---
config:
  logLevel: 1
  htmlLabels: true
  look: handDrawn
---
classDiagram
  Class01~T~ <|-- AveryLongClass : Cool
  Class03~T~ *-- Class04~T~
  Class01 : size()
  Class01 : int chimp
  Class01 : int gorilla
  Class08 <--> C2: Cool label
  class Class10~T~ {
    &lt;&lt;service&gt;&gt;
    int id
    test()
  }
