import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';
import { CommonValueConverter } from '../common/valueConverter.js';
import { MermaidGeneratedSharedModule, XYGeneratedModule } from '../generated/module.js';
import { XYTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `XY` services.
 */
interface XYAddedServices {
  parser: {
    TokenBuilder: XYTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `XY` services.
 */
export type XYServices = LangiumCoreServices & XYAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `XY` services.
 */
export const XYModule: Module<XYServices, PartialLangiumCoreServices & XYAddedServices> = {
  parser: {
    TokenBuilder: () => new XYTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createXYServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  XY: XYServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const XY: XYServices = inject(createDefaultCoreModule({ shared }), XYGeneratedModule, XYModule);
  shared.ServiceRegistry.register(XY);
  return { shared, XY };
}
