classDiagram
  note "This is a outer note"
  note for C1 "This is a outer note for C1"
  namespace Namespace1 {
    note "This is a inner note"
    note for C1 "This is a inner note for C1"
    class C1
  }
