---
config:
  look: handDrawn
---
flowchart LR
  classDef customClazz fill:#bbf,stroke:#f66,stroke-width:2px,color:#000,stroke-dasharray: 5 5
  n0 --> n00@{ shape: hourglass, label: 'new hourglass shape' }
  n00:::customClazz
