---
config:
  look: classic
---
flowchart TB
  classDef customClazz fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
  nA --> nAA@{ icon: 'fa:bell', label: 'new icon shape', form: 'rounded', pos: 't' }
  nAA:::customClazz
