---
config:
  look: handDrawn
  flowchart:
    htmlLabels: false
---
flowchart TB
  nA --> A@{ img: 'https://cdn.pixabay.com/photo/2020/02/22/18/49/paper-4871356_1280.jpg', label: 'This is **bold** </br>and <strong>strong</strong> for image shape', w: '250', h: '200', pos: 'b' }
