---
config:
  sankey:
    width: 800
    height: 500
    labelStyle: outlined
---
sankey

  iPhone,Products,205
  Mac,Products,40
  iPad,Products,29
  Wearables,Products,41
  Products,Revenue,315
  Services,Revenue,78
  Revenue,Cost of Revenue,223
  Revenue,Gross Profit,170
  Gross Profit,Op Expenses,51
  Gross Profit,Op Profit,119
  Op Profit,Tax,19
  Op Profit,Net Profit,100
