---
config:
  sankey:
    width: 800
    height: 500
    labelStyle: outlined
    showValues: true
    prefix: $
    suffix: B
    nodeColors:
      iPhone: '#6e6e73'
      Mac: '#6e6e73'
      iPad: '#6e6e73'
      Wearables: '#6e6e73'
      Products: '#6e6e73'
      Services: '#6e6e73'
      Revenue: '#424245'
      Cost of Revenue: '#ff3b30'
      Gross Profit: '#34c759'
      Op Expenses: '#ff3b30'
      Op Profit: '#34c759'
      Tax: '#ff3b30'
      Net Profit: '#34c759'
---
sankey

  iPhone,Products,205
  Mac,Products,40
  iPad,Products,29
  Wearables,Products,41
  Products,Revenue,315
  Services,Revenue,78
  Revenue,Cost of Revenue,223
  Revenue,Gross Profit,170
  Gross Profit,Op Expenses,51
  Gross Profit,Op Profit,119
  Op Profit,Tax,19
  Op Profit,Net Profit,100
