gantt
  title Style today marker (vertical line should be 5px wide and half-transparent blue)
  dateFormat YYYY-MM-DD
  axisFormat %d
  todayMarker stroke-width:5px,stroke:#00f,opacity:0.5
  section Section1
  Yesterday: 1010-10-09, 1d
  Today: 1010-10-10, 1d
