gantt
  title A Gantt Diagram
  dateFormat   SSS
  axisFormat   %Lms
  tickInterval 2millisecond
  excludes     weekends

  section Section
  A task           : a1, 000, 6ms
  Another task     : after a1, 6ms
  section Another
  Task in sec      : a2, 006, 3ms
  another task     : 3ms
