gantt
  title A Gantt Diagram
  dateFormat x
  axisFormat %L
  section Section
  A task           :a1, 0, 30ms
  Another task     :after a1, 20ms
  section Another
  Another another task      :b1, 20, 12ms
  Another another another task     :after b1, 0.024s
