gantt
  title A Gantt Diagram
  dateFormat   ss
  axisFormat   %Ss
  tickInterval 2second
  excludes     weekends

  section Section
  A task           : a1, 00, 6s
  Another task     : after a1, 6s
  section Another
  Task in sec      : 06, 3s
  another task     : 3s
