---
config:
  theme: dark
---
gantt
  dateFormat  YYYY-MM-DD
  title Gantt dark mode done-task inside-text readability

  section A section
  Done :done, 2014-01-06, 14d
  Active :active, 2014-01-20, 14d

  section Critical tasks
  Done critical :crit, done, 2014-01-06, 14d
