flowchart TB
    c1 --> a2
    subgraph one
        a1 --> a2
    end
    subgraph two
        direction LR
        b1 --> b2
    end
    subgraph three [Three with title]
        c1 --> c2
    end
    one --> two
