flowchart LR
    A:::important --> B
    C --> D
    classDef important fill:#f96,stroke:#333,stroke-width:4px
    classDef plain fill:#fff
    class B,C plain
    style D fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff
    linkStyle 0 stroke:red,stroke-width:3px
    linkStyle default interpolate basis stroke:#0a0
