flowchart LR
    sq[Square] --> ro(Round)
    ro --> st([Stadium])
    st --> sub[[Subroutine]]
    sub --> db[(Database)]
    db --> ci((Circle))
    ci --> dc(((Double circle)))
    dc --> di{Diamond}
    di --> hx{{Hexagon}}
    hx --> od>Odd]
    od --> tr[/Trapezoid/]
    tr --> it[\Inv trapezoid\]
    it --> lr[/Lean right\]
    lr --> ll[\Lean left/]
    ll --> el(-Ellipse-)
