flowchart TB
    A@{ shape: rounded, label: "Rounded" }
    B@{ shape: circle }
    A --> B
    C@{ shape: rounded } & D@{ shape: diamond } --> E
    F@{
        shape: circle
        label: "Multi
        line"
    }
