swimlane-beta TD
        A --> B --> C --> D --> E --> F --> G
        D --> H --> I --Yes--> J --> E
        I --No--> K --> L --> M & N
        subgraph Car
          A
        end
        subgraph Sales
          B
          M
        end

        subgraph Constr
          C
          D
          E
          H
          L
          N
        end
        subgraph Legal
          I
          J
          K
        end
        subgraph Fun
          F
          G
        end
