stateDiagram-v2
    [*] --> State1
    State1 --> State2
    State1 --> State3
    State1 --> State4
    State1 --> State5
    State2 --> State3
    State2 --> State4
    State2 --> State5
    State3 --> State4
    State3 --> State5
    State4 --> State5
    State5 --> [*]
