stateDiagram-v2
    [*] --> State1
    State1 --> State2
    State1 --> State3
    State1 --> State4
    State2 --> State3
    State2 --> State4
    State3 --> State4
    state State1: Description 1
    state State2: Description 2
    state State3: Description 3
    state State4: Description 4
    State4 --> [*]
