graph TD
  A[Contaminación] --> B[Tipos de contaminación]
  B --> C[Contaminación del aire]
  B --> D[Contaminación del agua]
  B --> E[Contaminación del suelo]
  B --> F[Contaminación acústica]
  B --> G[Contaminación lumínica]
  
  A --> H[Causas]
  H --> I[Emisiones industriales]
  H --> J[Uso de combustibles fósiles]
  H --> K[Desechos y residuos]
  H --> L[Uso de pesticidas]
  H --> M[Deforestación]
  
  A --> N[Efectos]
  N --> O[Calentamiento global]
  N --> P[Enfermedades respiratorias]
  N --> Q[Pérdida de biodiversidad]
  N --> R[Acidificación de océanos]
  N --> S[Alteración de ecosistemas]
  
  A --> T[Soluciones]
  T --> U[Energías renovables]
  T --> V[Reciclaje y reducción de residuos]
  T --> W[Conservación de bosques]
  T --> X[Legislación ambiental]
  T --> Y[Educación y conciencia ambiental]
