---
description: >-
  Minimal classDiagram with a single class given a custom text label, connected by a
  relationship to an implicitly-declared class.
---
classDiagram
  class C1["Class 1 with text label"]
  C1 -->  C2
