---
config:
  logLevel: 1
---
erDiagram
  ATLAS-ORGANIZATION ||--|{ ATLAS-PROJECTS : "has many"
  ATLAS-PROJECTS ||--|{ MONGODB-CLUSTERS : "has many"
  ATLAS-PROJECTS ||--|{ ATLAS-TEAMS : "has many"
  MONGODB-CLUSTERS ||..|{
  ATLAS-TEAMS ||..|{
