---
config:
  layout: elk
  elk:
    mergeEdges: false
    forceNodeModelOrder: false
    considerModelOrder: NONE

---
            flowchart TB
              a --> a1 & a2 & a3 & a4
              b --> b1 & b2
              b2 --> b3
              b1 --> b4
