---
config:
  layout: elk
  flowchart:
    curve: rounded
---
flowchart LR
    I["fa:fa-code Text"] -- Mermaid js --> D["Use<br/>the<br/>editor!"]
    I --> D & D
    D@{ shape: question}
    I@{ shape: question}
