agentflow TB
  llm["llm"]
  llm_query["llm.query"]
  net["net"]
  net_read["net.read"]
  llm -->> llm_query
  net -->> net_read

  llm@{ shape: hex }
  llm_query@{ shape: terminal }
  net@{ shape: hex }
  net_read@{ shape: terminal }
