---
config:
  look: handDrawn
  handDrawnSeed: 1
  fontFamily: courier
---
venn-beta
  title HandDrawn Skills
  set Frontend
  set Backend
  set DevOps
  union Frontend, Backend
  union Backend, DevOps
  union Frontend, DevOps
  union Frontend, Backend, DevOps
