---
config:
  theme: default
---
C4Context
  title Outline style, default theme

  Person(customerA, "Banking Customer A", "A customer of the bank.")
  System(SystemAA, "Internet Banking System", "Allows customers to view information.")
  System_Ext(SystemE, "Mainframe", "Stores all of the core banking information.")
  ContainerDb(db, "Database", "SQL Database", "Stores user registration information.")

  Rel(customerA, SystemAA, "Uses")
  Rel(SystemAA, db, "Reads from and writes to", "JDBC")
