C4Context
  title Relationship to a boundary

  Container_Boundary(banking, "Internet Banking") {
    Container(spa, "SPA", "JavaScript", "Front-end")
  }
  System_Ext(email, "Email System", "External mail")

  Rel(banking, email, "Forwards alerts")
