import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  NetworkGrammarGeneratedModule as NetworkGeneratedModule,
} from '../generated/module.js';
import { NetworkTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `Network` services.
 */
interface NetworkAddedServices {
  parser: {
    TokenBuilder: NetworkTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `Network` services.
 */
export type NetworkServices = LangiumCoreServices & NetworkAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Network` services.
 */
export const NetworkModule: Module<
  NetworkServices,
  PartialLangiumCoreServices & NetworkAddedServices
> = {
  parser: {
    TokenBuilder: () => new NetworkTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createNetworkServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  Network: NetworkServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Network: NetworkServices = inject(
    createDefaultCoreModule({ shared }),
    NetworkGeneratedModule,
    NetworkModule
  );
  shared.ServiceRegistry.register(Network);
  return { shared, Network };
}
