flowchart LR
    A1((A1))
    A2((A2))
    A3((A3))
    B1((B1))
    B2((B2))
    B3((B3))
    
    A1 --> B1
    A1 --> B2
    A1 --> B3
    A2 --> B1
    A2 --> B2
    A2 --> B3
    A3 --> B1
    A3 --> B2
    A3 --> B3