flowchart TD
    A --- B
    A --- C
    B --- D
    C --- D
    D --- E
    D --- F
    E --- G
    F --- G

    A --- A1 --- A11
    A1 --- A12
    A --- A2 --- A21
    A2 --- A22

    F --- F1 --- F11
    F1 --- F12
    F --- F2 --- F21
    

    G --- G1 --- G11
    G1 --- G12

    subgraph Subgraph
        A11
        G12
    end