---
config:
  layout: tidy-tree
---
mindmap
Risks
  LLMs can make simple diagrams
  Agentflow
    execution strategy
    untested features - overbuilding Risks
    contested market langchain & n8n
    Pricing: Break-even execution volumes unknown
    n15
  Large diagram performance
    LLMs facilitate easy migration out
    Distributed maintainer access
    Reputation - blame for downstreams vuln
    Too much depends on Knut
  Missing review protocols for AI authored code
  Enterprice customers AI use
