---
description: >-
  treemap-beta "Root" with three flat leaves; two of the three (Item A,
  Item C) are tagged with distinct classDefs (redClass, blueClass) that set
  only a fill color, verifying classDef fill-color styling applies
  correctly to individual leaf nodes.
---
treemap-beta
  "Root"
    "Item A": 30:::redClass
    "Item B": 20
    "Item C": 25:::blueClass

  classDef redClass fill:#ff0000;
  classDef blueClass fill:#0000ff;
