import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { WireframeValueConverter } from './valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  WireframeGrammarGeneratedModule as WireframeGeneratedModule,
} from '../generated/module.js';
import { WireframeTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `Wireframe` services.
 */
interface WireframeAddedServices {
  parser: {
    TokenBuilder: WireframeTokenBuilder;
    ValueConverter: WireframeValueConverter;
  };
}

/**
 * Union of Langium default services and `Wireframe` services.
 */
export type WireframeServices = LangiumCoreServices & WireframeAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Wireframe` services.
 */
export const WireframeModule: Module<
  WireframeServices,
  PartialLangiumCoreServices & WireframeAddedServices
> = {
  parser: {
    TokenBuilder: () => new WireframeTokenBuilder(),
    ValueConverter: () => new WireframeValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createWireframeServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  Wireframe: WireframeServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Wireframe: WireframeServices = inject(
    createDefaultCoreModule({ shared }),
    WireframeGeneratedModule,
    WireframeModule
  );
  shared.ServiceRegistry.register(Wireframe);
  return { shared, Wireframe };
}
