swimlane TD
subgraph X1
  A(Start)
  B{{B------}}
  I[I]
  id1[(Database)]
end
subgraph X3
  Sys1
  E
end
subgraph X2
  C{{C------------}}
  D{{D}}
  F
  G@{ shape: notch-pent }
  H
  exit(Exit)
end
  A --> Sys1
  --> B
  --> C
  --> D
  --> E
  --> F
  --> G
  %% try make it longer 
  --> H[H-]
  --> I
  --> exit