---
config:
  layout: swimlane
  swimlane:
    ignoreCrossLaneEdges: true
    optimizeRanksByCrossings: true
---
swimlane LR



  subgraph "Head of Engineering"
      E{Can answer?}
      E --Yes--> F(Answer)
      E --No --> G(Investigate) --> F2(Answer)
  end

    subgraph StatusSeeker
    A(Incoming query)
    A2{Knows<br/>which team?}
  end

  subgraph "Tech Lead"
      B{Can answer?}
      B --Yes--> C(Answer)

  end
  A --> A2
  A2 --Yes --> B
  A2 --No --> E
  B --No --> E
