---
config:
  logLevel: 1
  htmlLabels: true
  layout: elk
---
classDiagram
  class C1["Class with text label"]
  class C2["Class with text label"]
  class C3["Class with text label"]
  C1 --> C2
  C3 ..> C2
