---
config:
  logLevel: 1
  htmlLabels: true
  layout: elk
---
classDiagram
  class C1["OneWord"]
  class C2["With, Comma"]
  class C3["With (Brackets)"]
  class C4["With [Brackets]"]
  class C5["With {Brackets}"]
  class C7["With 1 number"]
  class C8["With . period..."]
  class C9["With - dash"]
  class C10["With _ underscore"]
  class C11["With ' single quote"]
  class C12["With ~!@#$%^&*()_+=-/?"]
  class C13["With Città foreign language"]
