treemap-beta
  "Products"
  "Electronics"
  "Phones": 50
  "Computers": 30
  "Accessories": 20
  "Clothing"
  "Men's"
      "Shirts": 10
      "Pants": 15
  "Women's"
      "Dresses": 20
      "Skirts": 10
