---
config:
  htmlLabels: false
---
flowchart TD
  a@{ shape: cyl, label: "Short" }
  b@{ shape: cyl, label: "kl lk kla lka lka lka lkas klasj kla klas" }
  c@{ shape: lin-cyl, label: "Short" }
  d@{ shape: h-cyl, label: "A longer label that wraps around" }
  e@{ shape: docs, label: "Short" }
  f@{ shape: st-rect, label: "A longer label that wraps around" }
  g@{ shape: div-rect, label: "Short" }
  h@{ shape: braces, label: "A longer label that wraps around" }
  i@{ shape: brace-l, label: "Short" }
  j@{ shape: tag-doc, label: "Short" }
  k@{ shape: win-pane, label: "A longer label that wraps around" }
  l@{ shape: lin-rect, label: "Short" }
  m@{ shape: sl-rect, label: "Short" }
  n@{ shape: flip-tri, label: "Short" }
  o@{ shape: delay, label: "A longer label that wraps around" }
  p@{ shape: text, label: "Short" }
  q@{ shape: notch-rect, label: "Short" }
  r@{ shape: doc, label: "Short" }
  a --> b --> c --> d
  e --> f --> g --> h
  i --> j --> k --> l
  m --> n --> o --> p
  q --> r
