---
config:
  logLevel: 1
---
erDiagram
  AUTHOR_WITH_LONG_ENTITY_NAME {
    string name PK
  }
  AUTHOR_WITH_LONG_ENTITY_NAME }|..|{ BOOK : writes
  BOOK {
      float price
      string author FK
      string title PK
    }
