---
config:
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart-elk LR
  classDef dark fill:#000,stroke:#000,stroke-width:4px,color:#fff
  Lorem --> Ipsum --> Dolor
  class Lorem,Dolor dark
