---
config:
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart-elk TB
  subgraph S1
   sub1 -->sub2
  end
  subgraph S2
   sub4
  end
  S1 --> S2
  sub1 --> sub4
