---
config:
  flowchart:
    titleTopMargin: 0
---
flowchart LR
  subgraph subgraph_ko6czgs5u["Untitled subgraph"]
        D["Option 1"]
  end
    C{"Evaluate"} -- One --> D
    C -- Two --> E(("Option 2"))
    D --> E
      A["A"]
