---
config:
  flowchart:
    titleTopMargin: 0
---
%%{init: {"flowchart": {"htmlLabels": false}} }%%
flowchart-elk LR
  a{"`The **cat** in the hat`"} -- 1o --> b
  a -- 2o --> c
  a -- 3o --> d
  g --2i--> a
  d --1i--> a
  h --3i -->a
  b --> d(The dog in the hog)
  c --> d
