---
config:
  xyChart:
    width: 4000
---
xychart
  title "Wide chart scaled down to fit"
  x-axis "Elapsed Time" 0 --> 10
  y-axis "Percentage (%)" 0 --> 100
  line "CPU" [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  line "RAM" [20, 30, 40, 50, 60, 70, 80, 90, 95, 90]
