---
config:
  xyChart:
    width: 1200
    height: 60
---
xychart
  title "Too short for a title"
  x-axis "Elapsed Time" 0 --> 10
  y-axis "Percentage (%)" 0 --> 100
  line "CPU" [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
