---
config:
  flowchart:
    htmlLabels: false
  fontFamily: courier
---
graph LR
  A(( )) -->|step 1| B(( ))
  B(( )) -->|step 2| C(( ))
  C(( )) -->|step 3| D(( ))
  linkStyle 1 stroke:greenyellow,stroke-width:2px
  style C fill:greenyellow,stroke:green,stroke-width:4px
