---
config:
  securityLevel: loose
  fontFamily: courier
---
graph TB
  TITLE["Link Click Events<br>(click the nodes below)"]
  A["link test (open in same tab)"]
  B["link test (open in new tab)"]
  C[anchor test]
  D[mailto test]
  E[other protocol test]
  F[script test]
  TITLE --> A & B & C & D & E & F
  click A "https://mermaid-js.github.io/mermaid/#/" "link test (open in same tab)"
  click B "https://mermaid-js.github.io/mermaid/#/" "link test (open in new tab)" _blank
  click C "#link-clicked"
  click D "mailto:user@user.user" "mailto test"
  click E "notes://do-your-thing/id" "other protocol test"
  click F "javascript:alert('test')" "script test"
