---
config:
  flowchart:
    nodeSpacing: 1
    rankSpacing: 1
---
---
  title: Subgraph nodeSpacing and rankSpacing example
  ---
  flowchart LR
  X --> Y
  subgraph X
    direction LR
    A
    C
  end
  subgraph Y
    B
    D
  end
