---
title: Subgraph nodeSpacing and rankSpacing example
config:
  flowchart:
    nodeSpacing: 250
    rankSpacing: 250
---
flowchart LR
  X --> Y
  subgraph X
    direction LR
    A
    C
  end
  subgraph Y
    B
    D
  end
