flowchart TD
  B[<img src='https://mermaid.js.org/mermaid-logo.svg'>]
  B-->C[<img src="https://mermaid.js.org/mermaid-logo.svg"> more text <img src='https://mermaid.js.org/mermaid-logo.svg'>]
  B-->D(<img src='https://mermaid.js.org/mermaid-logo.svg'> some text)
  B-->E(plain)
