---
config:
  fontFamily: courier
---
graph TD
  1A --> 1B
  1B --> 1C
  1C --> D
  1C --> E

  classDef processHead fill:#888888,color:white,font-weight:bold,stroke-width:3px,stroke:#001f3f
  class 1A,1B,D,E processHead
