---
config:
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart
  classDef cat fill:#f9d5e5, stroke:#233d4d,stroke-width:2px, font-weight:bold;
  CS(A long bold text to be viewed):::cat
