---
config:
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart
  Node1:::class1 --> Node2:::class2
  Node1:::class1 --> Node3:::class2
  Node3 --> Node4((I am a circle)):::larger

  classDef class1 fill:lightblue
  classDef class2 fill:pink
  classDef larger font-size:30px,fill:yellow
