flowchart TD
  A e1@-->B e5@--> E
  E e7@--> D
  B e3@-->D
  A e2@-->C e4@-->D
  C e6@--> F
  F e8@--> D
  e1@{ curve: natural }
  e2@{ curve: stepAfter }
  e3@{ curve: monotoneY }
  e4@{ curve: bumpY }
  e5@{ curve: linear }
  e6@{ curve: catmullRom }
  e7@{ curve: cardinal }
