---
config:
  flowchart:
    subGraphTitleMargin:
      top: 10
      bottom: 5
---
flowchart
  A --> A
  subgraph B
  B1 --> B1
  end
  subgraph C
  subgraph C1
    C2 --> C2
    subgraph D
      D1 --> D1
    end
    D --> D
  end
  C1 --> C1
  end
