---
config:
  markdownAutoWrap: false
---
flowchart TD
  angular_velocity["`**angular_velocity**
  *angular_displacement / duration*
  [rad/s, 1/s]
  {vector}`"]
  frequency["frequency
  (1 / period_duration)
  [Hz, 1/s]"]
