---
config:
  flowchart:
    titleTopMargin: 0
---
%%{init: {"flowchart": {"htmlLabels": true}} }%%
flowchart LR
  subgraph "One"
  a("`The **cat**
  in the hat`") -- "1o" --> b{{"`The **dog** in the hog`"}}
  end
  subgraph "`**Two**`"
  c("`The **cat**
  in the hat`") -- "`1o **ipa**`" --> d("The dog in the hog")
  end
