graph LR
  id1(Start) link@-- "Label" -->id2(Stop)
  style id1 fill:#f9f,stroke:#333,stroke-width:4px

  class id2 myClass
  classDef myClass fill:#bbf,stroke:#f66,stroke-width:2px,color:white,stroke-dasharray: 5 5
  class link myClass
