---
config:
  flowchart:
    titleTopMargin: 0
---
%%{init: {"flowchart": {"htmlLabels": true}} }%%
flowchart LR
  b("`The dog in **the** hog.(1).. a a a a *very long text* about it
  Word!

  Another line with many, many words. Another line with many, many words. Another line with many, many words. Another line with many, many words. Another line with many, many words. Another line with many, many words. Another line with many, many words. Another line with many, many words. `") --> c
