---
config:
  layout: dagre
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart TD
  subgraph  main
  subgraph subcontainer
    subcontainer-child
  end
   subcontainer-child--> subcontainer-sibling
  end
