---
config:
  layout: dagre
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
flowchart RL
  subgraph two
  b1
  end
  subgraph three
  c2
  end

  three --> two
  two --> c2
