C4Component
title Component variants
Component(c, "Component", "Tech", "A component")
Component_Ext(ce, "Component_Ext", "Tech", "An external component")
ComponentDb(cdb, "ComponentDb", "Tech", "A database component")
ComponentDb_Ext(cdbe, "ComponentDb_Ext", "Tech", "An external database component")
ComponentQueue(cq, "ComponentQueue", "Tech", "A queue component")
ComponentQueue_Ext(cqe, "ComponentQueue_Ext", "Tech", "An external queue component")
