C4Container
title Container variants
Container(c, "Container", "Tech", "A container")
Container_Ext(ce, "Container_Ext", "Tech", "An external container")
ContainerDb(cdb, "ContainerDb", "Tech", "A database container")
ContainerDb_Ext(cdbe, "ContainerDb_Ext", "Tech", "An external database container")
ContainerQueue(cq, "ContainerQueue", "Tech", "A queue container")
ContainerQueue_Ext(cqe, "ContainerQueue_Ext", "Tech", "An external queue container")
