C4Context
title System variants
System(s, "System", "A software system")
System_Ext(se, "System_Ext", "An external software system")
SystemDb(sdb, "SystemDb", "A data store")
SystemDb_Ext(sdbe, "SystemDb_Ext", "An external data store")
SystemQueue(sq, "SystemQueue", "A message queue")
SystemQueue_Ext(sqe, "SystemQueue_Ext", "An external message queue")
