wardley-beta
  title Kettle Evolution Pipeline
  size [1100, 800]

  component Kettle [0.57, 0.45]
  component Power [0.10, 0.70]
  component User [0.95, 0.50]

  Kettle -> Power
  User -> Electric Kettle

  pipeline Kettle {
  component Campfire Kettle [0.35] label [-60, 35]
  component Electric Kettle [0.53] label [-60, 35]
  component Smart Kettle [0.72] label [-30, 35]
  }

  Campfire Kettle -> Kettle
  Electric Kettle -> Kettle
  Smart Kettle -> Kettle
