wardley-beta
  title GPT Tokeniser
  size [1100, 800]

  anchor GPT Tokeniser [0.90, 0.58]

  component tokeniser [0.81, 0.58]
  component encoder [0.60, 0.32] label [1, -9]
  component decoder [0.60, 0.72]
  component methodology [0.72, 0.53]
  component training code [0.68, 0.26] label [-90, 2]
  component inference code [0.65, 0.37] label [-50, -12]
  component algo [0.53, 0.50] label [-15, -17]
  component GPT2 [0.81, 0.65] label [-14, 27]
  component GPT3 [0.81, 0.73] label [-15, 27]
  component GPT4 [0.81, 0.77] label [-14, 28]
  component GPT5 [0.81, 0.37] label [-10, 28]
  component GPT6 [0.81, 0.17] label [-20, 28]
  component GPT7 [0.81, 0.13] label [-13, 27]
  component tokeniser training data [0.29, 0.34] label [-74, -32]
  component special tokens [0.59, 0.26] label [-61, 15]
  component UTF8 [0.17, 0.74]
  component token vocabulary [0.41, 0.56] label [-25, 16]
  component byte pair encoding (BPE) [0.53, 0.76] label [-27, 19]
  component english text data [0.15, 0.37] label [0, 10]
  component code data [0.15, 0.30] label [-31, 23]
  component foreign text data [0.15, 0.23] label [-51, 18]
  component python [0.35, 0.84]
  component sentencepiece [0.25, 0.80] label [-49, 19]
  component IDE [0.27, 0.86]
  component MEGABYTE [0.53, 0.18] label [-28, 28]
  component text merging rules [0.60, 0.21] label [-64, -10]
  component security framework [0.67, 0.58] label [-27, 10]
  component Unicode Consortium [0.06, 0.55]
  component Unicode License v3 [0.13, 0.72] label [-29, 11]

  GPT Tokeniser -> tokeniser

  tokeniser -> methodology
  methodology -> training code
  methodology -> inference code
  methodology -> security framework

  training code -> special tokens
  training code -> python

  algo -> tokeniser training data
  training code -> text merging rules

  training code -> encoder
  inference code -> decoder
  encoder -> algo
  decoder -> algo

  algo -> token vocabulary

  byte pair encoding (BPE) -> UTF8
  MEGABYTE -> UTF8
  UTF8 -> Unicode License v3
  Unicode License v3 -> Unicode Consortium

  tokeniser training data -> english text data
  tokeniser training data -> code data
  tokeniser training data -> foreign text data

  python -> IDE
  python -> sentencepiece

  pipeline tokeniser {
  component tokeniser v1 [0.11]
  component tokeniser v2 [0.80]
  }

  pipeline methodology {
  component methodology v1 [0.20]
  component methodology v2 [0.80]
  }

  pipeline algo {
  component algo v1 [0.14]
  component algo v2 [0.80]
  }

  deaccelerator License Play [0.13, 0.78]

  annotations [1, 0]
  annotation 1,[0.57, 0.16] "Alternative algos in research"
  annotation 2,[0.57, 0.76] "Most popular, but not the most efficient"
  annotation 3,[0.20, 0.3] "Ensure balanced token vocabulary"
  annotation 4,[0.60, 0.28] "Required for delimiters"
  annotation 5,[0.70, 0.50] "A structured approach for achieving a goal"

  note "Voting members: Adobe, Amazon, Apple, Google, Meta, Microsoft, Netflix, Salesforce" [0.04, 0.35]
