wardley-beta
  title Sourcing Strategies
  size [1100, 800]

  component Custom Built [0.80, 0.20] (build)
  component Off The Shelf [0.65, 0.45] (buy)
  component Outsourced Service [0.50, 0.65] (outsource)
  component Marketplace [0.35, 0.80] (market)
  component Platform [0.20, 0.92] (ecosystem)
