wardley-beta
  title Pioneers, Settlers, Town Planners
  size [1100, 800]

  pioneers [0.95, 0.05, 0.55, 0.30]
  settlers [0.95, 0.35, 0.55, 0.65]
  townplanners [0.95, 0.70, 0.55, 0.95]

  component Custom Research [0.80, 0.15]
  component Product [0.55, 0.50]
  component Commodity Service [0.30, 0.85]
