import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  YearwheelGrammarGeneratedModule as YearwheelGeneratedModule,
} from '../generated/module.js';
import { YearwheelTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `Yearwheel` services.
 */
interface YearwheelAddedServices {
  parser: {
    TokenBuilder: YearwheelTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `Yearwheel` services.
 */
export type YearwheelServices = LangiumCoreServices & YearwheelAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Yearwheel` services.
 */
export const YearwheelModule: Module<
  YearwheelServices,
  PartialLangiumCoreServices & YearwheelAddedServices
> = {
  parser: {
    TokenBuilder: () => new YearwheelTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createYearwheelServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  Yearwheel: YearwheelServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Yearwheel: YearwheelServices = inject(
    createDefaultCoreModule({ shared }),
    YearwheelGeneratedModule,
    YearwheelModule
  );
  shared.ServiceRegistry.register(Yearwheel);
  return { shared, Yearwheel };
}
