---
config:
  theme: forest
---
---
  config:
  theme: base
  themeVariables:
  primaryColor: '#ff0000'
  ---
  graph TD
        A(Start) --> B[/Another/]
        A[/Another/] --> C[End]
        subgraph section
          B
          C
        end
