import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import {
  MermaidGeneratedSharedModule,
  C4GrammarGeneratedModule as C4GeneratedModule,
} from '../generated/module.js';
import { C4TokenBuilder } from './tokenBuilder.js';
import { C4ValueConverter } from './valueConverter.js';

/**
 * Declaration of `C4` services.
 */
interface C4AddedServices {
  parser: {
    TokenBuilder: C4TokenBuilder;
    ValueConverter: C4ValueConverter;
  };
}

/**
 * Union of Langium default services and `C4` services.
 */
export type C4Services = LangiumCoreServices & C4AddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `C4` services.
 */
export const C4Module: Module<C4Services, PartialLangiumCoreServices & C4AddedServices> = {
  parser: {
    TokenBuilder: () => new C4TokenBuilder(),
    ValueConverter: () => new C4ValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createC4Services(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  C4: C4Services;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const C4: C4Services = inject(createDefaultCoreModule({ shared }), C4GeneratedModule, C4Module);
  shared.ServiceRegistry.register(C4);
  return { shared, C4 };
}
