treeView-beta
  my-project/
  src/
      App.tsx :::highlight icon(fa:bell) ## main component
      index.js ## entry point
      styles.css
  .env ## environment variables
  Dockerfile
  package.json
