---
config:
  treeView:
    showIcons: true
    defaultIconPack: material-icon-theme
    filenameIcons:
      README.md: 'fa:bell'
    extensionIcons:
      .ts: typescript
      .py: none
      .xyz: javascript
---
treeView-beta
  src/
      main.py
      data.xyz
      index.ts
      unmapped.bin
  README.md
