---
config:
  look: handDrawn
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
graph TD
  classDef default fill:#a34,stroke:#000,stroke-width:4px,color:#fff
  hello --> default
