---
config:
  look: handDrawn
  htmlLabels: true
  flowchart:
    htmlLabels: true
  securityLevel: loose
---
graph LR
  id1(Start)-->id2(Stop)
  style id1 fill:#f9f,stroke:#333,stroke-width:4px
  style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
