---
config:
  look: handDrawn
  flowchart:
    htmlLabels: false
  fontFamily: courier
---
graph TD
  A[ h ] -- hello --> B[" test "]:::exClass & C --> D;
  classDef exClass background:#bbb,border:1px solid red;
