---
config:
  look: handDrawn
  flowchart:
    htmlLabels: false
  fontFamily: courier
---
graph LR
  A[red<br>text] -->|red<br>text| B(blue<br>text)
  C[/red<br/>text/] -->|blue<br/>text| D{blue<br/>text}
  E{{default<br />style}} -->|default<br />style| F([default<br />style])
  linkStyle default color:Sienna;
  linkStyle 0 color:red;
  linkStyle 1 stroke:DarkGray,stroke-width:2px,color:#0000ff
  style A color:red;
  style B color:blue;
  style C stroke:#ff0000,fill:#ffcccc,color:#ff0000
  style D stroke:#0000ff,fill:#ccccff,color:#0000ff
  click B "index.html#link-clicked" "link test"
  click D testClick "click test"
