---
config:
  look: handDrawn
  fontFamily: courier
---
graph TD
  A[/Christmas\]
  A -->|Get money| B[\Go shopping/]
  B --> C{Let me thinksssss<br/>ssssssssssssssssssssss<br/>sssssssssssssssssssssssssss}
  C -->|One| D[/Laptop/]
  C -->|Two| E[\iPhone\]
  C -->|Three| F[Car]
