block-beta
  columns 9
  A space B
  C space D
  E space F
  G space H
  I space J
  K space L
  M space N
  O space P
  Q space R
  A --- B
  C --> D
  E <--> F
  G === H
  I ==> J
  K <==> L
  M -.- N
  O -.-> P
  Q <-.-> R
