block
  columns 3
  space blockArrowId1<["down"]>(down) space
  blockArrowId2<["right"]>(right) blockArrowId3<["Sync"]>(x, y) blockArrowId4<["left"]>(left)
  space blockArrowId5<["up"]>(up) space
  blockArrowId6<["x"]>(x) space blockArrowId7<["y"]>(y)
