import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import { MermaidGeneratedSharedModule, ContextMapGeneratedModule } from '../generated/module.js';
import { ContextMapTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `ContextMap` services.
 */
interface ContextMapAddedServices {
  parser: {
    TokenBuilder: ContextMapTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `ContextMap` services.
 */
export type ContextMapServices = LangiumCoreServices & ContextMapAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `ContextMap` services.
 */
export const ContextMapModule: Module<
  ContextMapServices,
  PartialLangiumCoreServices & ContextMapAddedServices
> = {
  parser: {
    TokenBuilder: () => new ContextMapTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createContextMapServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  ContextMap: ContextMapServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const ContextMap: ContextMapServices = inject(
    createDefaultCoreModule({ shared }),
    ContextMapGeneratedModule,
    ContextMapModule
  );
  shared.ServiceRegistry.register(ContextMap);
  return { shared, ContextMap };
}
