import type { DiagramLanguageData, SyntaxSnippet } from './types.js';
import {
  C4_IDENTIFIER_PATTERNS,
  CLASS_IDENTIFIER_PATTERNS,
  ER_IDENTIFIER_PATTERNS,
  GIT_GRAPH_IDENTIFIER_PATTERNS,
  REQUIREMENT_IDENTIFIER_PATTERNS,
  SEQUENCE_IDENTIFIER_PATTERNS,
  STATE_IDENTIFIER_PATTERNS,
  collectIdentifiers,
  flowchartIdentifiers,
} from './identifiers.js';

const snip = (label: string, insertText: string, documentation?: string): SyntaxSnippet =>
  documentation ? { documentation, insertText, label } : { insertText, label };

type CuratedDiagram = Omit<DiagramLanguageData, 'detector' | 'engine' | 'grammarId' | 'tokens'>;

const FLOWCHART_SHAPES: SyntaxSnippet[] = [
  snip('[Rectangle]', '${1:A}[${2:Label}]', 'Rectangular node.'),
  snip('(Rounded)', '${1:A}(${2:Label})', 'Node with rounded corners.'),
  snip('([Stadium])', '${1:A}([${2:Label}])', 'Stadium-shaped node.'),
  snip('[[Subroutine]]', '${1:A}[[${2:Label}]]', 'Subroutine-shaped node.'),
  snip('[(Database)]', '${1:A}[(${2:Label})]', 'Cylindrical database node.'),
  snip('((Circle))', '${1:A}((${2:Label}))', 'Circular node.'),
  snip('{Rhombus}', '${1:A}{${2:Decision}}', 'Diamond-shaped decision node.'),
  snip('{{Hexagon}}', '${1:A}{{${2:Label}}}', 'Hexagonal node.'),
  snip('[/Parallelogram/]', '${1:A}[/${2:Label}/]', 'Parallelogram-shaped node.'),
  snip('[\\Trapezoid\\]', '${1:A}[\\${2:Label}\\]', 'Trapezoid-shaped node.'),
  snip('>Asymmetric]', '${1:A}>${2:Label}]', 'Asymmetric flag-shaped node.'),
];

const FLOWCHART_SNIPPETS: SyntaxSnippet[] = [
  snip('Node and edge', '${1:A}[${2:Label}] --> ${3:B}[${4:Label}]'),
  snip('Edge with label', '${1:A} -->|${2:label}| ${3:B}'),
  snip('subgraph', 'subgraph ${1:title}\n\t${2:A} --> ${3:B}\nend', 'Group nodes into a subgraph.'),
  snip('classDef style', 'classDef ${1:className} fill:${2:#f9f},stroke:${3:#333}'),
  snip('style node', 'style ${1:A} fill:${2:#f9f},stroke:${3:#333}'),
  snip('linkStyle', 'linkStyle ${1:0} stroke:${2:#f00}'),
  snip('click link', 'click ${1:A} href "${2:https://example.com}"'),
  snip('direction', 'direction ${1|TB,TD,BT,RL,LR|}'),
];

export const curatedDiagrams: readonly CuratedDiagram[] = [
  {
    docsUrl: 'https://mermaid.js.org/syntax/flowchart.html',
    extractIdentifiers: flowchartIdentifiers,
    id: 'flowchart',
    snippets: [...FLOWCHART_SHAPES, ...FLOWCHART_SNIPPETS],
    suppressAfterColon: true,
    title: 'Flowchart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/sequenceDiagram.html',
    extractIdentifiers: (text) => collectIdentifiers(text, SEQUENCE_IDENTIFIER_PATTERNS),
    id: 'sequenceDiagram',
    snippets: [
      snip('participant', 'participant ${1:A} as ${2:Alice}'),
      snip('actor', 'actor ${1:A} as ${2:Alice}'),
      snip('Message', '${1:A}->>${2:B}: ${3:Hello}'),
      snip('Reply', '${1:B}-->>${1:A}: ${3:Hi}'),
      snip('Note over', 'Note over ${1:A},${2:B}: ${3:text}'),
      snip('Note right of', 'Note right of ${1:A}: ${2:text}'),
      snip('alt block', 'alt ${1:condition}\n\t${2}\nelse ${3:other}\n\t${4}\nend'),
      snip('loop block', 'loop ${1:condition}\n\t${2}\nend'),
      snip('opt block', 'opt ${1:condition}\n\t${2}\nend'),
      snip('par block', 'par ${1:action}\n\t${2}\nand ${3:other action}\n\t${4}\nend'),
      snip('critical block', 'critical ${1:action}\n\t${2}\noption ${3:condition}\n\t${4}\nend'),
      snip('break', 'break ${1:condition}\n\t${2}\nend'),
      snip('activate', 'activate ${1:A}'),
      snip('deactivate', 'deactivate ${1:A}'),
      snip('autonumber', 'autonumber'),
    ],
    suppressAfterColon: true,
    title: 'Sequence diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/classDiagram.html',
    extractIdentifiers: (text) => collectIdentifiers(text, CLASS_IDENTIFIER_PATTERNS),
    id: 'classDiagram',
    snippets: [
      snip(
        'class with members',
        'class ${1:Animal} {\n\t${2:+String name}\n\t${3:+makeSound()}\n}'
      ),
      snip('interface annotation', '<<interface>> ${1:ClassName}'),
      snip('enumeration annotation', '<<enumeration>> ${1:ClassName}'),
      snip('Member', '${1:Animal} : ${2:+int age}'),
      snip('Inheritance', '${1:Dog} --|> ${2:Animal}'),
      snip('Composition', '${1:Car} *-- ${2:Engine}'),
      snip('Aggregation', '${1:Department} o-- ${2:Employee}'),
      snip('Association', '${1:Customer} --> ${2:Order}'),
      snip('Dependency', '${1:Order} ..> ${2:Payment}'),
      snip('namespace', 'namespace ${1:Base} {\n\tclass ${2:Shape}\n}'),
    ],
    suppressAfterColon: false,
    title: 'Class diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/stateDiagram.html',
    extractIdentifiers: (text) => collectIdentifiers(text, STATE_IDENTIFIER_PATTERNS),
    id: 'stateDiagram',
    snippets: [
      snip('state block', 'state ${1:Name} {\n\t${2:State1} --> ${3:State2}\n}'),
      snip('State transition', '${1:State1} --> ${2:State2}'),
      snip('Start transition', '[*] --> ${1:State}'),
      snip('End transition', '${1:State} --> [*]'),
      snip('State description', '${1:State} : ${2:description}'),
      snip('Long name alias', 'state "${1:Long name}" as ${2:s}'),
      snip('note right of', 'note right of ${1:State} : ${2:text}'),
      snip('note block', 'note right of ${1:State}\n\t${2:text}\nend note'),
      snip('fork state', 'state ${1:fork_state} <<fork>>'),
      snip('join state', 'state ${1:join_state} <<join>>'),
      snip('choice state', 'state ${1:choice_state} <<choice>>'),
    ],
    suppressAfterColon: true,
    title: 'State diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/entityRelationshipDiagram.html',
    extractIdentifiers: (text) => collectIdentifiers(text, ER_IDENTIFIER_PATTERNS),
    id: 'erDiagram',
    snippets: [
      snip('Relationship', '${1:CUSTOMER} ||--o{ ${2:ORDER} : ${3:places}'),
      snip('Entity block', '${1:CUSTOMER} {\n\t${2:string} ${3:name}\n}'),
    ],
    suppressAfterColon: true,
    title: 'Entity relationship diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/gantt.html',
    id: 'gantt',
    snippets: [
      snip('Task with dates', '${1:Task} :${2:task1}, ${3:2024-01-01}, ${4:30d}'),
      snip('Task after another', '${1:Task} :${2:task2}, after ${3:task1}, ${4:30d}'),
      snip('Milestone', '${1:Milestone} :milestone, ${2:m1}, ${3:2024-01-01}, 0d'),
      snip('section', 'section ${1:Phase}'),
      snip('excludes weekends', 'excludes weekends'),
      snip('dateFormat', 'dateFormat ${1|YYYY-MM-DD,DD-MM-YYYY,MM-DD-YYYY|}'),
    ],
    suppressAfterColon: true,
    title: 'Gantt chart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/pie.html',
    id: 'pie',
    snippets: [snip('Slice', '"${1:Label}" : ${2:42}')],
    suppressAfterColon: true,
    title: 'Pie chart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/gitgraph.html',
    extractIdentifiers: (text) => collectIdentifiers(text, GIT_GRAPH_IDENTIFIER_PATTERNS),
    id: 'gitGraph',
    snippets: [
      snip('commit', 'commit'),
      snip('commit with id', 'commit id: "${1:abc123}"'),
      snip('commit with tag', 'commit id: "${1:abc123}" tag: "${2:v1.0}"'),
      snip('commit with type', 'commit type: ${1|NORMAL,REVERSE,HIGHLIGHT|}'),
      snip('branch', 'branch ${1:feature}'),
      snip('checkout', 'checkout ${1:main}'),
      snip('merge', 'merge ${1:feature}'),
      snip('cherry-pick', 'cherry-pick id: "${1:abc123}"'),
    ],
    suppressAfterColon: true,
    title: 'Git graph',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/userJourney.html',
    id: 'journey',
    snippets: [snip('Task', '${1:Task}: ${2:5}: ${3:Me}')],
    suppressAfterColon: true,
    title: 'User journey',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/requirementDiagram.html',
    extractIdentifiers: (text) => collectIdentifiers(text, REQUIREMENT_IDENTIFIER_PATTERNS),
    id: 'requirementDiagram',
    snippets: [
      snip(
        'requirement block',
        'requirement ${1:req1} {\n\tid: ${2:1}\n\ttext: ${3:description}\n\trisk: ${4|low,medium,high|}\n\tverifymethod: ${5|analysis,inspection,test,demonstration|}\n}'
      ),
      snip('element block', 'element ${1:name} {\n\ttype: ${2:simulation}\n\tdocRef: ${3:ref}\n}'),
      snip(
        'Relation',
        '${1:req1} - ${2|contains,copies,derives,satisfies,verifies,refines,traces|} -> ${3:req2}'
      ),
    ],
    suppressAfterColon: false,
    title: 'Requirement diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/c4.html',
    extractIdentifiers: (text) => collectIdentifiers(text, C4_IDENTIFIER_PATTERNS),
    id: 'c4Diagram',
    snippets: [
      snip('Person', 'Person(${1:alias}, "${2:Label}")'),
      snip('System', 'System(${1:alias}, "${2:Label}")'),
      snip('System_Ext', 'System_Ext(${1:alias}, "${2:Label}")'),
      snip('Container', 'Container(${1:alias}, "${2:Label}", "${3:Technology}")'),
      snip('ContainerDb', 'ContainerDb(${1:alias}, "${2:Label}", "${3:Technology}")'),
      snip('Component', 'Component(${1:alias}, "${2:Label}", "${3:Technology}")'),
      snip('Deployment_Node', 'Deployment_Node(${1:alias}, "${2:Label}", "${3:Type}")'),
      snip('Boundary', 'Boundary(${1:alias}, "${2:Label}") {\n\t${3}\n}'),
      snip('Relationship', 'Rel(${1:from}, ${2:to}, "${3:Label}")'),
    ],
    suppressAfterColon: false,
    title: 'C4 diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/mindmap.html',
    id: 'mindmap',
    snippets: [
      snip('root', 'root((${1:Root}))'),
      snip('square node', '[${1:Node}]'),
      snip('rounded node', '(${1:Node})'),
      snip('circle node', '((${1:Node}))'),
      snip('hexagon node', '{{${1:Node}}}'),
    ],
    suppressAfterColon: false,
    title: 'Mindmap',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/timeline.html',
    id: 'timeline',
    snippets: [snip('Period', '${1:2024} : ${2:Event}')],
    suppressAfterColon: true,
    title: 'Timeline',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/quadrantChart.html',
    id: 'quadrantChart',
    snippets: [
      snip('Point', '${1:Point}: [${2:0.5}, ${3:0.5}]'),
      snip('x-axis', 'x-axis ${1:Low} --> ${2:High}'),
      snip('y-axis', 'y-axis ${1:Low} --> ${2:High}'),
      snip('quadrant-1', 'quadrant-1 ${1:Label}'),
    ],
    suppressAfterColon: true,
    title: 'Quadrant chart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/xyChart.html',
    id: 'xychart',
    snippets: [
      snip('bar series', 'bar [${1:1, 2, 3}]'),
      snip('line series', 'line [${1:1, 2, 3}]'),
      snip('x-axis labels', 'x-axis [${1:a, b, c}]'),
      snip('y-axis range', 'y-axis ${1:0} --> ${2:100}'),
    ],
    suppressAfterColon: false,
    title: 'XY chart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/sankey.html',
    id: 'sankey',
    snippets: [snip('Flow', '${1:Source},${2:Target},${3:10}')],
    suppressAfterColon: true,
    title: 'Sankey diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/info.html',
    id: 'info',
    snippets: [],
    suppressAfterColon: true,
    title: 'Info',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/kanban.html',
    id: 'kanban',
    snippets: [snip('Task', '${1:[Task]}')],
    suppressAfterColon: false,
    title: 'Kanban board',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/packet.html',
    id: 'packet',
    snippets: [snip('Field', '${1:0}-${2:15}: "${3:Field name}"')],
    suppressAfterColon: true,
    title: 'Packet diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/architecture.html',
    id: 'architecture',
    snippets: [
      snip('group', 'group ${1:api}(cloud)[${2:API}]'),
      snip('service', 'service ${1:db}(database)[${2:DB}]'),
      snip('service in group', 'service ${1:app}(server)[${2:App}] in ${3:api}'),
      snip('Connection', '${1:db}:${2:R} -- ${3:L}:${4:server}'),
    ],
    suppressAfterColon: false,
    title: 'Architecture diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/block.html',
    id: 'block',
    snippets: [
      snip('columns', 'columns ${1:3}'),
      snip('block', 'block${1::id}["${2:Label}"]'),
      snip('space', 'space'),
      snip('group block', 'block:${1:group}["${2:Label}"]\n\t${3}\nend'),
    ],
    suppressAfterColon: true,
    title: 'Block diagram',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/treemap.html',
    id: 'treemap',
    snippets: [snip('Section', '"${1:Section}"'), snip('Leaf with value', '"${1:Leaf}": ${2:10}')],
    suppressAfterColon: true,
    title: 'Treemap',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/radar.html',
    id: 'radar',
    snippets: [
      snip('axis', 'axis ${1:a}, ${2:b}, ${3:c}'),
      snip('curve', 'curve ${1:curve1}{${2:1}, ${3:2}, ${4:3}}'),
    ],
    suppressAfterColon: false,
    title: 'Radar chart',
  },
  {
    docsUrl: 'https://mermaid.js.org/syntax/zenuml.html',
    id: 'zenuml',
    snippets: [
      snip('Message', '${1:Alice} -> ${2:Bob}: ${3:Message}'),
      snip('Actor', '@Actor ${1:User}'),
      snip('if block', 'if (${1:condition}) {\n\t${2}\n}'),
    ],
    suppressAfterColon: true,
    title: 'ZenUML',
  },
];
