---
config:
  layout: grid
  grid:
    placements:
      root: { row: 2, column: 2 }
      Plan: { row: 1, column: 1 }
      Build: { row: 3, column: 1 }
      Test: { row: 1, column: 3 }
      Deploy: { row: 3, column: 3 }
---
mindmap
  root((Release))
    Plan
    Build
      Test
    Deploy
