---
config:
  layout: grid
---
flowchart TB
  TL["Top left"]@{ row: 1, column: 1 }
  TR["Top right"]@{ row: 1, column: 3 }
  BL["Bottom left"]@{ row: 3, column: 1 }
  BR["Bottom right"]@{ row: 3, column: 3 }

  TL --> BR
  TR --> BL

