flowchart TB
    A
    B
    C
    D
    E 
    F
    G

    A --- B
    A --- C
    B --- D
    C --- D
    D --- E
    D --- F
    E --- G
    F --- G

    A --- A1
    A --- A2
    A1 --- A11
    A1 --- A12
    A1 --- A13
    A11 --- A111
    A11 --- A112
    A13 --- A131
    A13 --- A132
    A13 --- A133

    B --- B1
    B --- B2
    B --- B3
    B --- B4
    B --- B5
    B --- B6
    B1 --- B11
    B1 --- B12
    B3 --- B31
    B3 --- B32
    B3 --- B33
    B3 --- B34
    B6 --- B61

    C --- C1
    C --- C2
    C1 --- C11
    C1 --- C12
    C11 --- C111
    C11 --- C112
    C111 --- C1111
    C111 --- C1112
    C111 --- C1113
    C12 --- C121
    C121 --- C1211

    D --- D1
    D --- D2
    D --- D3
    D --- D4
    D --- D5
    D1 --- D11
    D1 --- D12
    D1 --- D13
    D2 --- D21
    D2 --- D22
    D2 --- D23
    D2 --- D24
    D2 --- D25
    D2 --- D26
    D4 --- D41
    D11 --- D111
    D11 --- D112
    D13 --- D131
    D13 --- D132
    D13 --- D133
    D13 --- D134
    D22 --- D221
    D25 --- D251
    D25 --- D252
    D25 --- D253

    E --- E1
    E --- E2
    E --- E3
    E1 --- E11
    E1 --- E12
    E1 --- E13
    E1 --- E14
    E1 --- E15
    E1 --- E16
    E3 --- E31
    E11 --- E111
    E11 --- E112
    E14 --- E141
    E31 --- E311
    E31 --- E312
    E31 --- E313
    E111 --- E1111
    E112 --- E1121
    E112 --- E1122
    E313 --- E3131

    F --- F1
    F --- F2
    F --- F3
    F --- F4
    F1 --- F11
    F3 --- F31
    F3 --- F32
    F11 --- F111
    F31 --- F311
    F31 --- F312
    F31 --- F313
    F31 --- F314
    F31 --- F315
    F32 --- F321

    G --- G1
    G --- G2
    G --- G3
    G --- G4
    G --- G5
    G1 --- G11
    G1 --- G12
    G1 --- G13
    G2 --- G21
    G4 --- G41
    G4 --- G42
    G4 --- G43
    G4 --- G44
    G4 --- G45
    G4 --- G46
    G11 --- G111
    G11 --- G112
    G13 --- G131
    G13 --- G132
    G13 --- G133
    G41 --- G411
    G44 --- G441
    G44 --- G442
    G111 --- G1111
    G111 --- G1112
    G133 --- G1331
    G442 --- G4421
    G442 --- G4422
    G442 --- G4423