flowchart TD
    C1 --- C2
    C2 --- C3
    C3 --- C4
    C4 --- C1

    C1 --- C1_1
    C1 --- C1_2
    C1_1 --- C1_11
    C1_1 --- C1_12
    C1_1 --- C1_13
    C1_11 --- C1_111
    C1_2 --- C1_21

    C2 --- C2_1
    C2 --- C2_2
    C2_1 --- C2_11
    C2_1 --- C2_12

    C3 --- C3_1
    C3_1 --- C3_11
    C3_1 --- C3_12

    C4 --- C4_1
    C4 --- C4_2
    C4_1 --- C4_11
    C4_1 --- C4_12
    C4_2 --- C4_21
    C4_2 --- C4_22
    C4_11 --- C4_111
    C4_11 --- C4_112
    C4_12 --- C4_121
    C4_12 --- C4_122
    C4_21 --- C4_211
    C4_22 --- C4_221
    C4_111 --- C4_1111
    C4_112 --- C4_1121

    C1[Lorem ipsum dolor sit amet, consectetur adipiscing elit.]
    C2[Aliquam ultricies tempus rhoncus.]
    C4[Etiam congue enim vel tempor mollis.]
    C5[Mauris consectetur fermentum ornare.]
    C1_2[Mauris euismod consequat mi, vitae iaculis leo sollicitudin non.]
    C3_11[Quisque non urna ultrices, lobortis libero ac, vestibulum sem.]
    C2_1[Nulla dapibus libero gravida placerat tristique.]
    C2_11[Vestibulum bibendum ligula non diam maximus posuere.]
    C2_12[Ut urna leo, elementum at convallis a, vehicula cursus purus.]
    C3[Curabitur lacinia congue felis, non cursus arcu tempus quis. Suspendisse condimentum libero sed felis ullamcorper fermentum eget in massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ullamcorper convallis erat at sodales. Aenean risus arcu, euismod sit amet lacus sed, tincidunt blandit dolor. Proin dapibus accumsan nulla. Sed lacus ex, placerat suscipit finibus vitae, convallis at dui.]
    C4_112[Mauris hendrerit sapien ac enim luctus dictum.]
    C4_11[Nam vel elit sed elit cursus rutrum.]
    C1_111[Maecenas ut magna eu enim viverra tempus.]
    C1_13[Sed vel sapien eu elit aliquet scelerisque.]
    C4_2[Integer dictum nisi non tincidunt sagittis.]


