graph TD

    C["C lungo"]
    F["F </br> al </br> to"]
    L["L lungo"]
    N["N </br> grosso"]

    A --- C
    B --- C
    C --- D
    D --- E

    E --- F
    F --- G 
    G --- H
    H --- E

    E --- I
    I --- L
    L --- M
    M --- N
    N --- O 
    O --- E

