flowchart TD
    A[Node A]
    B[Node B]
    C[Node C]
    D[Node D]
    
    A --- B
    A --- C
    A --- D
    B --- A
    B --- C
    B --- D
    C --- A
    C --- B
    C --- D
    D --- A
    D --- B
    D --- C