flowchart
A["RNA Sequencing"] -- Differential Gene Expression Analysis -->  B("B: Investigate how SOX2 is implicated in endothelial to mesenchymal transition and how expression affects the migration of GBM cells")
B --> D["D: Investigate and isolate migratory glioblastoma with regards to phenotype"]
L("L: Expression of markers for stemness, EMT and invasion pattern")
D -- RNA Sequencing --> L
