bpmn-beta LR
  lane "Catching events"
    start message a1 "Message"
    start timer a2 "Timer"
    start conditional a3 "Conditional"
    start signal a4 "Signal"
    intermediate link a5 "Link"
    intermediate multiple a6 "Multiple"
    start parallel-multiple a7 "Parallel multiple"
