bpmn-beta LR
  lane "Throwing events"
    end message b1 "Message"
    end error b2 "Error"
    end escalation b3 "Escalation"
    end cancel b4 "Cancel"
    end terminate b5 "Terminate"
    throw compensation b6 "Compensation"
    throw signal b7 "Signal"
