bpmn-beta TB
  lane "Gateways"
    xor g1 "Exclusive"
    and g2 "Parallel"
    or g3 "Inclusive"
    event-gateway g4 "Event-based"
    complex g5 "Complex"
  lane "Activities"
    user task t1 "User"
    service task t2 "Service"
    script task t3 "Script"
    manual task t4 "Manual"
    subprocess t5 "Sub-process"
    call t6 "Call activity"
