gitGraph
  commit id: "ZERO"
  branch feature
  branch release
  checkout feature
  commit id: "A"
  commit id: "B"
  checkout main
  merge feature id: "M"
  checkout release
  cherry-pick id: "M" parent:"B"
