---
config:
  gitGraph:
    parallelCommits: false
---
gitGraph
  commit id:"1-abcdefg"
  commit id:"2-abcdefg"
  branch develop
  commit id:"3-abcdefg"
  commit id:"4-abcdefg"
  checkout main
  branch feature
  commit id:"5-abcdefg"
  commit id:"6-abcdefg"
  checkout main
  commit id:"7-abcdefg"
  commit id:"8-abcdefg"
