%%{init: { 'logLevel': 'debug', 'theme': 'default' , 'gitGraph': {
        'rotateCommitLabel': false
  } } }%%
gitGraph BT:
  commit id: "Alpha"
  commit id: "Beta"
  commit id: "Gamma"
  commit id: "Delta"
