gitGraph BT:
  commit id:"1-abcdefg"
  branch x
  checkout main
  commit id:"2-abcdefg"
  checkout x
  commit id:"3-abcdefg"
  checkout main
  merge x
  checkout x
  branch y
  checkout x
  commit id:"4-abcdefg"
  checkout y
  commit id:"5-abcdefg"
  checkout x
  merge y
