---
config:
  gitGraph:
    parallelCommits: true
---
gitGraph BT:
  branch dev
  branch v2
  branch feat
  commit id:"1-abcdefg"
  commit id:"2-abcdefg"
  checkout main
  commit id:"3-abcdefg"
  checkout dev
  commit id:"4-abcdefg"
  checkout v2
  commit id:"5-abcdefg"
  checkout main
  commit id:"6-abcdefg"
