gitGraph
  commit id: "1"
  commit id: "2"
  branch nice_feature
  switch nice_feature
  commit id: "3"
  switch main
  commit id: "4"
  switch nice_feature
  branch very_nice_feature
  switch very_nice_feature
  commit id: "5"
  switch main
  commit id: "6"
  switch nice_feature
  commit id: "7"
  switch main
  merge nice_feature id: "12345" tag: "my merge commit"
  switch very_nice_feature
  commit id: "8"
  switch main
  commit id: "9"
