gitGraph
  switch main
  %% Make sure to manually set the id of all commits, for consistent visual tests
  commit id: "1-abcdefg"
  switch main
  branch branch1
  commit id: "2-abcdefg"
  switch main
  merge branch1
  branch branch2
  commit id: "3-abcdefg"
  switch main
  merge branch2
  branch branch3
  commit id: "4-abcdefg"
  switch main
  merge branch3
  branch branch4
  commit id: "5-abcdefg"
  switch main
  merge branch4
  branch branch5
  commit id: "6-abcdefg"
  switch main
  merge branch5
  branch branch6
  commit id: "7-abcdefg"
  switch main
  merge branch6
  branch branch7
  commit id: "8-abcdefg"
  switch main
  merge branch7
  branch branch8
  commit id: "9-abcdefg"
  switch main
  merge branch8
  branch branch9
  commit id: "10-abcdefg"
