gitGraph BT:
  commit id: "ZERO"
  branch develop
  commit id:"A"
  checkout main
  commit id:"ONE"
  checkout develop
  commit id:"B"
  checkout main
  commit id:"TWO"
  cherry-pick id:"A"
  commit id:"THREE"
  checkout develop
  commit id:"C"
  checkout main
  cherry-pick id:"C"
  commit id:"FOUR"
