---
config:
  gitGraph:
    showBranches: true
    showCommitLabel: true
    rotateCommitLabel: false
    parallelCommits: false
---
gitGraph
  commit id: "Alpha"
  commit id: "Beta"
  branch develop
  checkout develop
  commit id: "Gamma"
  commit id: "Delta"
  checkout main
  commit id: "Epsilon"
