---
config:
  gitGraph:
    showBranches: true
    showCommitLabel: true
    rotateCommitLabel: false
    parallelCommits: true
---
gitGraph
  commit id: "1"
  commit id: "2"
  branch develop
  branch feature
  checkout develop
  commit id: "3"
  checkout feature
  commit id: "4"
  checkout main
  commit id: "5"
  checkout develop
  commit id: "6"
  checkout feature
  commit id: "7"
