---
config:
  gitGraph:
    showBranches: true
    showCommitLabel: true
    rotateCommitLabel: false
    parallelCommits: false
    mainBranchOrder: 2
---
gitGraph
  commit id: "1"
  branch feature1
  branch feature2
  checkout feature1
  commit id: "2"
  checkout feature2
  commit id: "3"
  checkout main
  commit id: "4"
