---
config:
  theme: redux-dark
  look: neo
  layout: elk
---
flowchart TB
  A[Start is the begining] --Get Going--> B(Continue Forward man)
  B --> C{Go Shopping}
  C -- One --> D[Option 1]
  C -- Two --> E[Option 2]
  C -- Three --> F[fa:fa-car Option 3]
