classDiagram
  Class01 <|-- AveryLongClass : Cool
  &lt;&lt;interface&gt;&gt; Class01
  Class01 : -privateMethod()
  Class01 : +publicMethod()
  Class01 : #protectedMethod()
  Class01 : -int privateChimp
  Class01 : +int publicGorilla
  Class01 : #int protectedMarmoset
