classDiagram
  class `This
  Title
  Has
  Many
  Newlines` {
  +String Also
  -String Many
  #int Members
  +And()
  -Many()
  #Methods()
  }
  &lt;&lt;Interface&gt;&gt; `This
  Title
  Has
  Many
  Newlines`
