classDiagram
  Animal <|-- `Du
  ck`
  Animal : +int age
  Animal : +String gender
  Animal: +isMammal()
  Animal: +mate()
  class `Du
  ck` {
  +String beakColor
  +String featherColor
  +swim()
  +quack()
  }
