/**
 * Constraint-based node overlap removal (guide §7.5), run immediately after
 * the initial core stress layout — invariant 4 — not as a late force pass.
 *
 * Constraint generation is the scanline procedure of Dwyer, Marriott & Stuckey,
 * *Fast Node Overlap Removal*: sweeping one axis while keeping the other axis
 * ordered gives, for every rectangle, only its immediate neighbours in the
 * scanline. Constraining just those pairs is enough to remove all overlaps and
 * keeps the constraint set linear rather than quadratic.
 *
 * The constraints that were actually violated at generation time are added to
 * the persistent system, so a later stage cannot re-introduce the overlap.
 */

import type { Axis, Bounds } from '../model.js';
import { rectsOverlap } from '../model.js';
import type { ConstraintSystem } from '../constraints/solver.js';
import type { SeparationConstraint } from '../constraints/types.js';
import { separation } from '../constraints/types.js';

export interface OverlapRect {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

interface SweepNode {
  rect: OverlapRect;
  /** Neighbours seen to the low side while this rectangle was open. */
  low: Set<SweepNode>;
  /** Neighbours seen to the high side while this rectangle was open. */
  high: Set<SweepNode>;
}

interface SweepEvent {
  position: number;
  isOpen: boolean;
  node: SweepNode;
}

function boundsOf(rect: OverlapRect): Bounds {
  return {
    minX: rect.x - rect.width / 2,
    minY: rect.y - rect.height / 2,
    maxX: rect.x + rect.width / 2,
    maxY: rect.y + rect.height / 2,
  };
}

export function findOverlappingPairs(rects: OverlapRect[], gap = 0): [string, string][] {
  const pairs: [string, string][] = [];
  const inflated = rects.map((r) => ({
    id: r.id,
    bounds: {
      minX: r.x - r.width / 2 - gap / 2,
      minY: r.y - r.height / 2 - gap / 2,
      maxX: r.x + r.width / 2 + gap / 2,
      maxY: r.y + r.height / 2 + gap / 2,
    },
  }));
  for (let i = 0; i < inflated.length; i++) {
    for (let j = i + 1; j < inflated.length; j++) {
      if (rectsOverlap(inflated[i].bounds, inflated[j].bounds)) {
        pairs.push([inflated[i].id, inflated[j].id]);
      }
    }
  }
  return pairs;
}

/**
 * Separation constraints on `axis`, generated by sweeping the perpendicular
 * axis. Only rectangles that are simultaneously open in the sweep — that is,
 * that overlap on the perpendicular axis — can constrain each other.
 */
export function generateSeparationConstraints(
  rects: OverlapRect[],
  axis: Axis,
  gap: number
): SeparationConstraint[] {
  if (rects.length < 2) {
    return [];
  }

  const centre = (r: OverlapRect): number => (axis === 'x' ? r.x : r.y);
  const extent = (r: OverlapRect): number => (axis === 'x' ? r.width : r.height);
  const sweepOpen = (r: OverlapRect): number => {
    const b = boundsOf(r);
    return axis === 'x' ? b.minY : b.minX;
  };
  const sweepClose = (r: OverlapRect): number => {
    const b = boundsOf(r);
    return axis === 'x' ? b.maxY : b.maxX;
  };

  const nodes = rects.map<SweepNode>((rect) => ({ rect, low: new Set(), high: new Set() }));

  const events: SweepEvent[] = [];
  for (const node of nodes) {
    events.push({ position: sweepOpen(node.rect), isOpen: true, node });
    events.push({ position: sweepClose(node.rect), isOpen: false, node });
  }
  events.sort((a, b) => {
    if (a.position !== b.position) {
      return a.position - b.position;
    }
    // Open before close at the same coordinate so touching rectangles still see
    // each other and get a separating constraint.
    if (a.isOpen !== b.isOpen) {
      return a.isOpen ? -1 : 1;
    }
    return compareScanline(a.node, b.node, centre);
  });

  // Scanline kept sorted by the constrained axis. A sorted array is exact and
  // fast enough for diagram-sized inputs.
  const scanline: SweepNode[] = [];
  const constraints: SeparationConstraint[] = [];

  const insert = (node: SweepNode): number => {
    let lo = 0;
    let hi = scanline.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (compareScanline(scanline[mid], node, centre) < 0) {
        lo = mid + 1;
      } else {
        hi = mid;
      }
    }
    scanline.splice(lo, 0, node);
    return lo;
  };

  for (const event of events) {
    const node = event.node;
    if (event.isOpen) {
      const at = insert(node);
      if (at > 0) {
        const left = scanline[at - 1];
        node.low.add(left);
        left.high.add(node);
      }
      if (at + 1 < scanline.length) {
        const right = scanline[at + 1];
        node.high.add(right);
        right.low.add(node);
      }
    } else {
      const at = scanline.indexOf(node);
      if (at >= 0) {
        scanline.splice(at, 1);
      }
      for (const other of node.low) {
        constraints.push(
          separation(
            axis,
            other.rect.id,
            node.rect.id,
            (extent(other.rect) + extent(node.rect)) / 2 + gap,
            'overlap-removal'
          )
        );
        other.high.delete(node);
      }
      for (const other of node.high) {
        constraints.push(
          separation(
            axis,
            node.rect.id,
            other.rect.id,
            (extent(node.rect) + extent(other.rect)) / 2 + gap,
            'overlap-removal'
          )
        );
        other.low.delete(node);
      }
      node.low.clear();
      node.high.clear();
    }
  }

  return constraints;
}

function compareScanline(a: SweepNode, b: SweepNode, centre: (r: OverlapRect) => number): number {
  const ca = centre(a.rect);
  const cb = centre(b.rect);
  if (ca !== cb) {
    return ca - cb;
  }
  return a.rect.id < b.rect.id ? -1 : a.rect.id > b.rect.id ? 1 : 0;
}

export interface OverlapRemovalResult {
  rounds: number;
  resolved: boolean;
  addedConstraints: number;
}

/**
 * Remove every node overlap by adding separation constraints and projecting.
 *
 * Each round picks the axis whose constraint set displaces the layout least,
 * which is what keeps the stress layout recognisable instead of smearing it
 * along one axis.
 */
export function removeOverlapsWithConstraints(
  rects: Map<string, OverlapRect>,
  positions: Map<string, { x: number; y: number }>,
  system: ConstraintSystem,
  gap: number,
  maxRounds: number
): OverlapRemovalResult {
  let added = 0;

  for (let round = 0; round < maxRounds; round++) {
    syncRects(rects, positions);
    const list = [...rects.values()];
    if (findOverlappingPairs(list, 0).length === 0) {
      return { rounds: round, resolved: true, addedConstraints: added };
    }

    const options: { axis: Axis; constraints: SeparationConstraint[]; cost: number }[] = [];
    for (const axis of ['x', 'y'] as Axis[]) {
      const generated = generateSeparationConstraints(list, axis, gap).filter((c) =>
        isViolated(c, positions)
      );
      if (generated.length === 0) {
        continue;
      }
      const before = clonePositions(positions);
      const outcome = system.project(positions, undefined, generated);
      const cost = outcome.feasible ? displacement(before, positions) : Number.POSITIVE_INFINITY;
      restore(positions, before);
      options.push({ axis, constraints: generated, cost });
    }

    const best = options.filter((o) => isFinite(o.cost)).sort((a, b) => a.cost - b.cost)[0];
    if (!best) {
      return { rounds: round + 1, resolved: false, addedConstraints: added };
    }

    if (!system.tryAdd(positions, best.constraints)) {
      return { rounds: round + 1, resolved: false, addedConstraints: added };
    }
    added += best.constraints.length;
  }

  syncRects(rects, positions);
  const resolved = findOverlappingPairs([...rects.values()], 0).length === 0;
  return { rounds: maxRounds, resolved, addedConstraints: added };
}

function isViolated(
  constraint: SeparationConstraint,
  positions: Map<string, { x: number; y: number }>
): boolean {
  const l = positions.get(constraint.leftOrAbove);
  const r = positions.get(constraint.rightOrBelow);
  if (!l || !r) {
    return false;
  }
  const delta = constraint.axis === 'x' ? r.x - l.x : r.y - l.y;
  return delta < constraint.gap - 1e-9;
}

function syncRects(
  rects: Map<string, OverlapRect>,
  positions: Map<string, { x: number; y: number }>
): void {
  for (const [id, rect] of rects) {
    const p = positions.get(id);
    if (p) {
      rect.x = p.x;
      rect.y = p.y;
    }
  }
}

function clonePositions(
  positions: Map<string, { x: number; y: number }>
): Map<string, { x: number; y: number }> {
  const copy = new Map<string, { x: number; y: number }>();
  for (const [id, p] of positions) {
    copy.set(id, { x: p.x, y: p.y });
  }
  return copy;
}

function restore(
  positions: Map<string, { x: number; y: number }>,
  snapshot: Map<string, { x: number; y: number }>
): void {
  for (const [id, p] of snapshot) {
    const target = positions.get(id);
    if (target) {
      target.x = p.x;
      target.y = p.y;
    }
  }
}

function displacement(
  before: Map<string, { x: number; y: number }>,
  after: Map<string, { x: number; y: number }>
): number {
  let total = 0;
  for (const [id, b] of before) {
    const a = after.get(id);
    if (!a) {
      continue;
    }
    total += (a.x - b.x) ** 2 + (a.y - b.y) ** 2;
  }
  return total;
}
