---
description: >-
  Two levels of composite-state nesting - PilotCockpit containing Parent,
  which contains leaf state C - tests deeply nested composite state
  rendering.
config:
  logLevel: 0
---
stateDiagram-v2
  state PilotCockpit {
    state  Parent {
      C
    }
  }
