---
description: >-
  The simplest possible state diagram - a single state (State1) with a
  start transition in and an end transition out ([*] --> State1 --> [*]) -
  baseline smoke test.
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2

  [*] --> State1
  State1 --> [*]
