---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram
  [*] --> NotShooting: Pacifist
  NotShooting --> A
  NotShooting --> B
  NotShooting --> C

  state NotShooting {
  [*] --> Idle: Yet another long long öong öong öong label
  Idle --> Configuring : EvConfig
  Configuring --> Idle : EvConfig  EvConfig EvConfig  EvConfig EvConfig
  }
