---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram
  [*]-->TV

  state TV {
  [*] --> Off: Off to start with
  On --> Off : Turn off
  Off --> On : Turn on
  }

  TV--> Console

  state Console {
  [*] --> Off2: Off to start with
  On2--> Off2 : Turn off
  Off2 --> On2 : Turn on
  On2-->Playing

  state Playing {
    Alive --> Dead
    Dead-->Alive
   }
  }
