---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram
  state "Long state description" as XState1
  state "Another Long state description" as XState2
  XState2 : New line
  XState1 --> XState2
