---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram
  State1: The state with a note
  note right of State1
  Important information! You
  can write
  notes with multiple lines...
  Here is another line...
  And another line...
  end note
