stateDiagram-v2

  state State1_____________
  {
  c0
  }

  state State2_____________
  {
  c1
  }

  state State3_____________
  {
  c7
  }

  state State4_____________
  {
  c2
  }

  state State5_____________
  {
  c3
  }

  state State6_____________
  {
  c4
  }

  state State7_____________
  {
  c5
  }

  state State8_____________
  {
  c6
  }

  state State9_____________
  {
  c9
  }

  state State10_____________
  {
  c10
  }

  [*] --> State1_____________
  State1_____________ --> State2_____________   : Transition1_____
  State2_____________ --> State3_____________   : Transition2_____
  State3_____________ --> State4_____________   : Transition3_____
  State4_____________ --> State5_____________   : Transition4_____
  State5_____________ --> State6_____________   : Transition5_____
  State6_____________ --> State7_____________   : Transition6_____
  State7_____________ --> State8_____________   : Transition7_____
  State8_____________ --> State9_____________   : Transition8_____
  State9_____________ --> State10_____________   : Transition9_____
