---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2
  AState: Should NOT be white
  BState
  classDef exampleStyleClass fill:#fff,color: blue;
  class AState,BState exampleStyleClass
  style AState fill:#636,border:1px solid red,color:white;
