---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2
  classDef notMoving fill:white
  classDef movement font-style:italic;
  classDef badBadEvent fill:#f00,color:white,font-weight:bold

  [*] --> Still
  Still --> [*]
  Still --> Moving
  Moving --> Still
  Moving --> Crash
  Crash --> [*]

  class Still notMoving
  class Moving, Crash movement
  class Crash badBadEvent
