---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2
  State1: The state with a note with minus - and plus + in it
  note left of State1
  Important information! You can write
  notes with . and  in them.
  end note
