---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2
  State1: The state with a note +,-
  note right of State1
  Important information! You can write +,-
  notes.
  end note
  State1 --> State2 : With +,-
  note left of State2 : This is the note +,-<br/>
