---
config:
  logLevel: 0
  fontFamily: courier
---
stateDiagram-v2
  State1: This a single line description
  State2: This a multi line description
  State2: here comes the multi part
  [*] --> State1
  State1 --> State2
  State2 --> [*]
