architecture-beta
  title Simple Architecture Diagram
  accTitle: Accessibility Title
  accDescr: Accessibility Description
  group api(cloud)[API]

  service db(database)[Database] in api
  service disk1(disk)[Storage] in api
  service disk2(disk)[Storage] in api
  service server(server)[Server] in api

  db:L -- R:server
  disk1:T -- B:server
  disk2:T -- B:db
