architecture-beta
  group tier1(cloud)[Tier 1]
  service a1(server)[A1] in tier1
  service a2(server)[A2] in tier1
  service a3(server)[A3] in tier1
  group tier2(database)[Tier 2]
  service b1(database)[B1] in tier2
  service b2(database)[B2] in tier2
  service b3(database)[B3] in tier2
  a1:B --> T:b1
  a2:B --> T:b2
  a3:B --> T:b3
  align row a1 a2 a3
  align row b1 b2 b3
  align column a1 b1
  align column a2 b2
  align column a3 b3
