architecture-beta
  service db(database)[Database]
  service s3(disk)[Storage]
  service serv1(server)[Server 1]
  service serv2(server)[Server 2]
  service disk(disk)[Disk]

  db:L -- R:s3
  serv1:L -- T:s3
  serv2:L -- B:s3
  serv1:T -- B:disk
