architecture-beta
  service src1(server)[Source 1]
  service src2(server)[Source 2]
  service src3(server)[Source 3]
  service proc(server)[Processor]
  src1:B --> T:proc
  src2:B --> T:proc
  src3:B --> T:proc
  align row src1 src2 src3
