architecture-beta
  service servC(server)[Server 1]
  service servL(server)[Server 2]
  service servR(server)[Server 3]
  service servT(server)[Server 4]
  service servB(server)[Server 5]

  servC:L --> R:servL
  servC:R --> L:servR
  servC:T --> B:servT
  servC:B --> T:servB

  servL:T --> L:servT
  servL:B --> L:servB
  servR:T --> R:servT
  servR:B --> R:servB
