architecture-beta
  service servC(server)[Server 1]
  service servL(server)[Server 2]
  service servR(server)[Server 3]
  service servT(server)[Server 4]
  service servB(server)[Server 5]

  servC:L -[Label]- R:servL
  servC:R -[Label]- L:servR
  servC:T -[Label]- B:servT
  servC:B -[Label]- T:servB

  servL:T -[Label]- L:servT
  servL:B -[Label]- L:servB
  servR:T -[Label]- R:servT
  servR:B -[Label]- R:servB
