usecase-beta
  direction LR

  actor Guest("Restaurant guest")
  systemBoundary "Professional Services":::service
    actor Chef("Chef")
    ReviewMeal("Review meal")
    PrepareMeal("Prepare meal")
  end
  Professional_Services@{ type: package }

  Chef --> PrepareMeal
  Chef --> ReviewMeal
  Guest --> ReviewMeal

  classDef service stroke:#b8860b,stroke-width:2px
