C4Context
title Relationship directions
System(a, "A")
System(b, "B")
System(c, "C")
System(d, "D")
System(e, "E")
Rel(a, b, "Rel (default)")
Rel_U(a, c, "Rel_U")
Rel_D(a, d, "Rel_D")
Rel_L(a, e, "Rel_L")
Rel_R(b, c, "Rel_R")
