---
config:
  theme: dark
  xyChart:
    width: 200
    height: 20
    xAxis:
      showLabel: false
      showTitle: false
      showTick: false
      showAxisLine: false
    yAxis:
      showLabel: false
      showTitle: false
      showTick: false
      showAxisLine: false
---
xychart
  bar [5000, 9000, 7500, 6200, 9500, 5500, 11000, 8200, 9200, 9500, 7000, 8800]
