---
config:
  xyChart:
    showDataLabel: true
    chartOrientation: horizontal
---
  xychart
  title "Multiple Bar Plots"
  x-axis Categories [A, B, C]
  y-axis "Values" 0 --> 100
  bar [10, 50, 90]
