== Audience
:icons: font

This document is written for the contributors. If you want to integrate ZenUML in your application,
you should read index.adoc; if you want to create themes, you should read create-my-own-theme.adoc.

== Build
This project is built with vue cli. It has two types of target: the web application and the library.

....
# to build the library
yarn build
# to build the web application
yarn build:site
....

=== Customize vue.config.js

==== Inline SVG
When we build the library, SVG must be inlined.

An inlined SVG looks like this:
....
<img src='data:image/svg+xml;base64,<svg ... > ... </svg>'>
....

[NOTE]
====
[TODO] Note that we use the `base64` encoding as it is the default behaviour of webpack 5
asset module `asset/inline`. However, `utf8` has https://www.npmjs.com/package/svg-url-loader[the following advantages]:

1. Resulting string is shorter (can be ~2 times shorter for 2K-sized icons);
2. Resulting string will be compressed better when using gzip compression;
3. Browser parses utf-8 encoded string faster than its base64 equivalent.

This can be implemented with https://webpack.js.org/guides/asset-modules/#custom-data-uri-generator[custom data URI generator].
====
The default loader build in vue cli service for svg files will not inline the SVG,
but give a url (relative path) to the svg resource like this:
....
<img src="/assets/arrow.svg">
....
Client applications will not be able to load the SVG properly.

To inline the SVG, we need to use https://webpack.js.org/guides/asset-modules/#inlining-assets[asset module `asset/inline`].


[source, javascript]
....
const svgRule = config.module.rule('svg')
svgRule.store.clear();
svgRule
    .test(/\.svg$/)  // required because of store.clear()
    .type('asset/inline')  // <1>
    .end()
....
<1> `asset/inline` exports a data URI of the asset. Previously achievable by using `url-loader`. https://webpack.js.org/guides/asset-modules/#inlining-assets[See more]

== Demo pages
In the public folder, there are some demo pages for testing the library.

=== How do they work?

The demo pages^1^ are built with vue cli service. On the page, there needs to be a `pre`
element with class `zenuml` and the content being the ZenUML DSL code.

For example:
[source, html]
....
<pre class="zenuml">
A.method
</pre>
....

The entry point of the demo pages is `src/main.ts`. It will find all the `pre` elements with
class `zenuml` and render the ZenUML DSL code in it.

== Parser

We use antlr4 to parse the ZenUML DSL code. The grammar files are:

1. Parser: `./src/g4/sequenceParser.g4`
2. Lexer: `./src/g4/sequenceLexer.g4`

=== How to generate the parser and lexer

Run `yarn antlr4` to generate the parser and lexer.

=== Setup local development environment

Run `yarn antlr:setup` (`python3 -m pip install antlr4-tools`) to install the antlr4 command and the runtime.

To test the setup, go to `src/g4-unit/hello-world` folder, and run:

1.

