export const NODE_SPACING = 100;

export const DEFAULT_LEVEL_SPACING = 120;

export const MIN_VERTICAL_PADDING = 90;

export const MIN_LEVEL_SPACING = 150;

export const MIN_HORIZONTAL_GAP = 90;

export const NEIGHBOR_STRESS_MAX_ITERATIONS = 50;

export const NEIGHBOR_STRESS_TOLERANCE = 1e-4;

export const TWEAK_ALIGNMENT_ALIGNMENT_THRESHOLD = 30;

export const MAX_EDGES_PER_SIDE = 5;

export const ALIGNMENT_EPSILON = 1e-2;

export const SELF_LOOP_CP_FACTOR = 1;

export const ORTHOGONAL_DEFAULT_CLEARANCE = 10;

export const SELF_LOOP_OFFSET_MULTIPLIER = 0.3;

export const SELF_LOOP_RADIUS_MULTIPLIER = 0.6;

export const ORTHOGONAL_EPSILON = 1e-6;

export const L_SHAPE_OFFSET_PERCENTAGES = [
  0, 50, -50, 40, -40, 60, -60, 30, -30, 70, -70, 20, -20, 10, -10,
];

export const Z_SHAPE_OFFSET_PERCENTAGES = [
  0, 10, -10, 20, -20, 30, -30, 40, -40, 50, -50, 60, -60, 70, -70, 80, -80,
];

export const ASTAR_DEFAULT_SEARCH_RADIUS = 48;

export const ASTAR_DEFAULT_ENDPOINT_CLEARANCE = 24;

export const ASTAR_DEFAULT_BEND_PENALTY = 10;

export const ASTAR_DEFAULT_CROSSING_PENALTY = 1000;

export const TREE_PLACEMENT_SCORE_EPSILON = 0.001;

export const TREE_PLACEMENT_MAX_ACCEPTABLE_STRESS = 5000;

export const TREE_PLACEMENT_STRESS_RELAX_DAMPING = 0.1;

export const TREE_PLACEMENT_STRESS_RELAX_CONVERGENCE = 0.01;

export const TREE_PLACEMENT_STRESS_RELAX_MAX_ITERATIONS = 20;

export const TREE_LAYOUT_MIN_WIDTH = 100;

export const TREE_NATURAL_GROWTH_ANGLE = 90;

export const TREE_DIRECTION_ANGLE_THRESHOLD = 45;

export const SAME_LAYER_VERTICAL_FORCE_RATIO = 0.3;

export const GROUP_SIBLING_SPACING = 80;

export const GROUP_SYMMETRY_THRESHOLD = 50;

export const GROUP_OVERLAP_MAX_ITERATIONS = 20;

export const DISCONNECTED_NODE_SPACING = 300;

export const GRADIENT_FACTOR = 2;

export const DEFAULT_NODE_WIDTH = 60;

export const DEFAULT_NODE_HEIGHT = 40;

export const DEFAULT_PADDING = 15;

export const STRESS_MINIMIZER_LEARNING_RATE = 0.1;

export const MINIMUM_EDGE_LENGTH = 50;

export const DEFAULT_TREE_PADDING = 100;

export const STRESS_MINIMIZATION_FACTOR = 0.1;

export const STRESS_MINIMIZATION_DAMPING_FACTOR = 0.05;

export const STRESS_MINIMIZATION_CONVERGENCE_THRESHOLD = 0.1;

export const EDGE_OBSTACLE_CROSSING_PENALTY = 200;
