usecase-beta
    direction RL
    %% Actors
    actor Customer
    Browse("Browse catalog")
    Checkout("Checkout")
    Receipt[Download receipt]

    %% Relationships
    Customer --> Browse
    Browse --> Checkout
    Checkout --> Receipt
