    flowchart TD
        Customer --> USCompany

        USCompany -- fdhdfjkfdkjdjd --> HongKongCompany
        USCompany -- & --> Expenses

        HongKongCompany  --> USCompany
        HongKongCompany --> ExpensesHK
        HongKongCompany --> Wages(HK)
        HongKongCompany --> Incomehk

