flowchart RL
  a1[I am a node with a super long label. I am a node with a super long label. I am a node with a super long label. I am a node with a super long label. I am a node with a super long label. ]
  a2[I am another node with a mega long label]
  a3[I am a node with a super long label]
  a4[I am another node with a mega long label]
  a1 & a2 & a3 & a4 -->  a5 & a6 & a7 & a8 & a9 & a10
