flowchart
        B{{"What am I going to do today?"}} --> n0("Train") & nl("Job") & nm("Go shopping") & n3("Sleep / chill at home")
        nl --> n4(["Productive! Progress in workprojects"])
        n4 --> no(["Go home earlier tomorrow"]) & nr(["Happy co-workers"])
        nr --> nh(["Better work enviroment"])
        no --> n6(["Spare time for hobbies"])
        n0 --> nj(["Build muscles"]) & nw(["Build up cardio"])
        nm --> n1(["Spend money"])
        n3 --> nb(["Rest and get energised"])
        nh --> ne["Happy life"]
        n6 --> ne
        nj --> ni(["Better physique"])
        nw --> ni
        ni --> ns(["Healthier body"])
        ns --> n2(["Higher life expectancy"])
        n2 --> ne
        n1 --> nq(["No money saved for the future"])
        nq --> n8(["No money for rent"])
        n8 --> nk(["Homeless"])
        nb --> nv(["Good for both mental and physical health"])
        nv --> np(["Can do a better job tomorrow"])
        np --> n5(["Risk for stress decreases"])
        n5 --> ne
