flowchart RL
    subgraph one
      a1[Iam a node with a super long label] -- I am a long label --> a2[I am another node with a mega long label]
      a1 -- Another long label --> a2
      a3 --> a1 & a2 & a3 & a4
      a1 --> a4
    end
