---
description: >-
  Vertical gitgraph with rotateCommitLabel: false, rendering four sequential
  commit labels horizontally - the vertical-orientation counterpart of the
  horizontal-labels test.
---
%%{init: { 'logLevel': 'debug', 'theme': 'default' , 'gitGraph': {
        'rotateCommitLabel': false
  } } }%%
gitGraph TB:
  commit id: "Alpha"
  commit id: "Beta"
  commit id: "Gamma"
  commit id: "Delta"
