---
description: >-
  Gitgraph where a merge commit (feature merged into main with a custom id)
  is itself cherry-picked onto a separate release branch, using the
  parent: clause to disambiguate which parent of the merge commit to
  cherry-pick from.
---
gitGraph
  commit id: "ZERO"
  branch feature
  branch release
  checkout feature
  commit id: "A"
  commit id: "B"
  checkout main
  merge feature id: "M"
  checkout release
  cherry-pick id: "M" parent:"B"
