---
description: >-
  Default-orientation gitgraph where a develop branch diverges from main
  and is never merged back, the default-orientation counterpart of the
  vertical two-branches-without-merge test.
---
gitGraph
  commit id: "1"
  commit id: "2"
  branch develop
  checkout develop
  commit id: "3"
  commit id: "4"
  checkout main
  commit id: "5"
  commit id: "6"
