---
description: >-
  BT gitGraph with a develop branch created from main: two commits on main, two on develop, then
  two more back on main, testing basic branch/checkout flow in vertical orientation.
---
gitGraph BT:
  commit id: "1"
  commit id: "2"
  branch develop
  checkout develop
  commit id: "3"
  commit id: "4"
  checkout main
  commit id: "5"
  commit id: "6"
