---
description: >-
  Regression test for issue #6593: BT gitGraph cherry-picking a commit from develop onto main with
  an explicit tag ('cherry-picked'), verifying cherry-pick rendering as part of this
  branch-ordering regression series.
---
gitGraph BT:
  commit id: "ZERO"
  branch develop
  commit id:"A"
  checkout main
  commit id:"ONE"
  checkout develop
  commit id:"B"
  checkout main
  commit id:"TWO"
  cherry-pick id:"A" tag: "cherry-picked"
  commit id:"THREE"
  checkout develop
  commit id:"C"
