---
description: >-
  Unicode characters and inline markdown emphasis/bold markers in the entity
  name, attribute types, and comments under the elk layout.
config:
  layout: elk
---
erDiagram
    _**testẽζ➕Ø😀㌕ぼ**_ {
        *__List~List~int~~sdfds__* **driversLicense** PK "***The l😀icense #***"
        *string(99)~T~~~~~~* firstName "Only __99__ <br>characters are a<br>llowed dsfsdfsdfsdfs"
        string last*Name*
        string __phone__ UK
        int _age_
    }
