---
description: >-
  Unicode characters and inline markdown emphasis/bold markers, with htmlLabels
  disabled.
config:
  htmlLabels: false
---
erDiagram
    _**testẽζ➕Ø😀㌕ぼ**_ {
        *__List~List~int~~sdfds__* **driversLicense** PK "***The l😀icense #***"
        *string(99)~T~~~~~~* firstName "Only __99__ <br>characters are a<br>llowed dsfsdfsdfsdfs"
        string last*Name*
        string __phone__ UK
        int _age_
    }
