---
description: >-
  An entity attribute block covering an array type (string[]) and a generic type
  (type~T~) under the elk layout.
config:
  layout: elk
---
erDiagram
    BOOK {
      string title
      string[] authors
      type~T~ type
    }
