---
description: >-
  Attribute names prefixed with an asterisk (*id) on two related entities under
  the elk layout.
config:
  layout: elk
---
erDiagram
    BOOK {
      int         *id
      string      name
      varchar(99) summary
    }
    BOOK }o..o{ STORE : soldBy
    STORE {
      int         *id
      string      name
      varchar(50) address
    }
