---
description: >-
  Two entities styled directly via a `style` statement, with htmlLabels
  disabled.
config:
  htmlLabels: false
---
erDiagram
      c[CUSTOMER]
      p[PERSON]
      style c,p fill:#f9f,stroke:blue, color:grey, font-size:24px,font-weight:bold
