import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumParser,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { MermaidGeneratedSharedModule, SankeyGeneratedModule } from '../generated/module.js';
import { SankeyTokenBuilder } from './tokenBuilder.js';
import { SankeyValueConverter } from './valueConverter.js';
import { createSankeyParser } from './parser.js';

/**
 * Declaration of `Sankey` services.
 */
export interface SankeyAddedServices {
  parser: {
    LangiumParser: LangiumParser;
    TokenBuilder: SankeyTokenBuilder;
    ValueConverter: SankeyValueConverter;
  };
}

/**
 * Union of Langium default services and `Sankey` services.
 */
export type SankeyServices = LangiumCoreServices & SankeyAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Sankey` services.
 */
export const SankeyModule: Module<
  SankeyServices,
  PartialLangiumCoreServices & SankeyAddedServices
> = {
  parser: {
    LangiumParser: (services) => createSankeyParser(services),
    TokenBuilder: (services) => new SankeyTokenBuilder(services),
    ValueConverter: () => new SankeyValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSankeyServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
  shared: LangiumSharedCoreServices;
  Sankey: SankeyServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Sankey: SankeyServices = inject(
    createDefaultCoreModule({ shared }),
    SankeyGeneratedModule,
    SankeyModule
  );
  shared.ServiceRegistry.register(Sankey);
  return { shared, Sankey };
}
