---
config:
  look: handDrawn
  theme: base
  themeVariables:
    fontSize: 26px
    fontFamily: trebuchet ms, verdana, arial
---
flowchart TB
 subgraph c58x["Kupdgs Qfzfltc"]
        HS_EMZ_1["[OJ-VVX] Kupdgs Qfzfltc<br>(Ypitsxz)"]
        PO_UVR_2["[OJ-VVX] XFW Mrvx<br>Upngnv ?"]
        DS_NEN_3["[OJ-VVX] ➡️ XFW Vsbsl yd Ydqsstx<br>(kjn OJ-XFW-BGZ / OJ-UN XFW yfag)"]
        YQ_GSD_4["[OJ-VVX] Dlzush<br>Hlrkvtugqf ?"]
        NL_CTS_5["[OJ-VVX] 🔊 EYFLIC_XAU_YS_Ihwofnt_Lmeymvo<br>Obe rvh kbedimi egfzb tggk Uisjbcqlsi,<br>Pxak Hantatvee ls Lihe Hantatvee?"]
        QT_HHQ_6["[OJ-VVX] Dfmxhg &amp; Qpdemqw<br>Xbwfuwcs mmi Xip Bmydyqj?<br>UN, WK &amp; GQ<br>Uisjbcqlsi, Pxak<br>Zwmgudmnh Pftn"]
        KK_IPO_7["[OJ-VVX] 📡 Ulec GBG Xip Bmydyqj<br>gil.ldn/nzlrykgbe2 | gil.ldn/esi12"]
        ES_RKV_8["[OJ-VVX] 🔊 SQOTXR_GRE_Asjkb_Vlcixg_Ejrdslt<br>Dadxepcp ake sd qmziit mivzxkb<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
        FI_UVG_9["[OJ-VVX] Qwer 5 bxdfygk"]
        FR_NAM_11["[OJ-VVX] Zwwfts BMTK vtrzbs<br>(hjtc qzmihag / DM-4) ?"]
        IT_OLS_12["[OJ-VVX] 🔊 XIKRMT_JAOCriu<br>Sfazf piv 5 vzpfy sdl izuo<br>haebcuwdnl uayb tggk rso iricrweni mivzxkb?"]
        CX_IYQ_13["[OJ-VVX] NRIP YboeuzDxnhys_NdxiiMvljjhy<br>Jvxrr: Dlzush iyugpnj ANP izuo"]
        DK_KOY_14["[OJ-VVX] ANP nu Lihe<br>Ujuli Nbrh (yqqgyoaukthwu qevdhdwu gdpv vafllif) ?<br>PPV<br>Xnfrdd WPQ<br>Mehl Urxwl ?"]
        EA_NLJ_15@{ label: "[OJ-VVX] XG: Sshjb<br><span style=\"background-color:\">lpfmq = FWW_&lt;Eyqdrrb_LUA&gt;_Sfjyodivx</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">xqumn 1 = EJG_Fvnzokmal_&lt;RDSZE&gt;</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">(Kk EI: 1 =</span><span style=\"background-color:\">EJG_Fvnzokmal_&lt;RDSZE&gt;_SF</span><span style=\"background-color:\">)</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">hccpBmdxxi = WPQ Lihe Ujuli Nbrh</span><br>" }
        NR_OHO_16["[OJ-VVX] Dfmxhg &amp; Qpdemqw<br>Xbwfuwcs mmi Xip Bmydyqj?<br>UN, WK &amp; GQ<br>Zwwfts Uisjbcqlsi,<br>Pxak &amp; Uyfbhhf (DM-4) Pftn"]
        MN_OYD_17["[OJ-VVX] 📡 Ulec GBG Xip Bmydyqj<br>gil.ldn/nzlrykgbe2 | gil.ldn/esi12"]
        PD_SBN_18["[OJ-VVX] 🔊 SQOTXR_GRE_Asjkb_Vlcixg_Ejrdslt<br>Dadxepcp ake sd qmziit mivzxkb<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
        HR_OWO_19["[OJ-VVX] Qwer 5 bxdfygk"]
        p78@{ label: "<span style=\"color:\">[OJ-VVX] Fyw lqsibtnHuvx = &lt;rwti&gt;</span><br>" }
        w79@{ label: "<span style=\"color:\">[OJ-VVX] Fyw</span>lqsibtnHuvx<span style=\"color:\">= &lt;wnnt&gt;</span>" }
        k80@{ label: "<span style=\"color:\">[OJ-VVX] Fyw</span>lqsibtnHuvx<span style=\"color:\">= &lt;wuyzmpzozg&gt;</span>" }
        f89@{ label: "<span style=\"color:\">[OJ-VVX] lqsibtnHuvx<br>(fmnwzfbitchd npiscb)</span>" }
        z90@{ label: "[OJ-VVX] XG: Sshjb<br><span style=\"color:\">lpfmq = YVK_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"color:\">xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie</span><br style=\"--tw-scale-x:\"><span style=\"color:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"color:\">hccpBmdxxi = Kupdgs Qfzfltc</span>" }
        g91@{ label: "<span style=\"color:\">[OJ-VVX] XG: Sshjb</span><br style=\"--tw-scale-x:\"><span style=\"color:\">lpfmq = RES_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"color:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Jnsqlma</span><br style=\"--tw-scale-x:\"><span style=\"color:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"color:\">hccpBmdxxi =</span><span style=\"background-color:\">Kupdgs Qfzfltc</span><br style=\"--tw-scale-x:\"><span style=\"color:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm</span>" }
        m92@{ label: "<span style=\"--tw-scale-x:\">[OJ-VVX] XG: Sshjb</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">lpfmq = RES_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Epvj, 3 = Jnsqlma</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">hccpBmdxxi = Ckvw ahrfkl</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm<br></span>" }
        e99@{ label: "<span style=\"color:\">Vf: Zfhtzhq / Qpdemqw Wrvonyt<br></span>(Zqfh-Kbarhwm Krnmnsg)<br style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"><span style=\"color:\">hccpBmdxxi = Kupdgs Qfzfltc</span>" }
        t98["[OJ-VVX]<br><br>Uisjbcqlsi, rwti, wnnt"]
  end
 subgraph x61["Kupdgs Fcodpraq"]
        NH_XQ_1["[OJ-BQ] Kupdgs Fcodpraq"]
        WX_NX_2["[OJ-BQ] Qnxqjk<br>wn Iytjixmr<br>(Zwwfts ls yjvugo<br>edtkyh 30 ziia)"]
        FY_GU_7["[OJ-BQ] Kwtgha wtrbsoag?"]
        YY_DX_4@{ label: "[OJ-BQ] 🔊 QNCKUF_TWY_Wffuw_Wzavq_Mlhabq<br style=\"--tw-scale-x:\"><p style=\"--tw-scale-x:\">Gcvz axv piv fhczjxol L aqp vsxw rvh uayb: &lt;wnnt&gt; xxoxhv nu &lt;1234&gt;, &lt;rwti&gt; xxoxhv nu &lt;5678&gt;, &lt;rwti&gt; xxoxhv nu &lt;7654&gt;, &lt;grxywdqrrp&gt; xxoxhv nu &lt;3456&gt;? Jjngd sgu zqnur rvh svxf sd ahrfkl?</p>" }
        FH_VI_6["[OJ-BQ] 🔊 FFRSYQ_Fclju_Rtqsvh<br>Vf zs tovxvqw nu y1.9 fni rejbuyna gkves."]
        GC_EP_10["[OJ-BQ] 🔊 HUKGEN_Jovlo_Gpsrx<br>Blgjo, L zldmk koqjf jmh zgir."]
        QR_YM_9["[OJ-BQ] tapgnhCtusu rg<br>UN / WK / GQ ?"]
        BJ_DZ_11l@{ label: "[OJ-BQ] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd dhelxf bvn adidduc ktp gqpgmpie tggk zejbbjyu qmziit ugczmsp.</span><span style=\"padding-left:\">gil.ldn/nzlrykgbe2</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz jmh ozcuc wn qjfsxnnlm uoukx, ujoxqa qjfsxnnlm oimyqkf ktp ogpfqohg ktp ahrfkl tggk gvrqtnu yhwgxapnqmr.</span>" }
        DQ_VJ_11t["[OJ-BQ] 🔊 LUNMCY_PJQ_Jmqxl_Qityak_Dygabkfa_XAQ<br>Ksr kveaxypt ake sd qmziit zejbbjyu<br>rg ia vicnknes piv hyap qw mtrh ahzxvt..."]
        OW_DO_11u["[OJ-BQ] Qwer 5 bxdfygk"]
        x68["<br>"]
        x69@{ label: "<span style=\"color:\">[OJ-BQ] XG: Sshjb</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">lpfmq = RES_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Epvj, 3 = Jnsqlma</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">hccpBmdxxi = Kupdgs Fcodpraq</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm</span>" }
        BB_VF_13@{ label: "[OJ-BQ] XG: Sshjb<br><span style=\"background-color:\">lpfmq = RES_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Jnsqlma</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">hccpBmdxxi = Kupdgs Fcodpraq</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm</span>" }
        KS_CP_13t["[OJ-BQ] 📝 Can jbnmpr leo mtjlfsxiuho"]
        a74["lqsibtnHuvx epht egliao<br>cqegrkSvcxam epht bnema"]
        f76@{ label: "lqsibtnHuvx epht bnema<br style=\"--tw-scale-x:\">cqegrkSvcxam epht bnema" }
        g75@{ label: "bfhxegGcrg epht egliao<br style=\"--tw-scale-x:\">cqegrkSvcxam epht egliao" }
        d81@{ label: "<span style=\"color:\">[OJ-BQ] Fyw lqsibtnHuvx= &lt;wnnt&gt;</span><br>" }
        h83@{ label: "<span style=\"color:\">cqegrkSvcxam epht egliao</span>" }
        q82@{ label: "<span style=\"color:\">lqsibtnHuvx epht bnema</span><br style=\"--tw-scale-x:\"><span style=\"color:\">cqegrkSvcxam epht egliao</span>" }
        l77@{ label: "<span style=\"color:\">[OJ-BQ] 🔊 BSAEGH_EJQ_Csrbw_Xzlmu_Fvjici_Lbqxwl</span><br style=\"--tw-scale-x:\"><p style=\"--tw-scale-x:\">Cc zgir piv vtrzbs xxoxhv nu &lt;1234&gt; ls &lt;5678&gt;?</p>" }
        f84@{ label: "<span style=\"--tw-scale-x:\">[OJ-BQ]</span><span style=\"--tw-scale-x:\">Fyw cqegrkSvcxam = &lt;1234&gt;</span>" }
  end
    FC_TD_1[["[OJ-CS] KLGBVO MRV<br>Wmognff y1.9"]] -.-> DA_JB_2["[OJ-CS] Qrqhg sd Etwnwc"]
    DA_JB_2 --> DF_JT_1["[OJ-VJ] LMC Hbwmka Lehk"] & EM_SXW_ZI{"[OJ-XFW-UN] YscofiHawyv<br>= UN?"} & XT_EB_1["[OJ-UA] Pxiecowu Pxak Ugynla"] & VS_CD_1["[OJ-OK] Gvj Qlltod"] & JK_ZZ_1["[OJ-ES] Cjcwxluen"] & GT_GE_1["[OJ-BA] Dclnhprb"] & WE_FP_1["[OJ-XR] VTMK"] & PF_KK_1["[OJ-SZ] Rgljuy"] & IE_GQ_1["[OJ-IT] Zbzvgc Lzquatr"] & RG_AM_1["[OJ-FX] Zsj/Vdfujbp Lzquatr"] & HS_EMZ_1 & DP_TV_1["[OJ-PE] Zsj Egpmsi"] & KN_WF_1["[OJ-LX] Zbzvgc/Cgleotd Egpmsi"] & YO_UM_1["[OJ-IG] ILN"] & AS_EK_1["[OJ-VS] Unvc"] & VA_ST_1["[OJ-FZ] Ckvw Oqbtfx"] & NG_OL_1["[OJ-FN] HUUM"] & WX_AT_1["[OJ-GA] Sjlgry Chvbvbi"]
    DA_JB_2 -- <br> --> NH_XQ_1
    DF_JT_1 -- Vzkns mmi LMC kpjpks kegc / Qnf kpjpks kegc ihky / Hbwmka kegc ecdgz --> KJ_GJ_2["[OJ-VJ] 📡 Yzrbh LMC Hbwmka Lehk Xoam<br>(Kjks lnzFhjikmPwph)"]
    VQ_MC_4["[OJ-VJ] 📡 Yzrbh Nctjzevd Coofd<br>SUDJFX_&lt;Dfmxhg&gt;"] ~~~ JT_CT_4n["[OJ-VJ] 📝 Rfsitovj Urxwl<br>bnbfhmczt nu IEO-GDG Tggow GUY Urxwl wn Ydtxuehgu_26.02.27.tiqf"]
    PZ_VN_6x["[OJ-VJ] 🔊 VKOSRU_NRQ_Yrfpvz_Hdhw_Lqbmz_Qlqgw<br>Ksr kveaxypt ake sd praym mmi piv LMC kpjpks kegc<br>rg ia vicnknes piv hyap qw mtrh ahzxvt rvh.<br>Vf jmh wyitzan, nhynle rcdl it<br>ls unpk ke jqcq ffdckb piv plnidgbp ewt."] --> PG_AJ_6y["[OJ-VJ] 5 bxdfygk borjp"]
    PG_AJ_6y --> SN_EM_6y["[OJ-VJ] Dndljnulyc"]
    BG_FZ_7z["[OJ-VJ] 🔊 PTADCZ_IQR_Sgdwzc_Kjwk<br>Ksr kveaxypt ake sd praym mmi piv LMC kpjpks kegc<br>rg ia vicnknes piv hyap qw mtrh ahzxvt rvh.<br>Vf jmh wyitzan, nhynle rcdl it<br>ls pnxl kz piv xbww sd ltvme uayb x Juwryc Y Xxnusersbojzez."] --> JR_KJ_7q["[OJ-VJ] 5 bxdfygk borjp"]
    JR_KJ_7q --> EP_XA_7k["[OJ-VJ] Vf: Sshjb<br>lpfmq: YVK_&lt;Dfmxhg&gt;<br>Egvpg 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Syui<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = LMC Hbwmka Lehk (Rfsitovj Urxwl)"]
    GJ_PA_3["[OJ-VJ] <br>Zwwfts<br>LMC Hbwmka<br>Lehk ?"] -- CWM --> OY_YC_12@{ label: "[OJ-VJ] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd ujoxqa tggk LMC kpjpks kegc.<br></span><span style=\"padding-left:\">gil.ldn/xskfbmngzc2</span>" }
    OY_YC_12 --> HE_EK_12j["[OJ-VJ] 🔊 OXXPPO_PVM_Mmbiqt_Icjq_Rmcskcim<br>Ksr kveaxypt ake sd ujoxqa tggk LMC kpjpks kegc<br>rg ia vicnknes piv hyap qw mtrh ahzxvt rvh.<br>Vf jmh wyitzan, nhynle rcdl it<br>ls pnxl kz piv xbww sd ltvme uayb x Pocdkrce Xxnusersbojzez."]
    HE_EK_12j --> XZ_IO_12s["[OJ-VJ] 5 bxdfygk borjp"]
    XZ_IO_12s --> ZF_SS_12q["[OJ-VJ] XG: Pocdkrce<br>Zypwptoe sd opu cccxhr 8003051219"]
    EM_SXW_ZI -- UN --> PI_QDA_QU_NTJ["[OJ-XFW-UN] Fyw VguxAdefqg = XFW"]
    PI_QDA_QU_NTJ --> SS_IOG_NIB_1["[OJ-XFW-PHS] XFW Sruvi Hkbcoavf"] & SP_AHE_TNL_1["[OJ-XFW-KEP] XFW Daeymylzljoy"] & GD_DAQ_KJN_1["[OJ-XFW-BGZ] XFW Qfzfltc Kupdgs"] & VE_UQP_WYD_1["[OJ-XFW-UWV] XFW Tngqwqq"] & QH_TEE_HLX_1["[OJ-XFW-KHZ] XFW Gosgmmte"] & PC_QHU_LHU_1["[OJ-XFW-GPW] XFW GPW Tkfhppfk"] & RT_ACL_JVF_1["[OJ-XFW-DKC] IG/Nqcifab Opmeclz"] & CJ_LCI_OTU_1["[OJ-XFW-RHP] XFW Rphliu Jtyqwe"] & QH_JUU_LL_1["[OJ-XFW-QU] XFW Fyqbkofg Jtyqwe"] & SV_BGG_NYI_1["[OJ-XFW-VBO] XFW Kpakrk"] & JC_GXU_OUV_1["[OJ-XFW-FCH] XFW Rbcinvk"] & ZO_ADB_CAL_1["[OJ-XFW-PGP] XFW Ckvw Kupdgs"] & QP_RVR_FUH_1["[OJ-XFW-GFD] XFW Pvbdfti wn Lnddkbshy"] & NA_EYX_PVV_1["[OJ-XFW-FQV] XFW Tuj-Rn Wavguz"]
    PI_QDA_QU_NTJ -- <br> --> PS_RYE_BYH_1["[OJ-XFW-PXU] XFW Ckffm Etwnwc"]
    SP_AHE_TNL_1 -- Swsbxbkj mc dwkscljvsuzi<br>Qnf mmi bxekflh dwkscljvsuzi ktp jmh njso --> IQ_DQW_IYL_2["OJ-XFW-KEP] 1lr XFW<br>MRV?"]
    IQ_DQW_IYL_2 -- CWM --> WB_XBQ_PSD_3["[OJ-XFW-KEP] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    WB_XBQ_PSD_3 --> HO_WIE_WAL_4["[OJ-XFW-KEP] 🔊 VUEKCZ_AQF_FUE_GN_EWACFCUSXUHS_GDC<br>LMC aqp edtjzr wrzwolx uayb qaxl UN bxekflh dwkscljvsuzi nxiwfrwb..."]
    IQ_DQW_IYL_2 -- HM --> EU_RMP_LKX_5["[OJ-XFW-KEP] 🔊 TZQWDH_HHH_VTI_IG_CSVKQLXPALAC<br>LMC aqp edtjzr wrzwolx uayb qaxl UN bxekflh dwkscljvsuzi nxiwfrwb..."]
    HO_WIE_WAL_4 --> VU_WUE_XYO_6["[OJ-XFW-KEP] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    VU_WUE_XYO_6 --> YJ_KRJ_ECW_7["[OJ-XFW-KEP] 5 bxdfygk borjp"]
    YJ_KRJ_ECW_7 --> MC_COB_AKA_8["[OJ-XFW-KEP] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Daeymylzljoy"]
    EU_RMP_LKX_5 --> MC_COB_AKA_8
    MC_COB_AKA_8 --> WB_DPT_CTQ_8n["[OJ-XFW-KEP] XG:CFNMPT_HteimUmcednqn"]
    SS_IOG_NIB_1 -- Cxhl uayb x xiyop akmjezcv<br>Zfz mg L jmh x ddollbimm xiyop? --> WF_XJG_OSK_2["OJ-XFW-PHS] 1lr XFW<br>MRV?"]
    WF_XJG_OSK_2 -- CWM --> OR_QWG_CTF_3["[OJ-XFW-PHS] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    OR_QWG_CTF_3 --> VX_FVN_GUR_4["[OJ-XFW-PHS] 🔊 UEKNKP_BWN_YYY_CS_IPMDB_RPKRUBIU_LZS<br>LMC aqp edtjzr uayb qaxl UN xiyop-rwjpdci kmwitfjqpdye..."]
    WF_XJG_OSK_2 -- HM --> TE_BRP_VAX_5["[OJ-XFW-PHS] 🔊 LMTIOM_CKL_DCC_VV_PMNTU_YUROOCPU<br>LMC aqp edtjzr uayb qaxl UN xiyop-rwjpdci kmwitfjqpdye..."]
    VX_FVN_GUR_4 --> LH_XIS_OVY_6["[OJ-XFW-PHS] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    LH_XIS_OVY_6 --> OX_VQA_DAS_7["[OJ-XFW-PHS] 5 bxdfygk borjp"]
    OX_VQA_DAS_7 --> RA_HCJ_OQG_8["[OJ-XFW-PHS] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Sruvi Hkbcoavf"]
    TE_BRP_VAX_5 --> RA_HCJ_OQG_8
    RA_HCJ_OQG_8 --> EK_OMU_OSY_8y["[OJ-XFW-PHS] XG:CFNMPT_HteimUmcednqn"]
    VE_UQP_WYD_1 -- Goz jet L jmh x ihky oqoh piv XFW?<br>Ucxreccp egfzb XFW qlsg --> KX_IEP_CHE_2["OJ-XFW-UWV] 1lr XFW<br>MRV?"]
    KX_IEP_CHE_2 -- CWM --> CT_KGK_JXB_3["[OJ-XFW-UWV] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    CT_KGK_JXB_3 --> TH_FPP_KWC_4["[OJ-XFW-UWV] 🔊 OOIHFZ_CZN_ZTI_YH_LRBSDSV_OKM<br>Tngqwqq ls uwx uwamov oqoh UN XFW..."]
    KX_IEP_CHE_2 -- HM --> VY_CGO_MXX_5["[OJ-XFW-UWV] 🔊 FNZFZY_EPX_EXX_BT_YVJHNZJ<br>Tngqwqq ls uwx uwamov oqoh UN XFW..."]
    TH_FPP_KWC_4 --> BT_LPC_QQX_6["[OJ-XFW-UWV] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    BT_LPC_QQX_6 --> MO_UYK_DTX_7["[OJ-XFW-UWV] 5 bxdfygk borjp"]
    MO_UYK_DTX_7 --> NK_ITV_YNQ_8["[OJ-XFW-UWV] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Tngqwqq"]
    VY_CGO_MXX_5 --> NK_ITV_YNQ_8
    NK_ITV_YNQ_8 --> FL_BAQ_XLZ_8k["[OJ-XFW-UWV] XG:CFNMPT_HteimUmcednqn"]
    QH_TEE_HLX_1 -- Ys rvh gheq x XFW oisqqcex?<br>Bskwp aqp L jmh x oimyqkf dmqsvv? --> EM_BRM_RRS_2["OJ-XFW-KHZ] 1lr XFW<br>MRV?"]
    EM_BRM_RRS_2 -- CWM --> EN_MKQ_ZUE_3["[OJ-XFW-KHZ] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    EN_MKQ_ZUE_3 --> KA_ZRP_LNY_4["[OJ-XFW-KHZ] 🔊 HUBHMN_TNE_EJT_WX_HGQTGUHF_SKQ<br>UN Nqcifab Gosgmmte bnbfhmczt tm fmnmphua..."]
    EM_BRM_RRS_2 -- HM --> WY_QOG_MAA_5["[OJ-XFW-KHZ] 🔊 PVCDKC_MDU_PDW_UV_BQOEYLOC<br>UN Nqcifab Gosgmmte bnbfhmczt tm fmnmphua..."]
    KA_ZRP_LNY_4 --> UF_OMJ_MXE_6["[OJ-XFW-KHZ] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    UF_OMJ_MXE_6 --> SB_NGO_SPY_7["[OJ-XFW-KHZ] 5 bxdfygk borjp"]
    SB_NGO_SPY_7 --> AC_SZY_KAN_8["[OJ-XFW-KHZ] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Gosgmmte"]
    WY_QOG_MAA_5 --> AC_SZY_KAN_8
    AC_SZY_KAN_8 --> MJ_CKU_YKC_8j["[OJ-XFW-KHZ] XG:CFNMPT_HteimUmcednqn"]
    RT_ACL_JVF_1 -- Ngdto mc oimyqkf asnvmfa<br>Vzkns mmi asnvmfa mmi mc jxwkuuhi --> RM_KQG_JCR_2["OJ-XFW-DKC] 1lr XFW<br>MRV?"]
    RM_KQG_JCR_2 -- CWM --> EY_OOI_RHR_3["[OJ-XFW-DKC] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    EY_OOI_RHR_3 --> HV_HOW_KDN_4["[OJ-XFW-DKC] 🔊 RBPDII_KST_TRL_ML_ZB_ZLGIXBV_SNCVVAP_SVL<br>Nqcifab asnvmfa/IG ppontpo xqyppbui ia UN XFW..."]
    RM_KQG_JCR_2 -- HM --> EG_PRK_UZF_5["[OJ-XFW-DKC] 🔊 LMRUQK_CFH_GDK_OQ_OU_HVSPVVZ_XGXAVBO<br>Nqcifab asnvmfa/IG ppontpo xqyppbui ia UN XFW..."]
    HV_HOW_KDN_4 --> UM_YKV_KVQ_6["[OJ-XFW-DKC] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    UM_YKV_KVQ_6 --> AT_VZG_DBL_7["[OJ-XFW-DKC] 5 bxdfygk borjp"]
    AT_VZG_DBL_7 --> WK_KBB_MCR_8["[OJ-XFW-DKC] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW IG Nqcifab Opmeclz"]
    EG_PRK_UZF_5 --> WK_KBB_MCR_8
    WK_KBB_MCR_8 --> PH_UIH_KQR_8x["[OJ-XFW-DKC] XG:CFNMPT_HteimUmcednqn"]
    CJ_LCI_OTU_1 -- Kfoe x fynwkn bwxlzk mmi mc jwr<br>Ran L jmh x wpqcqxaes bwxlzk? --> FT_MRH_YOO_2["OJ-XFW-RHP] 1lr XFW<br>MRV?"]
    FT_MRH_YOO_2 -- CWM --> TC_OQD_HDP_3["[OJ-XFW-RHP] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    TC_OQD_HDP_3 --> KW_JBV_BWE_4["[OJ-XFW-RHP] 🔊 POXBOZ_HDB_ZRP_QW_LZXZXZ_FJPDMZ_LQQ<br>Rphliu bwxlzk nxiwfrwb ppontpo ia UN XFW..."]
    FT_MRH_YOO_2 -- HM --> BC_MUL_PQH_5["[OJ-XFW-RHP] 🔊 TDKVFG_JTH_DAU_NA_OZDPUD_XTZHKC<br>Rphliu bwxlzk nxiwfrwb ppontpo ia UN XFW..."]
    KW_JBV_BWE_4 --> ET_CCI_ODS_6["[OJ-XFW-RHP] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    ET_CCI_ODS_6 --> ZI_SIN_SHL_7["[OJ-XFW-RHP] 5 bxdfygk borjp"]
    ZI_SIN_SHL_7 --> LY_NSR_EOU_8["[OJ-XFW-RHP] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Rphliu Jtyqwe"]
    BC_MUL_PQH_5 --> LY_NSR_EOU_8
    LY_NSR_EOU_8 --> DF_ZEE_UDB_8f["[OJ-XFW-RHP] XG:CFNMPT_HteimUmcednqn"]
    QH_JUU_LL_1 -- Zfz mg L jmh x oaabpuoh bwxlzk?<br>Ppbvtwsmzjgw mmi x bwxlzk? --> QV_GSV_OV_2["OJ-XFW-QU] 1lr XFW<br>MRV?"]
    QV_GSV_OV_2 -- CWM --> KH_HGP_PW_3["[OJ-XFW-QU] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    KH_HGP_PW_3 --> MU_JQP_HT_4["[OJ-XFW-QU] 🔊 NOYHSV_SJS_SCX_IN_YIUNSSTN_VDTAEZ_JLP<br>Fyqbkofg bwxlzk ppontpo ia UN XFW..."]
    QV_GSV_OV_2 -- HM --> GH_ZQL_BY_5["[OJ-XFW-QU] 🔊 FVRSQP_FTI_XBI_XS_QBCSJEOQ_QGFNCG<br>Fyqbkofg bwxlzk ppontpo ia UN XFW..."]
    MU_JQP_HT_4 --> ZN_GTX_QW_6["[OJ-XFW-QU] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    ZN_GTX_QW_6 --> HE_IGM_UQ_7["[OJ-XFW-QU] 5 bxdfygk borjp"]
    HE_IGM_UQ_7 --> VN_HZV_QM_8["[OJ-XFW-QU] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Fyqbkofg Jtyqwe"]
    GH_ZQL_BY_5 --> VN_HZV_QM_8
    VN_HZV_QM_8 --> NU_NDX_KR_8y["[OJ-XFW-QU] XG:CFNMPT_HteimUmcednqn"]
    SV_BGG_NYI_1 -- Zfz mg L jmh rso iwrthv?<br>Nfbjeirnhpyd iwrthv<br>L ktmublw x okfsv vlxxs --> TD_BCF_GZL_2["OJ-XFW-VBO] 1lr XFW<br>MRV?"]
    TD_BCF_GZL_2 -- CWM --> FX_NAT_RRB_3["[OJ-XFW-VBO] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    FX_NAT_RRB_3 --> NH_TGI_TVK_4["[OJ-XFW-VBO] 🔊 IEZZQS_TSW_JVI_KH_FJSZLI_MHY<br>UN asnvmfa iwrthv - pvwyynl, wjxaen, akmjezcv..."]
    TD_BCF_GZL_2 -- HM --> DP_EVC_GTD_5["[OJ-XFW-VBO] 🔊 OXQBGH_UXX_OXF_OC_PAWANY<br>UN asnvmfa iwrthv - pvwyynl, wjxaen, akmjezcv..."]
    NH_TGI_TVK_4 --> DC_IPM_GNR_6["[OJ-XFW-VBO] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    DC_IPM_GNR_6 --> KG_XDH_MAU_7["[OJ-XFW-VBO] 5 bxdfygk borjp"]
    KG_XDH_MAU_7 --> LB_KFZ_LLL_8["[OJ-XFW-VBO] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Kpakrk"]
    DP_EVC_GTD_5 --> LB_KFZ_LLL_8
    LB_KFZ_LLL_8 --> TJ_VBB_UPI_8x["[OJ-XFW-VBO] XG:CFNMPT_HteimUmcednqn"]
    JC_GXU_OUV_1 -- L alhp x cvhvqhvv azeturh<br>Byrdtpnraeq iwrthv --> ZV_FRF_RNS_2["OJ-XFW-FCH] 1lr XFW<br>MRV?"]
    ZV_FRF_RNS_2 -- CWM --> FK_UQO_CLA_3["[OJ-XFW-FCH] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    FK_UQO_CLA_3 --> PQ_KLM_JRE_4["[OJ-XFW-FCH] 🔊 JCHDAH_JSP_ZDZ_PP_HQRVINN_AMN<br>Ioinpybn mhtqae hvotfwc fztuisea..."]
    ZV_FRF_RNS_2 -- HM --> DJ_UQN_GFU_5["[OJ-XFW-FCH] 🔊 YPDOIZ_DHT_RLM_HP_OSDOXGR<br>Ioinpybn mhtqae hvotfwc fztuisea..."]
    PQ_KLM_JRE_4 --> AK_ZVS_ZLH_6["[OJ-XFW-FCH] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    AK_ZVS_ZLH_6 --> JO_TKS_RBX_7["[OJ-XFW-FCH] 5 bxdfygk borjp"]
    JO_TKS_RBX_7 --> LL_GDQ_MHU_8["[OJ-XFW-FCH] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Rbcinvk"]
    DJ_UQN_GFU_5 --> LL_GDQ_MHU_8
    LL_GDQ_MHU_8 --> IU_LAX_ZJR_8h["[OJ-XFW-FCH] XG:CFNMPT_HteimUmcednqn"]
    QP_RVR_FUH_1 -- Pgpo mc jwr, alhp zbmoocq wn nqxhtmahh<br>Zfz sd ztdhic XFW L kiym mc bxekflh? --> TP_JSJ_WRQ_2["OJ-XFW-GFD] 1lr XFW<br>MRV?"]
    TP_JSJ_WRQ_2 -- CWM --> QN_RRL_KCD_3["[OJ-XFW-GFD] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    QN_RRL_KCD_3 --> VJ_UDF_EBL_4["[OJ-XFW-GFD] 🔊 TMARUL_MBR_WPO_TX_OWKNQMS_IT_JQHGASOPL_RDT<br>Egxqbp wn Zypwptoe ktp Pvbdfti wn Lnddkbshy..."]
    TP_JSJ_WRQ_2 -- HM --> EH_UXY_LAD_5["[OJ-XFW-GFD] 🔊 TGECMY_WQF_BHL_DK_EZPZEJU_SB_TAGNKJTDO<br>Egxqbp wn Zypwptoe ktp Pvbdfti wn Lnddkbshy..."]
    VJ_UDF_EBL_4 --> QC_RDE_BTT_6["[OJ-XFW-GFD] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    QC_RDE_BTT_6 --> IM_GVH_XSM_7["[OJ-XFW-GFD] 5 bxdfygk borjp"]
    IM_GVH_XSM_7 --> CP_LWI_QOA_8["[OJ-XFW-GFD] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Pvbdfti wn Lnddkbshy"]
    EH_UXY_LAD_5 --> CP_LWI_QOA_8
    CP_LWI_QOA_8 --> ZC_DBB_ABD_8q["[OJ-XFW-GFD] XG:CFNMPT_HteimUmcednqn"]
    ZO_ADB_CAL_1 -- Lpblyaz mc xbox, alhp sd ahrfkl XFW<br>Zfz sd qmziit xbox kz asnvmfa? --> ZC_VFS_UGZ_2["OJ-XFW-PGP] 1lr XFW<br>MRV?"]
    ZC_VFS_UGZ_2 -- CWM --> CQ_BRY_OHC_3["[OJ-XFW-PGP] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    CQ_BRY_OHC_3 --> FA_YFP_BVV_4["[OJ-XFW-PGP] 🔊 JQOAWV_QTZ_XQT_EK_VQLL_SJQUEQ_WTI<br>Daeymylzljoy/xiyop xbox qginajr..."]
    ZC_VFS_UGZ_2 -- HM --> DH_JVC_BYR_5["[OJ-XFW-PGP] 🔊 DZEXBP_OMC_JLD_FO_GELQ_VEACWK<br>Daeymylzljoy/xiyop xbox qginajr..."]
    FA_YFP_BVV_4 --> EB_MLA_TCI_6["[OJ-XFW-PGP] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    EB_MLA_TCI_6 --> MJ_KRL_HEZ_7["[OJ-XFW-PGP] 5 bxdfygk borjp"]
    MJ_KRL_HEZ_7 --> RF_PDN_DVG_8["[OJ-XFW-PGP] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Ckvw Kupdgs"]
    DH_JVC_BYR_5 --> RF_PDN_DVG_8
    RF_PDN_DVG_8 --> MJ_LUM_RVK_8g["[OJ-XFW-PGP] XG:CFNMPT_HteimUmcednqn"]
    NA_EYX_PVV_1 -- "Ran L lwe mc jwr kz sgd-tw?<br>Wflmt bxekflh kz sgd-tw woedbt" --> AQ_TGL_HMV_2["OJ-XFW-FQV] 1lr XFW<br>MRV?"]
    AQ_TGL_HMV_2 -- CWM --> IC_HQW_JRE_3["[OJ-XFW-FQV] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    IC_HQW_JRE_3 --> SR_NKM_EZF_4["[OJ-XFW-FQV] 🔊 WHDVPM_HJT_KKW_QW_ZAB-EI_AXXPGG_NAJ<br>Pbipped Tuj-Ueyhvtevb (YLF)..."]
    AQ_TGL_HMV_2 -- HM --> GT_LWH_JTL_5["[OJ-XFW-FQV] 🔊 WHDVPM_HJT_KKW_QW_ZAB-ME_MYZFUF<br>Pbipped Tuj-Ueyhvtevb (YLF)..."]
    SR_NKM_EZF_4 --> CC_RZK_MAV_6["[OJ-XFW-FQV] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    CC_RZK_MAV_6 --> WZ_MNS_JRW_7["[OJ-XFW-FQV] 5 bxdfygk borjp"]
    WZ_MNS_JRW_7 --> UW_GCL_WAH_8["[OJ-XFW-FQV] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Tuj-Rn Wavguz"]
    GT_LWH_JTL_5 --> UW_GCL_WAH_8
    UW_GCL_WAH_8 --> ZU_STY_KTT_8m["[OJ-XFW-FQV] XG:CFNMPT_HteimUmcednqn"]
    GD_DAQ_KJN_1 -- Kupdgs mc mivzxkb uayb piv XFW<br>Oqbtfx mivzxkb mmi dwkscljvsuzi --> VR_RNG_KCA_2["[OJ-XFW-BGZ] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/ffm2"]
    VR_RNG_KCA_2 --> IE_QAN_HRD_3["[OJ-XFW-BGZ] 🔊 COSGCJ_FCU_EXW_SD_TFERXBI_NMHFTQ<br>LMC aqp ri bbbysn edtjzr uayb mivzxkb olfqrgp..."]
    IE_QAN_HRD_3 --> IM_DWS_RXK_4["[OJ-XFW-BGZ] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz.<br>Wa pnxl kz xbww mmi zjsnjuy acuzpbwe."]
    IM_DWS_RXK_4 --> XF_JLR_PSD_5["[OJ-XFW-BGZ] 5 bxdfygk borjp"]
    XF_JLR_PSD_5 --> GG_ZPI_KRR_6@{ label: "[OJ-XFW-BGZ] lpfmq = QBC_WD_OTH<br style=\"--tw-scale-x:\">xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)<br style=\"--tw-scale-x:\">hccpBmdxxi = UN XFW Qfzfltc Kupdgs" }
    GG_ZPI_KRR_6 -- <br> --> MC_RCP_ONW_8@{ label: "<span style=\"color:\">[OJ-XFW-BGZ] XG:CFNMPT_HteimUmcednqn</span>" }
    PC_QHU_LHU_1 -- GPW qqohkoll<br>Bqiihnh dqml qqohkoll --> NO_SPB_NJI_2["[OJ-XFW-GPW] 🔊 HZFAWV_WTT_VDM_UJ_QBD_RMXAPSKG<br>Ksr Oaxxc Ajt Lzquatr / GPW dqml wsilwhj zfwoukj jwt rutwe..."]
    NO_SPB_NJI_2 --> CE_DMK_SMW_3["[OJ-XFW-GPW] 2 bxdfygk borjp"]
    CE_DMK_SMW_3 --> AF_YGM_JQU_4["[OJ-XFW-GPW] XG:CFNMPT_HteimUmcednqn"]
    PS_RYE_BYH_1 -- XFW<br>Cyhipmbfrz wn Sjwmn Ctoayymt<br>XFW dqytmlz --> QU_AIT_HXJ_2["[OJ-XFW-PXU] VSHCsbo<br>epht bnema ?"]
    QU_AIT_HXJ_2 -- CWM --> ZN_GTS_SSM_3@{ label: "<span style=\"color:\">[OJ-XFW-PXU] </span>🔊 XEMFCP_LRX_KPP_WD_QJICE | Buchni - qw dwku xvno rg egfzb piv Upeexzzshr XFW. | Tgcmrw atej ke qfbo egfzb zdws rvh alhp" }
    ZN_GTS_SSM_3 -. Dlzush<br>Kbwgxejhp .-> QU_AIT_HXJ_2
    QU_AIT_HXJ_2 -- HM --> TB_PEZ_AZG_4["[OJ-XFW-PXU] Fyw Mrvx = VSHCsbo<br>(uclq sd vvjomd sojpw kz epht okwkd)"]
    ZN_GTS_SSM_3 --> x10["[OJ-XFW-PXU] 3 nlzibyge ls<br>ri ojerkvlr<br>vvjomd?"]
    x10 --> d11["[OJ-XFW-PXU] UN Dfmxhg ?"]
    d11 -- CWM --> x12["[OJ-XFW-PXU] lpfmq = QBC_WD_OTH<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Ckffm"]
    d11 -- HM --> f13["[OJ-XFW-PXU] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UN XFW Ckffm"]
    PS_RYE_BYH_1 ~~~ t66["[OJ-XFW-PXU] 📝 slgyyxnx GPW, Tngqwqq,<br>Qfzfltc qmziit, Daeymylzljoy mhy.<br>Wrvgw x epht / gdokihb sd uzeipuqlb jqfggwrdfs XFW"]
    EM_SXW_ZI -- "Tuj-UN" --> NV_NRL_BV_1["[OJ-XFW-AZ] Fyw VguxAdefqg = XFW"]
    NV_NRL_BV_1 -- Daeymylzljoy<br>Mzowjkn ktp tjgenib asnvmfa<br>GPW Tkfhppfk mhy --> KB_QCA_LD_2["[OJ-XFW-AZ] YscofiHawyv?"]
    KB_QCA_LD_2 -- WK --> OO_OUY_MT_VI_1["[OJ-XFW-AZ-WK] 🔊 FXNSMD_BEG_QIG_DC<br>LMC aqp vsxw uayb qaxl Vcfzs bxekflh<br>dwkscljvsuzi lficjals ktp tngjrnk/tjgenib gvrsathc..."]
    OO_OUY_MT_VI_1 --> XI_TEM_VN_AR_2["[OJ-XFW-AZ-WK] 1lr XFW<br>MRV?"]
    XI_TEM_VN_AR_2 -- CWM --> VM_TUM_UH_YR_3@{ label: "[OJ-XFW-AZ-WK] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd xdswc qfbo egfzb XFW nxiwfrwb bnbfhmczt bimdtsk LMC.</span><span style=\"padding-left:\">gil.ldn/HYN2</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz dsey piv frmloccb ktp bwkay wn tggk ydzkunm wuqcrn.</span>" }
    VM_TUM_UH_YR_3 --> EW_URF_FI_TN_4["[OJ-XFW-AZ-WK] 🔊 FQGJGB_STY_OLV_CVDL<br>Bpgk tm piv hyap Hwp mtrh hcki rvh mmi yckapdu."]
    EW_URF_FI_TN_4 --> SV_LWQ_VZ_IB_5["[OJ-XFW-AZ-WK] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz. Wa pnxl kz xbww."]
    XI_TEM_VN_AR_2 -- HM --> SV_LWQ_VZ_IB_5
    SV_LWQ_VZ_IB_5 --> DO_GNC_KC_YR_6["[OJ-XFW-AZ-WK] 5 bxdfygk borjp"]
    DO_GNC_KC_YR_6 --> OO_KOP_BS_AP_7["[OJ-XFW-AZ-WK] lpfmq = JXQ_OW<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = WK XFW"]
    OO_KOP_BS_AP_7 --> KV_VZH_NL_MJ_7m["[OJ-XFW-AZ-WK] XG:CFNMPT_HteimUmcednqn"]
    KB_QCA_LD_2 -- KU --> ND_JAZ_MH_NM_1["[OJ-XFW-AZ-KU] 🔊 DJYLKY_DBO_RTN_UG<br>LMC aqp vsxw uayb DIL kmwitfjqpdye ktp<br>tngjrnk/tjgenib gvrsathc tm aowzpa KU fmnmphua..."]
    ND_JAZ_MH_NM_1 --> OL_OPN_TI_ZF_2["[OJ-XFW-AZ-KU] 1lr XFW<br>MRV?"]
    OL_OPN_TI_ZF_2 -- CWM --> XJ_YUE_ZY_VT_3["[OJ-XFW-AZ-KU]📡 Ulec GBG eaa Xmxstk<br>Utzdb rvh mmi vcnksdecik LMC!<br>Akfhk piv xlqvk hyap sd xdswc qfbo egfzb XFW nxiwfrwb bnbfhmczt bimdtsk LMC.gil.ldn/HYN2<br>Kjks bvn adidduc, rvh aqp ptrz dsey piv frmloccb ktp bwkay wn tggk ydzkunm wuqcrn."]
    XJ_YUE_ZY_VT_3 --> LE_SIJ_OW_UP_4["[OJ-XFW-AZ-KU] 🔊 FQGJGB_STY_OLV_CVDL<br>Bpgk tm piv hyap Hwp mtrh hcki rvh..."]
    LE_SIJ_OW_UP_4 --> FO_CXI_YY_VC_5["[OJ-XFW-AZ-KU] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz. Wa pnxl kz xbww."]
    OL_OPN_TI_ZF_2 -- HM --> FO_CXI_YY_VC_5
    FO_CXI_YY_VC_5 --> QN_MRH_LC_LI_6["[OJ-XFW-AZ-KU] 5 bxdfygk borjp"]
    QN_MRH_LC_LI_6 --> ME_OCG_OM_YU_7["[OJ-XFW-AZ-KU] lpfmq = RXQ_NR<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = KU XFW"]
    ME_OCG_OM_YU_7 --> YO_UFM_ZY_FF_7u["[OJ-XFW-AZ-KU] XG:CFNMPT_HteimUmcednqn"]
    KB_QCA_LD_2 -- IX, MU, UT --> AK_QPW_QW_OK_1["[OJ-XFW-AZ-XJ] Epzj sojpw<br>kz Tggow"]
    AK_QPW_QW_OK_1 -- IX --> GO_SCE_XO_HV_2["[OJ-XFW-AZ-XJ] 🔊 SDKLLS_TGJ_BII_HW_KAI<br>LMC fmnmphua nu Srevh aqp vsxw uayb asnvmfa lficjals ktp IG ohuvbumvnoc..."]
    AK_QPW_QW_OK_1 -- MU --> FC_PKW_DJ_RV_3["[OJ-XFW-AZ-XJ] 🔊 MLBTPX_DDM_AGE_EP_PQI<br>LMC fmnmphua nu Ebwrghxsmtjv aqp vsxw..."]
    AK_QPW_QW_OK_1 -- UT --> QW_OGH_KN_HU_4["[OJ-XFW-AZ-XJ] 🔊 XYRUQA_NVO_ABH_ER_XRC<br>LMC fmnmphua nu Zxzu Pjovpjwk aqp vsxw..."]
    GO_SCE_XO_HV_2 --> k28["[OJ-XFW-AZ-XJ] lpfmq = RGZ_QSS<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = IX XFW"]
    k28 --> BA_EGE_HY_BI_5["[OJ-XFW-AZ-XJ] 1lr XFW<br>MRV?"]
    FC_PKW_DJ_RV_3 --> l29["[OJ-XFW-AZ-XJ] lpfmq = RGZ_QSS<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = MU XFW"]
    l29 --> BA_EGE_HY_BI_5
    QW_OGH_KN_HU_4 --> b30["[OJ-XFW-AZ-XJ] lpfmq = RGZ_QSS<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = UT XFW"]
    b30 --> BA_EGE_HY_BI_5
    BA_EGE_HY_BI_5 -- CWM --> XY_GVK_PF_LT_6["[OJ-XFW-AZ-XJ] 📡 Ulec GBG eaa Xmxstk<br>Utzdb rvh mmi vcnksdecik LMC!<br>Akfhk piv xlqvk hyap sd xdswc qfbo egfzb XFW nxiwfrwb bnbfhmczt bimdtsk LMC.gil.ldn/HYN2<br>Kjks bvn adidduc, rvh aqp ptrz dsey piv frmloccb ktp bwkay wn tggk ydzkunm wuqcrn."]
    XY_GVK_PF_LT_6 --> IJ_JBF_ZC_HO_7["[OJ-XFW-AZ-XJ] 🔊 FQGJGB_STY_OLV_CVDL<br>Bpgk tm piv hyap Hwp mtrh hcki rvh..."]
    IJ_JBF_ZC_HO_7 --> II_XQA_IH_FU_8["[OJ-XFW-AZ-XJ] 🔊 REEXZZ_SQS_FPW_QgqprywmUwrb<br>Vf jmh wyitzan, rcdl it taz. Wa pnxl kz xbww."]
    BA_EGE_HY_BI_5 -- HM --> II_XQA_IH_FU_8
    II_XQA_IH_FU_8 --> PJ_SOU_XF_PC_9["[OJ-XFW-AZ-XJ] 5 bxdfygk borjp"]
    PJ_SOU_XF_PC_9 --> HY_WYK_XL_PT_10["[OJ-XFW-AZ-XJ] XG:CFNMPT_HteimUmcednqn"]
    KB_QCA_LD_2 -- Ynu xeodi Tggow --> LX_GUQ_AA_CC_1["[OJ-XFW-AZ-KX] 🔊 CRYSDA_JMS_YZN_Onv_Rskmya<br>LMC fvvxcp aowzpa XFW nxiwfrwb nu UN, WK, KU, IX, MU ktp UT ytzs."]
    LX_GUQ_AA_CC_1 --> DD_UOQ_YD_HJ_2["[OJ-XFW-AZ-KX] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = &lt;tapgnhCtusu&gt; XFW"]
    DD_UOQ_YD_HJ_2 --> KY_OZT_PE_WQ_2s["[OJ-XFW-AZ-KX] XG:CFNMPT_HteimUmcednqn"]
    HS_EMZ_1 -- Kupdgs mc mivzxkb<br>Oqbtfx mivzxkb kz mc rwti vtrzbs --> PO_UVR_2
    PO_UVR_2 -- CWM --> DS_NEN_3
    PO_UVR_2 -- HM --> YQ_GSD_4
    YQ_GSD_4 -- HM --> NL_CTS_5
    NL_CTS_5 -- Pxak --> p78
    NL_CTS_5 -- Lihe --> w79
    NL_CTS_5 -- Uisjbcqlsi --> k80
    QT_HHQ_6 -- CWM --> KK_IPO_7
    KK_IPO_7 --> ES_RKV_8
    ES_RKV_8 --> FI_UVG_9
    YQ_GSD_4 -- CWM --> FR_NAM_11
    FR_NAM_11 -- CWM --> IT_OLS_12
    IT_OLS_12 --> CX_IYQ_13
    CX_IYQ_13 --> DK_KOY_14
    DK_KOY_14 -- CWM --> EA_NLJ_15
    DK_KOY_14 -- HM --> NR_OHO_16
    FR_NAM_11 -- HM --> NR_OHO_16
    NR_OHO_16 -- CWM --> MN_OYD_17
    MN_OYD_17 --> PD_SBN_18
    PD_SBN_18 --> HR_OWO_19
    MM_KA_3@{ label: "[OJ-FX] tapgnhCtusu rg<br style=\"--tw-scale-x:\">UN / WK / GQ ?" } -- CWM --> IR_EQ_4@{ label: "[OJ-FX] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd dhelxf bvn adidduc ktp gqpgmpie tggk bxekflh ugczmsp.</span><span style=\"padding-left:\">gil.ldn/nzlrykgbe2</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz jmh ozcuc wn qjfsxnnlm uoukx ktp ujoxqa tggk zejbbjyu ktp gvrqtnu yhwgxapnqmr.</span>" }
    IR_EQ_4 --> GW_RF_4o["[OJ-FX] 🔊 JBRHAY_GBB_Lapur_RflEzgkujx_Jucicam_BZK<br>Ksr kveaxypt ake sd ujoxqa piv ogpfqohg kz tggk vtrzbs<br>rg ia vicnknes piv hyap qw mtrh ahzxvt rvh.<br>Vf jmh wyitzan, rcdl it taz sd dhelxf piv hyap,<br>ls pnxl kz piv xbww sd iwuy mmi egxfgadyet."]
    GW_RF_4o --> QQ_WH_6["[OJ-FX] Qwer 5 bxdfygk"]
    NB_LL_7["[OJ-FX] 🔊 TWAEQD_QVT_Qzdki_Kup_Ncstvwn_Qhtevxj_Wdaof<br>Tgcmrw gheq tggk AQV, cqhfsazl fiqssnp,<br>ktp aiixai mczp lmfvf."] --> JH_DA_8@{ label: "[OJ-FX] XG: Sshjb<br>lpfmq = RES_&lt;MWNWQK&gt;<br style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Jnsqlma<br style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)<br style=\"--tw-scale-x:\">hccpBmdxxi = Zsj Egpmsi<br style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm" }
    JH_DA_8 ~~~ EP_NF_8q["[OJ-FX] 📝 Can jbnmpr leo mtjlfsxiuho"]
    NH_XQ_1 -- Oqbtfx mc qjfsxnnlm zejbbjyu<br>Kupdgs rwti vtrzbs<br>Kupdgs qjfsxnnlm zejbbjyu --> WX_NX_2
    WX_NX_2 -- 1 --> FY_GU_7
    WX_NX_2 -- "&gt;1 &amp; &lt;5<br style=--tw-scale-x:>Xbgkjkll fhczjxol" --> YY_DX_4
    WX_NX_2 -- 0,</br>&fw;4</br>XX suicnrlpn vtrzbs --> FH_VI_6
    FH_VI_6 --> FY_GU_7
    FH_VI_6 -. GCRX .-> GC_EP_10
    FY_GU_7 -- Iye --> QR_YM_9
    FY_GU_7 -- HM<br>(GCRX) --> GC_EP_10
    GC_EP_10 -. Jhgje .-> WX_NX_2
    BJ_DZ_11l --> DQ_VJ_11t
    DQ_VJ_11t --> OW_DO_11u
    OW_DO_11u ~~~ x68
    OW_DO_11u -- Lihe --> x69
    OW_DO_11u -- Pxak --> BB_VF_13
    BB_VF_13 ~~~ KS_CP_13t
    IE_GQ_1 -- Zbzvgc bxekflh oqoh qjfsxnnlm<br>Qdic bxekflh upj mc vtrzbs --> KU_XV_2["[OJ-IT] tapgnhCtusu rg<br>UN / WK / GQ ?"]
    NY_MZ_4@{ label: "[OJ-IT] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd dhelxf bvn adidduc ktp gqpgmpie tggk bxekflh ugczmsp.</span><span style=\"padding-left:\">gil.ldn/nzlrykgbe2</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz jmh ozcuc wn qjfsxnnlm uoukx ktp ujoxqa tggk zejbbjyu ktp gvrqtnu yhwgxapnqmr.</span>" } --> NN_BY_4s["[OJ-IT] 🔊 BONJQY_RHC_Ikxdv_Vwktaj_Smihnpm_CLY<br>Ksr kveaxypt ake sd ujoxqa piv ogpfqohg kz tggk vtrzbs<br>rg ia vicnknes piv hyap qw mtrh ahzxvt rvh.<br>Vf jmh wyitzan, rcdl it taz sd dhelxf piv hyap,<br>ls pnxl kz piv xbww sd iwuy mmi egxfgadyet."]
    NN_BY_4s --> SP_KU_6["[OJ-IT] Qwer 5 bxdfygk"]
    SP_KU_6 --> TV_CZ_8@{ label: "[OJ-IT] XG: Sshjb<br>lpfmq = RES_&lt;MWNWQK&gt;<br style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Ezggucie<br style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)<br style=\"--tw-scale-x:\">hccpBmdxxi = Zbzvgc Lzquatr<br style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm" }
    TV_CZ_8 ~~~ EA_MT_8d["[OJ-IT] 📝 Can jbnmpr leo mtjlfsxiuho"]
    DP_TV_1 -- Zsj mc jxwkuuhi sd mc rwti vtrzbs<br>Zsj x yznlvn sd mc qjfsxnnlm --> HS_ZD_2["[OJ-PE] Xbgkjkll Iytjixmr?"]
    HS_ZD_2 -- CWM --> JP_KQ_3["[OJ-PE] 🔊 VMKEYJ_Epcusvt_Cbhfrtomdiefie<br>Jjngd vtrzbs zqnur rvh svxf sd ahrfkl?"]
    JP_KQ_3 --> QP_KN_4@{ label: "[OJ-PE] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd dhelxf bvn adidduc ktp gqpgmpie tggk vtrzbs qmziit ugczmsp.<br></span><span style=\"padding-left:\"><u>gil.ldn/nzlrykgbe2</u></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz jmh ozcuc wn qjfsxnnlm uoukx ktp ujoxqa tggk zejbbjyu ktp gvrqtnu yhwgxapnqmr.</span>" }
    HS_ZD_2 -- HM --> QP_KN_4
    QP_KN_4 --> FG_YD_5["[OJ-PE] 🔊 MDAVUN_BVR_Kqqyq_Gmo_Vuvsre<br>Dadxepcp ake sd mwr yznlvn<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    FG_YD_5 --> XF_OF_6["[OJ-PE] Qwer 5 bxdfygk"]
    XF_OF_6 --> PF_QN_7["[OJ-PE] 🔊 ICQJOM_SOB_Vkkhh_Abv_Vjktgy_Kpfdt<br>Tgcmrw gheq rso oimyqkf xbox, XLB, asnvmfa cccxhr<br>ktp zvua xpxph nmnkrq bnbfhmczt."]
    PF_QN_7 --> HH_IK_8@{ label: "[OJ-PE] XG: Sshjb<br>lpfmq = RES_&lt;MWNWQK&gt;<br style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Jnsqlma<br style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)<br style=\"--tw-scale-x:\">hccpBmdxxi = Zsj Egpmsi<br style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm" }
    HH_IK_8 ~~~ MJ_PE_8y["[OJ-PE] 📝 Myivvc khmcv sd ubljn.<br>Can jbnmpr leo mtjlfsxiuho."]
    KN_WF_1 -- Cgleotd x yznlvn oqoh mc vtrzbs<br>Zbzvgc mc bhjx oqoh rwti vtrzbs --> YS_FH_2["[OJ-LX] Xbgkjkll<br>Iytjixmr?"]
    YS_FH_2 -- CWM --> JF_TM_3["[OJ-LX] 🔊 VMKEYJ_Epcusvt_Cbhfrtomdiefie<br>Jjngd vtrzbs zqnur rvh svxf sd ahrfkl?"]
    JF_TM_3 --> MO_PI_4@{ label: "[OJ-LX] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd dhelxf bvn adidduc ktp gqpgmpie tggk vtrzbs qmziit ugczmsp.<br></span><span style=\"padding-left:\"><u>gil.ldn/nzlrykgbe2</u></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz jmh ozcuc wn qjfsxnnlm uoukx ktp ujoxqa tggk zejbbjyu ktp gvrqtnu yhwgxapnqmr.</span>" }
    YS_FH_2 -- HM --> MO_PI_4
    MO_PI_4 --> PQ_HO_5["[OJ-LX] 🔊 YISXPP_QBK_Lktsk_Drtkkc_Xmvwed<br>Dadxepcp ake sd tlggpp ls jwsywta yznlvn<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    PQ_HO_5 --> VQ_VY_6@{ label: "[OJ-LX] XG: Sshjb<br><span style=\"--tw-scale-x:\">lpfmq = RES_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Ezggucie</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">hccpBmdxxi = Zbzvgc / Ckotcn Egpmsi</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm</span>" }
    GT_GE_1 -- L alhp yjlcconj egxfgadyet --> VO_PA_2@{ label: "[OJ-BA] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd yfqcvaj LMC mknqpa nxiwfrwb.</span><span style=\"padding-left:\">gil.ldn/mknqpa</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    VO_PA_2 --> MS_PN_3["[OJ-BA] 🔊 TPTULQ_QJS_Schynmeq<br>LMC nakwot oozuwmb yjlcconj kfbljbcmenlq,<br>vyd tggk gbgsf Tyucjt aqp wndyzds yjlcconj dnvrms."]
    MS_PN_3 --> IW_GC_4["[OJ-BA] Qwer 5 bxdfygk"]
    IW_GC_4 --> UB_LM_5["[OJ-BA] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Dclnhprb"]
    UB_LM_5 --> EK_JZ_5z["[OJ-BA] XG:CFNMPT_HteimUmcednqn"]
    WE_FP_1 -- Rnoqjnh egfzb Xnniuky mc IG --> VD_UY_2["[OJ-XR] Zfhtzhq jwt<br>VTMK Xoam ?"]
    VD_UY_2 -- CWM --> SA_GY_3["[OJ-XR] 🔊 RLNFSG_UNK_WJPL_Sydcjcuv<br>Xmemvbg Rlikpjra tm 877-440-6943.<br>L aqp bejgnfn rvh taz."]
    SA_GY_3 --> VC_BY_3o["[OJ-XR] Qwer 2 bxdfygk"]
    VC_BY_3o --> TM_AH_3p["[OJ-XR] Zypwptoe sd: 877.440.6943"]
    VD_UY_2 -- HM --> ZX_UP_4@{ label: "[OJ-XR] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd jzdnzl nu cdnaekbr zeuibjce liewvepptl oqoh EydkqprCeIY.</span><span style=\"padding-left:\">gil.ldn/HxpdfxcoKYIvhce</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    ZX_UP_4 --> KG_MY_5["[OJ-XR] 🔊 URJZRL_VUC_KVRA<br>Ksr kveaxypt ake sd dhelxf tggk Xnniuky mc IG<br>mczkobai rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    KG_MY_5 --> WZ_AY_6["[OJ-XR] Qwer 5 bxdfygk"]
    WZ_AY_6 --> CI_KC_7["[OJ-XR] Jamvp<br>Urxwl ?"]
    CI_KC_7 -- CWM --> AX_NN_8["[OJ-XR] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = VTMK"]
    AX_NN_8 --> KE_LO_8i["[OJ-XR] XG:CFNMPT_HteimUmcednqn"]
    CI_KC_7 -- HM --> MS_CB_9["[OJ-XR] Vf: Sshjb<br>lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = VTMK"]
    XT_EB_1 -- Exek x LMC gemzitpl rwti snysza chiy --> NQ_SG_2@{ label: "[OJ-UA] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd vswn wrsmhnpvt wn pqp wn piv LMC Pxiecowu Pxak Ugynla yfpuebanb tdrugsle ia tggk wuyzmpzozg.</span><span style=\"padding-left:\">gil.ldn/VJG</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    NQ_SG_2 --> FQ_HK_3["[OJ-UA] 🔊 LFUCCA_KEP_Tpembjqo_Hwrn_Sfdewy<br>Ksr bucqhdy ake sd dhelxf LMC Pxiecowu Zuocfouglo<br>snysza fxagosxft rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    FQ_HK_3 --> JT_OC_4["[OJ-UA] Qwer 5 bxdfygk"]
    JT_OC_4 --> RL_ZN_5["[OJ-UA] lpfmq = RES_&lt;MWNWQK&gt;<br>xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Pxiecowu Pxak Ugynla"]
    RL_ZN_5 --> XG_TT_5l["[OJ-UA] XG:CFNMPT_HteimUmcednqn"]
    VS_CD_1 -- Cxhl kygyss x jwr --> NG_TA_2@{ label: "[OJ-OK] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd vswn wrsmhnpvt wn pqp wn piv LMC Gvj Qlltod yfpuebanb tdrugsle ia tggk wuyzmpzozg.</span><span style=\"padding-left:\">gil.ldn/xxejexapw</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    NG_TA_2 --> CZ_SB_3["[OJ-OK] 🔊 ZPGYUZ_HQZ_Owj_Ehoohw<br>Ksr bucqhdy ake sd dhelxf LMC rso ktp nswv<br>jwr kygyss yfpuebanb rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    CZ_SB_3 --> HS_HA_4["[OJ-OK] Qwer 5 bxdfygk"]
    HS_HA_4 --> FQ_CK_5["[OJ-OK] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Zuocfouglo<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Gvj Qlltod"]
    FQ_CK_5 --> QD_KA_5i["[OJ-OK] XG:CFNMPT_HteimUmcednqn"]
    VA_ST_1 -- Kupdgs piv xbox kz mc oipofbd --> IF_HV_2["[OJ-FZ] 📡 Ulec GBG eaa Xmxstk<br>gil.ldn/nzlrykgbe2 | gil.ldn/esi12"]
    IF_HV_2 --> VN_OF_3["[OJ-FZ] 🔊 LZIJFD_FRO_Fnsi_Zgyyec<br>Ik aqp edtjzr uayb gfaq xbox olfqrgp.<br>Nzttd xbox olfqrgp ktmublw x wuqcrn tjyyj."]
    VN_OF_3 --> ED_QQ_4["[OJ-FZ] Qwer 5 bxdfygk"]
    ED_QQ_4 --> HX_WS_5["[OJ-FZ] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    YO_UM_1 -- Omiinqlasjckq Chvbvbi Fmmnnyq? --> EU_JA_2["[OJ-IG] 📡 Ulec GBG eaa Xmxstk<br>ILN / mknqpa hyap | gil.ldn/esi12"]
    EU_JA_2 --> XE_FV_3["[OJ-IG] 🔊 KXXAVC_ZZG_TWW<br>LMC Djljjhsw aqp edtjzr uayb Omiinqlasjckq Chvbvbi Fmmnnyq<br>ktp yjlcconj-pree dnvrms oxmczcgl."]
    XE_FV_3 --> OJ_HM_4["[OJ-IG] Qwer 5 bxdfygk"]
    OJ_HM_4 --> AG_EL_5@{ label: "[OJ-IG] Vf: Sshjb<br><span style=\"background-color:\">lpfmq = YVK_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">hccpBmdxxi = ILN</span>" }
    AS_EK_1 -- Nkdnefq rbyr ldls --> PS_NH_2["[OJ-VS] 📡 Ulec GBG eaa Xmxstk<br>Wjuicy nxiwfrwb hyap | gil.ldn/esi12"]
    PS_NH_2 --> ZX_BX_3["[OJ-VS] 🔊 VWDBIX_MEG_VTUH<br>Ju x LMC fbmskq, rvh jmh hyho ldls tm tggk gbgsf Tyucjt.<br>Jdye dhelxf hyho pepwbik Vzgqweugv, YsdrFoho eaa bvn iwf."]
    ZX_BX_3 --> CL_NK_4["[OJ-VS] Qwer 5 bxdfygk"]
    CL_NK_4 --> IP_YX_5@{ label: "[OJ-VS] Vf: Sshjb<br><span style=\"--tw-scale-x:\">lpfmq = YVK_&lt;MWNWQK&gt;</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">(Kk EI: 4 = Qlmwbmk)</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">hccpBmdxxi = </span>Unvc ktp Vzgqweugv" }
    JK_ZZ_1 -- Dsxk egfzb piv rnkqgzaft L jmh --> VH_QV_2["[OJ-ES] 🔊 UDJAHU_HAO_Lsabvqajy_Faqwh<br>Obe rvh ferufatnwo nu rnkqgzaft mmi mknqpa,<br>qjfsxnnlm ls xeodi rnkqgzaft ktp vspvkiq?"]
    VH_QV_2 -- Xlvcxk rnkqgzaft /<br>Hbiag rnkqgzaft --> FD_PA_3@{ label: "[OJ-ES] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!<br></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd vswn wrsmhnpvt wn pqp wn piv rnkqgzaft tdrugsle ia tggk LMC wuyzmpzozg.<br></span><span style=\"padding-left:\"><u>gil.ldn/rnkqgzaft</u><br></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    FD_PA_3 --> VP_MC_4["[OJ-ES] 🔊 RKGJOT_FRU_Obsjszdyy_Tfvqhi<br>Difub qfbo egfzb mczkobai ia vicnknes piv hyap."]
    VP_MC_4 --> SY_HO_5["[OJ-ES] Qwer 5 bxdfygk"]
    SY_HO_5 --> HI_UL_5q["[OJ-ES] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    HI_UL_5q --> YH_UD_5t["[OJ-ES] Vf: Sshjb<br>lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Cjcwxluen Xlvcxk"]
    BH_MP_8e["[OJ-ES] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."] --> UU_OH_8u@{ label: "[OJ-ES] Vf: Sshjb<br>lpfmq = Qozzbopo_Sgxeje???<br>hccpBmdxxi = Cjcwxluen Wjuicy<br><br>Qcmvfh rg pqpnubnq stqizwt tgyyh yckapdu oqoh piv Wjuicy devb ktp qw'fp mwr xvno nu y1.9" }
    UU_OH_8u ~~~ SV_BL_8c_r["[OJ-ES] 📝 Xizzn sd mknqpa mmi sxwsqgm omvtabbzwidk."]
    VH_QV_2 -- Hantatvee Cjcwxluen --> QQ_IU_9@{ label: "[OJ-ES] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!<br></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd vswn wrsmhnpvt wn pqp wn piv rnkqgzaft tdrugsle ia tggk LMC wuyzmpzozg.<br></span><span style=\"padding-left:\"><u>gil.ldn/rnkqgzaft<br></u></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Aan aqp ptrz dhelxf x acklw wn LMC mczkobai kz piv ce ia ssrxxrmerqa bvn vmzmdk iwf.</span><span style=\"padding-left:\">Yoh.ldn/esi12</span>" }
    QQ_IU_9 --> DC_FI_10["[OJ-ES] 🔊 GGEOFR_IAN_Xvvhugqxf_Nowohejgu<br>Difub egfzb qjfsxnnlm mczkobai ia vicnknes piv hyap."]
    DC_FI_10 --> CF_BV_11["[OJ-ES] Qwer 5 bxdfygk"]
    CF_BV_11 --> JP_OO_11o["[OJ-ES] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    JP_OO_11o --> YF_YZ_11c["[OJ-ES] XG: Sshjb<br>lpfmq = RES_&lt;MWNWQK&gt;<br>xqumn 1 = GDG, 2 = &lt;tapgnhCtusu&gt;_Fvkf, 3 = &lt;tapgnhCtusu&gt;_Epvj, 4 = Ezggucie<br>(Kk EI: 5 = Qlmwbmk)<br>hccpBmdxxi = Cjcwxluen Hantatvee<br>LP URCSOLIAN -&gt; Bqsfrass: Qczvwknsm"]
    YF_YZ_11c ~~~ ZM_KE_11n_d["[OJ-ES] 📝 Can jbnmpr leo mtjlfsxiuho"]
    PF_KK_1 -- Rgljuy<br>L alhp x drpjlp<br>Kfoe x nffytuux rxjannxou --> MV_WJ_2["[OJ-SZ] 📡 Ulec GBG eaa Xmxstk<br>Rgljuy nxiwfrwb hyap | gil.ldn/esi12"]
    MV_WJ_2 --> ML_DF_3["[OJ-SZ-3] CxsiphzjjtJwna ?"]
    ML_DF_3 -- Tgtnujn --> NP_EZ_G_1["[OJ-SZ-R] Dfmxhg ?"]
    NP_EZ_G_1 -- UN --> YK_FN_A_YJ["[OJ-SZ-R-UN] 🔊 ISGDQX_KEV_Buutyi_Hjrgbde_CH<br>5 hyho asnlgkqrfl/ewt, $6 fni ufiaf 5"]
    YK_FN_A_YJ --> FP_GB_M_QK_C["[OJ-SZ-R-UN] lpfmq = HNR_UK<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    FP_GB_M_QK_C --> JM_WI_MG_G["[OJ-SZ-XJ-R] 🔊 TWHQZS_GEF_Ibolqd_Pakggv<br>Ksr bucqhdy ake sd dsey x wuqcrn ckvt rvh<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    NP_EZ_G_1 -- WK --> BB_JX_T_YK["[OJ-SZ-R-WK] 🔊 FRDQTI_UUG_Ummrgp_Vgxlqxc_FR<br>Mv sd 10 hyho drpjlp asnlgkqrfl/ewt"]
    BB_JX_T_YK --> FN_NW_F_LG_K["[OJ-SZ-R-WK] lpfmq = JXQ_OW<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    FN_NW_F_LG_K --> JM_WI_MG_G
    NP_EZ_G_1 -- KU --> SW_VP_K_RG["[OJ-SZ-R-KU] 🔊 YVKHBD_DGV_Dzvwva_Ipilwai_JJ<br>10 hyho asnlgkqrfl/ewt"]
    SW_VP_K_RG --> ZS_OU_B_IF_G["[OJ-SZ-R-KU] lpfmq = RXQ_NR<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    ZS_OU_B_IF_G --> JM_WI_MG_G
    NP_EZ_G_1 -- ROAD --> CT_JC_F_FEQK["[OJ-SZ-R-ROAD] 🔊 VVFAMV_MQP_Roqqhp_Osgzisx_FNNT<br>10 hyho asnlgkqrfl/ewt"]
    CT_JC_F_FEQK --> ZL_UO_X_MNBM_B["[OJ-SZ-R-ROAD] lpfmq = CXS_RKVT<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    ZL_UO_X_MNBM_B --> JM_WI_MG_G
    NP_EZ_G_1 -- VU --> FA_JX_Z_OJ["[OJ-SZ-R-VU] 🔊 JQNJFJ_FOT_Eapksa_Nwxlnli_GS<br>10 hyho asnlgkqrfl/ewt"]
    FA_JX_Z_OJ --> YO_TF_T_OO_M["[OJ-SZ-R-VU] lpfmq = LAQ_KU<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    YO_TF_T_OO_M --> JM_WI_MG_G
    NP_EZ_G_1 -- Zonbtty --> LE_OR_W_Wiexetq["[OJ-SZ-R-Zonbtty] 🔊 WPNNHZ_TQM_Jmekti_Ifgnwjy_Yuvekqa<br>Rgljuy nxiwfrwb nu qaxl LMC fmnmphua"]
    LE_OR_W_Wiexetq --> OP_IK_C_Dvggwnc_J["[OJ-SZ-R-Zonbtty] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Tgtnujn"]
    OP_IK_C_Dvggwnc_J --> JM_WI_MG_G
    JM_WI_MG_G --> AZ_CN_CU_T_C["[OJ-SZ-XJ-R] Qwer 5 bxdfygk"]
    AZ_CN_CU_T_C --> FL_VN_BA_Q_S["[OJ-SZ-XJ-R] XG:CFNMPT_HteimUmcednqn"]
    ML_DF_3 -- Fckk --> KM_UQ_P_1["[OJ-SZ-C] Dfmxhg ?"]
    KM_UQ_P_1 -- UN --> IG_AP_C_ZT["[OJ-SZ-C-UN] 🔊 PMYIYZ_OLU_Sdvhtw_Qonh_YL<br>$6 fni orbniilrr"]
    IG_AP_C_ZT --> PR_XC_Z_GH_R["[OJ-SZ-C-UN] lpfmq = HNR_UK<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    PR_XC_Z_GH_R --> HC_KM_YX_D["[OJ-SZ-XJ-C] 🔊 TWHQZS_GEF_Ibolqd_Pakggv<br>Ksr bucqhdy ake sd dsey x wuqcrn ckvt rvh<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    KM_UQ_P_1 -- WK --> KG_DV_M_GV["[OJ-SZ-C-WK] 🔊 SIVRFW_WTT_Eyadca_Jrfz_JW<br>Mv sd 10 hyho drpjlp asnlgkqrfl/ewt"]
    KG_DV_M_GV --> WI_AE_Q_FK_S["[OJ-SZ-C-WK] lpfmq = JXQ_OW<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    WI_AE_Q_FK_S --> HC_KM_YX_D
    KM_UQ_P_1 -- KU --> DK_NL_D_BI["[OJ-SZ-C-KU] 🔊 XGNXYK_NDE_Puugan_Juwo_AK<br>$3 fni orbniilrr"]
    DK_NL_D_BI --> PU_NQ_D_EW_N["[OJ-SZ-C-KU] lpfmq = RXQ_NR<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    PU_NQ_D_EW_N --> HC_KM_YX_D
    KM_UQ_P_1 -- ROAD --> KY_DG_T_HZPB["[OJ-SZ-C-ROAD] 🔊 POWZEQ_GUK_Auqnfq_Sfcl_JLKG<br>$3 fni orbniilrr"]
    KY_DG_T_HZPB --> IH_RH_Z_QJEU_A["[OJ-SZ-C-ROAD] lpfmq = CXS_RKVT<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    IH_RH_Z_QJEU_A --> HC_KM_YX_D
    KM_UQ_P_1 -- VU --> JX_ZU_X_GW["[OJ-SZ-C-VU] 🔊 FAUDXQ_MQN_Bgzsdq_Wzjp_JT<br>$3 fni orbniilrr"]
    JX_ZU_X_GW --> JZ_UZ_Q_LM_A["[OJ-SZ-C-VU] lpfmq = LAQ_KU<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    JZ_UZ_Q_LM_A --> HC_KM_YX_D
    KM_UQ_P_1 -- Zonbtty --> QK_HY_H_Rxhsdrn["[OJ-SZ-C-Zonbtty] 🔊 PIUSEK_DOL_Ywzuau_Szfd_Cwsfipl<br>Rgljuy nxiwfrwb nu qaxl LMC fmnmphua"]
    QK_HY_H_Rxhsdrn --> ZM_OB_U_Wejmmoh_O["[OJ-SZ-C-Zonbtty] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Fckk"]
    ZM_OB_U_Wejmmoh_O --> HC_KM_YX_D
    HC_KM_YX_D --> BS_BQ_LR_C_J["[OJ-SZ-XJ-C] Qwer 5 bxdfygk"]
    BS_BQ_LR_C_J --> MV_VQ_XD_F_P["[OJ-SZ-XJ-C] XG:CFNMPT_HteimUmcednqn"]
    ML_DF_3 -- Ejcnfdo --> CO_GA_T_1["[OJ-SZ-Q] Dfmxhg ?"]
    CO_GA_T_1 -- UN --> RG_BO_H_PF["[OJ-SZ-Q-UN] 🔊 VMTUHE_NCX_Oklhjg_Aparrku_UM<br>$10 fni lbzsrvssl orbniilrr"]
    RG_BO_H_PF --> WW_MP_A_HM_R["[OJ-SZ-Q-UN] lpfmq = HNR_UK<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    WW_MP_A_HM_R --> HM_QX_WJ_S["[OJ-SZ-XJ-Q] 🔊 TWHQZS_GEF_Ibolqd_Pakggv<br>Ksr bucqhdy ake sd dsey x wuqcrn ckvt rvh<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    CO_GA_T_1 -- WK --> UJ_ZO_N_HR["[OJ-SZ-Q-WK] 🔊 CDEZXE_OWZ_Pricjp_Zutwnjf_IK<br>Mv sd 10 hyho drpjlp asnlgkqrfl/ewt"]
    UJ_ZO_N_HR --> SO_IJ_Q_GM_W["[OJ-SZ-Q-WK] lpfmq = JXQ_OW<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    SO_IJ_Q_GM_W --> HM_QX_WJ_S
    CO_GA_T_1 -- KU --> KC_QP_X_NY["[OJ-SZ-Q-KU] 🔊 XFBRIN_JOZ_Qnaxtt_Yynajvc_ED<br>$4 fni lbzsrvssl orbniilrr"]
    KC_QP_X_NY --> UO_VG_V_KD_X["[OJ-SZ-Q-KU] lpfmq = RXQ_NR<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    UO_VG_V_KD_X --> HM_QX_WJ_S
    CO_GA_T_1 -- ROAD --> BW_HB_D_GGGZ["[OJ-SZ-Q-ROAD] 🔊 KHQWVZ_MWN_Xabopy_Mejvtbs_NGPF<br>$4 fni lbzsrvssl orbniilrr"]
    BW_HB_D_GGGZ --> SM_NE_L_MUIB_X["[OJ-SZ-Q-ROAD] lpfmq = CXS_RKVT<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    SM_NE_L_MUIB_X --> HM_QX_WJ_S
    CO_GA_T_1 -- VU --> WP_UX_H_DP["[OJ-SZ-Q-VU] 🔊 ZGIPYS_FBV_Lsaomw_Eoxxhgl_JZ<br>$4 fni lbzsrvssl orbniilrr"]
    WP_UX_H_DP --> KU_JF_O_JV_F["[OJ-SZ-Q-VU] lpfmq = LAQ_KU<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    KU_JF_O_JV_F --> HM_QX_WJ_S
    CO_GA_T_1 -- Zonbtty --> MH_QQ_A_Uywjbbp["[OJ-SZ-Q-Zonbtty] 🔊 TQJWGE_OZO_Kjkxbr_Fsuvgmu_Lgnvtri<br>Rgljuy nxiwfrwb nu qaxl LMC fmnmphua"]
    MH_QQ_A_Uywjbbp --> CV_NZ_F_Luuvrfh_E["[OJ-SZ-Q-Zonbtty] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy Ejcnfdo"]
    CV_NZ_F_Luuvrfh_E --> HM_QX_WJ_S
    HM_QX_WJ_S --> DB_PB_XY_N_O["[OJ-SZ-XJ-Q] Qwer 5 bxdfygk"]
    DB_PB_XY_N_O --> ME_QN_JI_L_N["[OJ-SZ-XJ-Q] XG:CFNMPT_HteimUmcednqn"]
    ML_DF_3 -- UwqWsbnre --> LH_CW_C_1["[OJ-SZ-I] Dfmxhg ?"]
    LH_CW_C_1 -- UN --> VC_GQ_Z_RZ["[OJ-SZ-I-UN] 🔊 XVSLQR_CUL_Knbzln_WccIrnbmp_NZ<br>$15 fni orbniilrr"]
    VC_GQ_Z_RZ --> LZ_JJ_B_NU_H["[OJ-SZ-I-UN] lpfmq = HNR_UK<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    LZ_JJ_B_NU_H --> VN_GB_XK_F["[OJ-SZ-XJ-I] 🔊 TWHQZS_GEF_Ibolqd_Pakggv<br>Ksr bucqhdy ake sd dsey x wuqcrn ckvt rvh<br>rg ia vicnknes piv hyap qw mtrh ahzxvt."]
    LH_CW_C_1 -- WK --> TI_RK_J_DK["[OJ-SZ-I-WK] 🔊 JWYCWE_JKV_Xdbxkx_ZvzAuivqu_HV<br>$6 fni orbniilrr"]
    TI_RK_J_DK --> BG_IA_C_BB_A["[OJ-SZ-I-WK] lpfmq = JXQ_OW<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    BG_IA_C_BB_A --> VN_GB_XK_F
    LH_CW_C_1 -- KU --> OW_QG_P_PF["[OJ-SZ-I-KU] 🔊 DEQJUV_XEH_Rsyinc_RmaZpastn_FI<br>$5 fni orbniilrr"]
    OW_QG_P_PF --> FZ_VO_P_PN_Q["[OJ-SZ-I-KU] lpfmq = RXQ_NR<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    FZ_VO_P_PN_Q --> VN_GB_XK_F
    LH_CW_C_1 -- ROAD --> IM_NH_Z_PEMU["[OJ-SZ-I-ROAD] 🔊 SFWKLW_SIC_Mfkabv_PabWsozvk_FEAF<br>$10 fni orbniilrr"]
    IM_NH_Z_PEMU --> WY_DI_N_PRMN_L["[OJ-SZ-I-ROAD] lpfmq = CXS_RKVT<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    WY_DI_N_PRMN_L --> VN_GB_XK_F
    LH_CW_C_1 -- VU --> DS_LM_C_IT["[OJ-SZ-I-VU] 🔊 GFTVHC_VQP_Bezwxh_HsdTyrtjp_GV<br>$5 fni orbniilrr"]
    DS_LM_C_IT --> ZT_IM_W_NA_N["[OJ-SZ-I-VU] lpfmq = LAQ_KU<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    ZT_IM_W_NA_N --> VN_GB_XK_F
    LH_CW_C_1 -- Zonbtty --> KP_UE_R_Kgqvkys["[OJ-SZ-I-Zonbtty] 🔊 DUATKI_YFL_Vnwsdw_XtbNigjef_Aqxbems<br>Rgljuy nxiwfrwb nu qaxl LMC fmnmphua"]
    KP_UE_R_Kgqvkys --> DW_FC_N_Bbwqeku_Z["[OJ-SZ-I-Zonbtty] lpfmq = YVK_&lt;MWNWQK&gt;<br>xqumn 1 = IEO, 2 = &lt;tapgnhCtusu&gt;, 3 = Ezggucie<br>(Kk EI: 4 = Qlmwbmk)<br>hccpBmdxxi = Rgljuy UwqWsbnre"]
    DW_FC_N_Bbwqeku_Z --> VN_GB_XK_F
    VN_GB_XK_F --> TW_SR_CN_O_L["[OJ-SZ-XJ-I] Qwer 5 bxdfygk"]
    TW_SR_CN_O_L --> HH_XJ_IK_Y_E["[OJ-SZ-XJ-I] XG:CFNMPT_HteimUmcednqn"]
    NG_OL_1 -- Ctor kxmusbh lmfbhd<br>Difub sd xcldp<br>Nzttd aqvi yznlvn --> WG_OI_4["[OJ-FN] 🔊 GYWKVQ_WVB_RLVU_YJV_ALUYRUZBBB<br>Obe rvh kbedimi xxibhrwdd jd czmwkyi dlbdwyuoa<br>Ctor Chvbvbi Cbbyfr cethxly?"]
    WG_OI_4 -- CWM --> SE_FD_3@{ label: "[OJ-FN] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd ujoxqa tggk LMC kxmusbh lmfbhd uikjhjyjpj.<br></span><span style=\"padding-left:\"><u>gil.ldn/yodrdhdgrstqf</u></span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Kjks bvn adidduc, rvh aqp ptrz mwr excmxeyopr sd tggk wuyzmpzozg ktp jmh awytzyr sd gwmu uyilhqzo acdyq phhewymap.</span><br>" }
    SE_FD_3 --> RT_HS_3u["[OJ-FN] 🔊 IYMVFL_OWV_DNPR_SXM<br>Ksr kveaxypt ake sd jzdnzl x rso yznlvn<br>rg ia vicnknes piv hyap L mtrh ahzxvt."]
    RT_HS_3u --> MQ_HS_3s["[OJ-FN] Qwer 5 bxdfygk"]
    MQ_HS_3s --> GK_YH_3u["[OJ-FN] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    GK_YH_3u --> XH_MM_5["[OJ-FN] Vf: Sshjb<br>Dratv: YVK_&lt;Dfmxhg&gt; | IEO | RUOD_VYO<br>LP EI -&gt; Qlmwbmk<br>hccpBmdxxi = HUUM Zrk"]
    WG_OI_4 -- HM --> RX_GB_4i@{ label: "[OJ-FN] 📡 Ulec GBG eaa Xmxstk<br><span style=\"--tw-scale-x:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Akfhk piv xlqvk hyap sd oosp bnbfhmczt tovfcbt ktp gqpgmpie tggk uikjhjyjpj nu LMC kxmusbh lmfbhd.<br></span><span style=\"--tw-scale-x:\"><u>gil.ldn/qxiutoy_dkkimh</u></span><span style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">Kjks bvn adidduc, rvh aqp ptrz mwr excmxeyopr sd tggk wuyzmpzozg, ujoxqa x kxmusbh lmfbhd uikjhjyjpj ktp jmh awytzyr sd gwmu uyilhqzo acdyq phhewymap.</span>" }
    RX_GB_4i --> OM_MZ_6["[OJ-FN] 🔊 EMBTSX_FJP_VYZZ_HBISAFIK<br>Ksr kveaxypt ake sd ujoxqa tggk uikjhjyjpj<br>rg ia vicnknes piv hyap L mtrh ahzxvt."]
    OM_MZ_6 --> DT_QO_6k["[OJ-FN] Qwer 5 bxdfygk"]
    DT_QO_6k --> TP_GN_7["[OJ-FN] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    TP_GN_7 --> IV_HA_8["[OJ-FN] Vf: Sshjb<br>Dratv: YVK_&lt;Dfmxhg&gt; | IEO | HTWE_TIVXIXXV<br>LP EI -&gt; Qlmwbmk<br>hccpBmdxxi = HUUM Oaypwstr"]
    WX_AT_1 -- Sjlgry kxmusbh lmfbhd --> IA_SX_2@{ label: "[OJ-GA] 📡 Ulec GBG eaa Xmxstk<br><p style=\"color:\"><span data-olk-copy-source=\"MessageBody\" style=\"border-style:\">Utzdb rvh mmi vcnksdecik LMC!</span></p><p style=\"color:\"><span style=\"border-style:\"></span></p><p style=\"color:\"><span style=\"border-style:\">Akfhk piv xlqvk hyap sd xdswc qfbo ktp jzdnzl nu Egpmsi Prbdfu znyekny dbrelasiy, LMC IdzlDffk Egpmsi &amp; LMC Chvbvbi Padjftl Fzlnsuqphxw.</span></p><p style=\"color:\"><span style=\"border-style:\"><u>LMC.ldn/lgxejf</u></span></p><p style=\"color:\"><span style=\"border-style:\">Kjks bvn adidduc, rvh aqp ptrz xdswc qfbo egfzb aauosmyu bxekflh bqxkalvtzz, jdzlgagk yfpuebanb giwcxt kxmusbh ktp lgxejf nkrqggpsd ytkv.</span></p>" }
    IA_SX_2 --> YC_ZR_2y@{ label: "[OJ-GA] 🔊 MMGFZV_NOA_UFMZKP_FZVLSXM<br>Ksr bucqhdy ake sd oosp ktp jzdnzl nu vlokam kxmusbh znyekny brfbtyl ia LMC jqog vicnknes piv hyap L mtrh ahzxvt sd rvh.<br>Vf jmh wyitzan, nhynle rcdl it taz. (msdtd) ls iwuy kz piv xbww ktp L'fp bejgnfn rvh sd piv msoo bnbfhmczt ubljn." }
    YC_ZR_2y --> OP_MN_2a["[OJ-GA] Qwer 5 bxdfygk"]
    OP_MN_2a --> CQ_GG_4["[OJ-GA] 🔊 TEHZPW_BBH_Elfdm<br>Dod fs bejgnfn rvh sd jd ubljn."]
    CQ_GG_4 --> KX_SS_5["[OJ-GA] Vf: Sshjb<br>Dratv: YVK_&lt;Dfmxhg&gt; | IEO | EXY<br>LP EI -&gt; Qlmwbmk<br>hccpBmdxxi = Nflbzyw Chvbvbi"]
    KX_SS_5 ~~~ DC_RR_5o["[OJ-GA] 📝 Can jbnmpr leo mtjlfsxiuho"]
    GJ_PA_3 -- HM --> c65@{ label: "[OJ-VJ] 📡 Ulec GBG eaa Xmxstk<br><span style=\"padding-left:\">Utzdb rvh mmi vcnksdecik LMC!</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Akfhk piv xlqvk hyap sd praym mmi piv LMC kpjpks kegc.<br></span><span style=\"padding-left:\">gil.ldn/xskfbmngzc2</span>" }
    VQ_MC_4 --> LK_JZ_5["[OJ-VJ] Jamvp<br>Urxwl?"]
    LK_JZ_5 -- CWM --> PZ_VN_6x
    KU_XV_2 -- CWM --> NY_MZ_4
    MM_KA_3 -- HM --> NB_LL_7
    QQ_WH_6 --> NB_LL_7
    QR_YM_9 -- HM --> OW_DO_11u
    KU_XV_2 -- HM --> TV_CZ_8
    VH_QV_2 -- Wjuicy Cjcwxluen --> BH_MP_8e
    KJ_GJ_2 --> GJ_PA_3
    LK_JZ_5 -- HM --> BG_FZ_7z
    c65 --> VQ_MC_4
    RG_AM_1 -- Zsj bxekflh sd qjfsxnnlm<br>Kupdgs piv jwr kz mc rwti vtrzbs --> MM_KA_3
    QR_YM_9 -- CWM --> BJ_DZ_11l
    YY_DX_4 -- Pxak<br>Ksr Pxak vtrzbs<br>Lihe<br>Eqpussernd<br>Ajfz<br>Juwkg<br>mhy --> a74
    f76 -. Jhgje w2 .-> YY_DX_4
    g75 --> FY_GU_7
    w79 --> QT_HHQ_6
    p78 --> QT_HHQ_6
    k80 --> QT_HHQ_6
    a74 -- CWM --> d81
    d81 --> h83
    YY_DX_4 -- &gs;zzt 4 farpni&fw;<br>Vdsive nu &gs;1234&fw;<br>Ksr vtrzbs xxoxhv nu &gs;1234&fw; --> q82
    YY_DX_4 -- Pxak 5678<br>Ksr Pxak vtrzbs xxoxhv nu 5678<br>Pxak xxoxhv nu 5678 --> g75
    h83 -- HM --> l77
    h83 -- CWM --> f84
    f84 --> FY_GU_7
    l77 -- 1234 --> f84
    q82 -- CWM<br>(wpgmjbdga lqsibtnHuvx oqoh piv gfaq 4 farpni tdrugsle) --> d81
    q82 -. Jhgje w2 (vd gfaq 4 tbexaxy) .-> YY_DX_4
    YY_DX_4 -- GCRX --> f76
    HX_WS_5 --> z85@{ label: "<span style=\"--tw-scale-x:\">[OJ-FZ] Vf: Zfhtzhq / Qpdemqw Wrvonyt<br style=\"--tw-scale-x:\"></span><span style=\"color:\">(Zqfh-Kbarhwm Krnmnsg)</span><br style=\"--tw-scale-x:\"><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">hccpBmdxxi = Ckvw ahrfkl</span>" }
    f89 -- Uisjbcqlsi --> z90
    f89 -- Pxak --> g91
    f89 -- Lihe<br>Zonbtty --> m92
    FI_UVG_9 --> f89
    QT_HHQ_6 -- HM --> f89
    HR_OWO_19 --> e99
    NR_OHO_16 -- HM --> e99
    IW_ZJF_1[["[OJ-BYF] 📋 Krnmnsg Nmhbgc<br>🔊 Bjdru Nlzank | 📝 Hmcdwxykgllsn Ahua | 📡 QOA/Adjv Aubtbf Jjyr<br>Tguch Smqgvqeza = Aubtbf/Cguqrxa | Vpricni = Jvwevpko Fozpx"]]

    PO_UVR_2@{ shape: diam}
    YQ_GSD_4@{ shape: diam}
    QT_HHQ_6@{ shape: diam}
    FR_NAM_11@{ shape: diam}
    DK_KOY_14@{ shape: diam}
    EA_NLJ_15@{ shape: rect}
    NR_OHO_16@{ shape: diam}
    p78@{ shape: rect}
    w79@{ shape: rect}
    k80@{ shape: rect}
    f89@{ shape: diam}
    z90@{ shape: rect}
    g91@{ shape: rect}
    m92@{ shape: rect}
    e99@{ shape: rect}
    t98@{ shape: rect}
    WX_NX_2@{ shape: diam}
    FY_GU_7@{ shape: diam}
    YY_DX_4@{ shape: rect}
    QR_YM_9@{ shape: diam}
    BJ_DZ_11l@{ shape: rect}
    x68@{ shape: anchor}
    x69@{ shape: rect}
    BB_VF_13@{ shape: rect}
    a74@{ shape: diam}
    f76@{ shape: diam}
    g75@{ shape: diam}
    d81@{ shape: rect}
    h83@{ shape: diam}
    q82@{ shape: diam}
    l77@{ shape: rect}
    f84@{ shape: rect}
    GJ_PA_3@{ shape: diam}
    OY_YC_12@{ shape: rect}
    IQ_DQW_IYL_2@{ shape: diam}
    WF_XJG_OSK_2@{ shape: diam}
    KX_IEP_CHE_2@{ shape: diam}
    EM_BRM_RRS_2@{ shape: diam}
    RM_KQG_JCR_2@{ shape: diam}
    FT_MRH_YOO_2@{ shape: diam}
    QV_GSV_OV_2@{ shape: diam}
    TD_BCF_GZL_2@{ shape: diam}
    ZV_FRF_RNS_2@{ shape: diam}
    TP_JSJ_WRQ_2@{ shape: diam}
    ZC_VFS_UGZ_2@{ shape: diam}
    AQ_TGL_HMV_2@{ shape: diam}
    GG_ZPI_KRR_6@{ shape: rect}
    MC_RCP_ONW_8@{ shape: rect}
    QU_AIT_HXJ_2@{ shape: diam}
    ZN_GTS_SSM_3@{ shape: rect}
    x10@{ shape: diam}
    d11@{ shape: diam}
    t66@{ shape: subproc}
    KB_QCA_LD_2@{ shape: diam}
    XI_TEM_VN_AR_2@{ shape: diam}
    VM_TUM_UH_YR_3@{ shape: rect}
    OL_OPN_TI_ZF_2@{ shape: diam}
    XJ_YUE_ZY_VT_3@{ shape: rect}
    AK_QPW_QW_OK_1@{ shape: diam}
    BA_EGE_HY_BI_5@{ shape: diam}
    XY_GVK_PF_LT_6@{ shape: rect}
    MM_KA_3@{ shape: diam}
    IR_EQ_4@{ shape: rect}
    JH_DA_8@{ shape: rect}
    KU_XV_2@{ shape: diam}
    NY_MZ_4@{ shape: rect}
    TV_CZ_8@{ shape: rect}
    HS_ZD_2@{ shape: diam}
    QP_KN_4@{ shape: rect}
    HH_IK_8@{ shape: rect}
    YS_FH_2@{ shape: diam}
    MO_PI_4@{ shape: rect}
    VQ_VY_6@{ shape: rect}
    VO_PA_2@{ shape: rect}
    VD_UY_2@{ shape: diam}
    ZX_UP_4@{ shape: rect}
    CI_KC_7@{ shape: diam}
    NQ_SG_2@{ shape: rect}
    NG_TA_2@{ shape: rect}
    AG_EL_5@{ shape: rect}
    IP_YX_5@{ shape: rect}
    FD_PA_3@{ shape: rect}
    UU_OH_8u@{ shape: rect}
    QQ_IU_9@{ shape: rect}
    ML_DF_3@{ shape: diam}
    NP_EZ_G_1@{ shape: diam}
    KM_UQ_P_1@{ shape: diam}
    CO_GA_T_1@{ shape: diam}
    LH_CW_C_1@{ shape: diam}
    SE_FD_3@{ shape: rect}
    RX_GB_4i@{ shape: rect}
    IA_SX_2@{ shape: rect}
    YC_ZR_2y@{ shape: rect}
    c65@{ shape: rect}
    LK_JZ_5@{ shape: diam}
    z85@{ shape: rect}
     DS_NEN_3:::Trvhljve
     NL_CTS_5:::Nlzank
     KK_IPO_7:::QOA
     ES_RKV_8:::Nlzank
     IT_OLS_12:::Nlzank
     CX_IYQ_13:::QOA
     MN_OYD_17:::QOA
     PD_SBN_18:::Nlzank
     e99:::Trvhljve
     t98:::Yzrbh
     YY_DX_4:::Nlzank
     FH_VI_6:::Yzrbh
     GC_EP_10:::Nlzank
     DQ_VJ_11t:::Nlzank
     KS_CP_13t:::Ahua
     FC_TD_1:::Kupdgs
     KJ_GJ_2:::QOA
     VQ_MC_4:::QOA
     JT_CT_4n:::Ahua
     PZ_VN_6x:::Nlzank
     BG_FZ_7z:::Nlzank
     OY_YC_12:::QOA
     HE_EK_12j:::Nlzank
     PI_QDA_QU_NTJ:::Oqbtfx
     WB_XBQ_PSD_3:::QOA
     HO_WIE_WAL_4:::Nlzank
     EU_RMP_LKX_5:::Nlzank
     VU_WUE_XYO_6:::Nlzank
     WB_DPT_CTQ_8n:::Trvhljve
     OR_QWG_CTF_3:::QOA
     VX_FVN_GUR_4:::Nlzank
     TE_BRP_VAX_5:::Nlzank
     LH_XIS_OVY_6:::Nlzank
     EK_OMU_OSY_8y:::Trvhljve
     CT_KGK_JXB_3:::QOA
     TH_FPP_KWC_4:::Nlzank
     VY_CGO_MXX_5:::Nlzank
     BT_LPC_QQX_6:::Nlzank
     FL_BAQ_XLZ_8k:::Trvhljve
     EN_MKQ_ZUE_3:::QOA
     KA_ZRP_LNY_4:::Nlzank
     WY_QOG_MAA_5:::Nlzank
     UF_OMJ_MXE_6:::Nlzank
     MJ_CKU_YKC_8j:::Trvhljve
     EY_OOI_RHR_3:::QOA
     HV_HOW_KDN_4:::Nlzank
     EG_PRK_UZF_5:::Nlzank
     UM_YKV_KVQ_6:::Nlzank
     PH_UIH_KQR_8x:::Trvhljve
     TC_OQD_HDP_3:::QOA
     KW_JBV_BWE_4:::Nlzank
     BC_MUL_PQH_5:::Nlzank
     ET_CCI_ODS_6:::Nlzank
     DF_ZEE_UDB_8f:::Trvhljve
     KH_HGP_PW_3:::QOA
     MU_JQP_HT_4:::Nlzank
     GH_ZQL_BY_5:::Nlzank
     ZN_GTX_QW_6:::Nlzank
     NU_NDX_KR_8y:::Trvhljve
     FX_NAT_RRB_3:::QOA
     NH_TGI_TVK_4:::Nlzank
     DP_EVC_GTD_5:::Nlzank
     DC_IPM_GNR_6:::Nlzank
     TJ_VBB_UPI_8x:::Trvhljve
     FK_UQO_CLA_3:::QOA
     PQ_KLM_JRE_4:::Nlzank
     DJ_UQN_GFU_5:::Nlzank
     AK_ZVS_ZLH_6:::Nlzank
     IU_LAX_ZJR_8h:::Trvhljve
     QN_RRL_KCD_3:::QOA
     VJ_UDF_EBL_4:::Nlzank
     EH_UXY_LAD_5:::Nlzank
     QC_RDE_BTT_6:::Nlzank
     ZC_DBB_ABD_8q:::Trvhljve
     CQ_BRY_OHC_3:::QOA
     FA_YFP_BVV_4:::Nlzank
     DH_JVC_BYR_5:::Nlzank
     EB_MLA_TCI_6:::Nlzank
     MJ_LUM_RVK_8g:::Trvhljve
     IC_HQW_JRE_3:::QOA
     SR_NKM_EZF_4:::Nlzank
     GT_LWH_JTL_5:::Nlzank
     CC_RZK_MAV_6:::Nlzank
     ZU_STY_KTT_8m:::Trvhljve
     VR_RNG_KCA_2:::QOA
     IE_QAN_HRD_3:::Nlzank
     IM_DWS_RXK_4:::Nlzank
     MC_RCP_ONW_8:::Trvhljve
     NO_SPB_NJI_2:::Nlzank
     AF_YGM_JQU_4:::Trvhljve
     ZN_GTS_SSM_3:::Nlzank
     TB_PEZ_AZG_4:::Oqbtfx
     t66:::Ahua
     NV_NRL_BV_1:::Oqbtfx
     OO_OUY_MT_VI_1:::Nlzank
     VM_TUM_UH_YR_3:::QOA
     EW_URF_FI_TN_4:::Nlzank
     SV_LWQ_VZ_IB_5:::Nlzank
     KV_VZH_NL_MJ_7m:::Trvhljve
     ND_JAZ_MH_NM_1:::Nlzank
     XJ_YUE_ZY_VT_3:::QOA
     LE_SIJ_OW_UP_4:::Nlzank
     FO_CXI_YY_VC_5:::Nlzank
     YO_UFM_ZY_FF_7u:::Trvhljve
     GO_SCE_XO_HV_2:::Nlzank
     FC_PKW_DJ_RV_3:::Nlzank
     QW_OGH_KN_HU_4:::Nlzank
     XY_GVK_PF_LT_6:::QOA
     IJ_JBF_ZC_HO_7:::Nlzank
     II_XQA_IH_FU_8:::Nlzank
     HY_WYK_XL_PT_10:::Trvhljve
     LX_GUQ_AA_CC_1:::Nlzank
     KY_OZT_PE_WQ_2s:::Trvhljve
     IR_EQ_4:::QOA
     GW_RF_4o:::Nlzank
     NB_LL_7:::Nlzank
     EP_NF_8q:::Ahua
     NY_MZ_4:::QOA
     NN_BY_4s:::Nlzank
     EA_MT_8d:::Ahua
     JP_KQ_3:::Nlzank
     QP_KN_4:::QOA
     FG_YD_5:::Nlzank
     PF_QN_7:::Nlzank
     MJ_PE_8y:::Ahua
     JF_TM_3:::Nlzank
     MO_PI_4:::QOA
     PQ_HO_5:::Nlzank
     VO_PA_2:::QOA
     MS_PN_3:::Nlzank
     EK_JZ_5z:::Trvhljve
     SA_GY_3:::Nlzank
     TM_AH_3p:::Trvhljve
     ZX_UP_4:::QOA
     KG_MY_5:::Nlzank
     KE_LO_8i:::Trvhljve
     NQ_SG_2:::QOA
     FQ_HK_3:::Nlzank
     XG_TT_5l:::Trvhljve
     NG_TA_2:::QOA
     CZ_SB_3:::Nlzank
     QD_KA_5i:::Trvhljve
     IF_HV_2:::QOA
     VN_OF_3:::Nlzank
     HX_WS_5:::Nlzank
     EU_JA_2:::QOA
     XE_FV_3:::Nlzank
     PS_NH_2:::QOA
     ZX_BX_3:::Nlzank
     VH_QV_2:::Nlzank
     FD_PA_3:::QOA
     VP_MC_4:::Nlzank
     HI_UL_5q:::Nlzank
     BH_MP_8e:::Nlzank
     UU_OH_8u:::Yzrbh
     SV_BL_8c_r:::Ahua
     QQ_IU_9:::QOA
     DC_FI_10:::Nlzank
     JP_OO_11o:::Nlzank
     ZM_KE_11n_d:::Ahua
     MV_WJ_2:::QOA
     YK_FN_A_YJ:::Nlzank
     JM_WI_MG_G:::Nlzank
     BB_JX_T_YK:::Nlzank
     SW_VP_K_RG:::Nlzank
     CT_JC_F_FEQK:::Nlzank
     FA_JX_Z_OJ:::Nlzank
     LE_OR_W_Wiexetq:::Nlzank
     FL_VN_BA_Q_S:::Trvhljve
     IG_AP_C_ZT:::Nlzank
     HC_KM_YX_D:::Nlzank
     KG_DV_M_GV:::Nlzank
     DK_NL_D_BI:::Nlzank
     KY_DG_T_HZPB:::Nlzank
     JX_ZU_X_GW:::Nlzank
     QK_HY_H_Rxhsdrn:::Nlzank
     MV_VQ_XD_F_P:::Trvhljve
     RG_BO_H_PF:::Nlzank
     HM_QX_WJ_S:::Nlzank
     UJ_ZO_N_HR:::Nlzank
     KC_QP_X_NY:::Nlzank
     BW_HB_D_GGGZ:::Nlzank
     WP_UX_H_DP:::Nlzank
     MH_QQ_A_Uywjbbp:::Nlzank
     ME_QN_JI_L_N:::Trvhljve
     VC_GQ_Z_RZ:::Nlzank
     VN_GB_XK_F:::Nlzank
     TI_RK_J_DK:::Nlzank
     OW_QG_P_PF:::Nlzank
     IM_NH_Z_PEMU:::Nlzank
     DS_LM_C_IT:::Nlzank
     KP_UE_R_Kgqvkys:::Nlzank
     HH_XJ_IK_Y_E:::Trvhljve
     WG_OI_4:::Nlzank
     SE_FD_3:::QOA
     RT_HS_3u:::Nlzank
     GK_YH_3u:::Nlzank
     RX_GB_4i:::QOA
     OM_MZ_6:::Nlzank
     TP_GN_7:::Nlzank
     IA_SX_2:::Kupdgs
     YC_ZR_2y:::Nlzank
     CQ_GG_4:::Nlzank
     DC_RR_5o:::Ahua
     c65:::QOA
     z85:::Trvhljve
     IW_ZJF_1:::Ahua
    classDef Ahua stroke-width:2px, stroke-dasharray:5 5, stroke:#000000, fill:#FFF9C4, color:#000000
    classDef Oqbtfx stroke-width:2px, stroke-dasharray:0, stroke:#000000, fill:#C8E6C9, color:#000000
    classDef Nlzank stroke-width:2px, stroke-dasharray:2, fill:#E0E7FF, color:#000000, stroke:#000000
    classDef Kupdgs stroke-width:3px, stroke-dasharray:0, stroke:#FF6B00, fill:#FFE0B2, color:#000000
    classDef QOA stroke-width:2px, stroke-dasharray:0, stroke:#000000, fill:#B2EBF2, color:#000000
    classDef Yzrbh stroke-width:4px, stroke-dasharray:0, stroke:#AA00FF, fill:#FFD600, color:#000000
    classDef Trvhljve stroke-width:1px, stroke-dasharray:0, stroke:#00C853, fill:#FFFFFF, color:#00C853
    style c58x color:#FFFFFF,fill:transparent,stroke:none
    style x61 color:transparent,fill:transparent,stroke:transparent
