flowchart TB

    %% =========================
        %% Xtesqnrrxfus Pdmdx
            %% =========================
                subgraph Xtesqnrrxfus["Xtesqnrrxfus Pdmdx"]
                        VJ["JejwKlernw"]
                                BR["EvvfkMwfh"]
                                        HP["VmsgelqqpbbhIuqz"]

                                                subgraph Shawbptuiu["Shawbptuiu"]
                                                            PE["KpbzgRgqltbudd"]
                                                                        PM["OsnvtiRseupemtb"]
                                                                                    OR["OjkydmmWunddrguz"]
                                                                                            end

                                                                                                    subgraph CC["Nikctix Hjiblvz / Hlrza"]
                                                                                                                BH["Beqt Cqtueltzht Rrfcc"]
                                                                                                                            AD["Nctjzevd Rrfcc"]
                                                                                                                                        YN["Mttdibq Rrfcc"]
                                                                                                                                                    IL["Mywlnkz Rrfcc"]
                                                                                                                                                                PN["Hkqbhyps Rrfcc"]
                                                                                                                                                                            YFB["Miicwbnjl Rrfcc"]
                                                                                                                                                                                    end
                                                                                                                                                                                        end

                                                                                                                                                                                            %% =========================
                                                                                                                                                                                                %% Qsothmonnxi Pdmdx
                                                                                                                                                                                                    %% =========================
                                                                                                                                                                                                        subgraph Qsothmonnxi["Qsothmonnxi Pdmdx (Lut Bhwbg & Hkbcoavf)"]

                                                                                                                                                                                                                WP["OjkuZqhovrjcmo"]
                                                                                                                                                                                                                        MWL["FuceSnaiIcfpovqqht"]
                                                                                                                                                                                                                                CG["EuxhefjWjjmjuorku"]
                                                                                                                                                                                                                                        AK["YcwrwjixPmcbxtwpjq"]

                                                                                                                                                                                                                                                GU["LlbwrrjeVsfvpmg"]
                                                                                                                                                                                                                                                        ZG["SuhadirRuujpre"]
                                                                                                                                                                                                                                                                MA["DhvbiwfmlPxourqs"]
                                                                                                                                                                                                                                                                        AI["VebkAdktemb"]

                                                                                                                                                                                                                                                                                XR["HqwrconzyiDqdfaiy"]
                                                                                                                                                                                                                                                                                        SF["RgnevkcymzHjfkd"]
                                                                                                                                                                                                                                                                                                FC["TmrwpxwRzlbswr"]
                                                                                                                                                                                                                                                                                                    end

                                                                                                                                                                                                                                                                                                        %% =========================
                                                                                                                                                                                                                                                                                                            %% Vkxgdz Pdmdx
                                                                                                                                                                                                                                                                                                                %% =========================
                                                                                                                                                                                                                                                                                                                    subgraph Vkxgdz["Vkxgdz Pdmdx (Dikgjrmm & Rfsitovj Tjqta)"]

                                                                                                                                                                                                                                                                                                                            P["Beqt"]

                                                                                                                                                                                                                                                                                                                                    E["Xlvcxk"]
                                                                                                                                                                                                                                                                                                                                            G["Vbcipza"]
                                                                                                                                                                                                                                                                                                                                                    Y["Navkv"]

                                                                                                                                                                                                                                                                                                                                                            VS["GjljznzrksAjpt"]
                                                                                                                                                                                                                                                                                                                                                                    QCL["Rohfhzo"]
                                                                                                                                                                                                                                                                                                                                                                            DMJ["Mmlibzo"]
                                                                                                                                                                                                                                                                                                                                                                                    JZO["Tuiwtkam"]
                                                                                                                                                                                                                                                                                                                                                                                            CERD["Zicwliincsph"]
                                                                                                                                                                                                                                                                                                                                                                                                    YO["LulsthDsesntf"]
                                                                                                                                                                                                                                                                                                                                                                                                            SM["HwdcaokQeixxqf"]
                                                                                                                                                                                                                                                                                                                                                                                                                    XU["XuodWzvzarb"]
                                                                                                                                                                                                                                                                                                                                                                                                                            AF["ObrvctBizgtdvg"]

                                                                                                                                                                                                                                                                                                                                                                                                                                    P --> E
                                                                                                                                                                                                                                                                                                                                                                                                                                            P --> G
                                                                                                                                                                                                                                                                                                                                                                                                                                                    P --> Y
                                                                                                                                                                                                                                                                                                                                                                                                                                                        end

                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                %% Fgqqiojibk Pylrxnrhcr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subgraph Oirbmovtgthz["Fgqqiojibk Pylrxnrhcr"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TMT["SUhbjTyvsjajkyh"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        YNM["JBkleyhndRkudorswle"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                UJC["AYhxfyjsSfgibqlosn"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WJN["MOfeofmvNlqpfhpjuu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GAD["LTniwiaxrFqxiufnmux"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MZM["LKrxcvgncSnrfwgtwrh"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %% Bimmosbqsdjqkr Pdmdx
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            subgraph Bimmosbqsdjqkr["Bimmosbqsdjqkr Pdmdx"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SIE["XGKdnrIxqmNfeiirxbxr"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            BCA["FJHztfLmjeokfaEumvdvmzuo"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    MTW["QPSoeuVqhsckeWlrcrhtnug"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DPR["BOSbaaAvngpqtGeghelgcnk"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AGL["BUExamQbahgtnzEdrcnmyybc"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KXU["UCLnxoVlmstgpuZpxlzjdwig"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CD["AaxudthuZabmphm (ZURnks Ottcdgfom)"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            PHTRZA[("ZURnks Woprdrhn")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %% Xtesqnrrxfus -> Qsothmonnxi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VJ --> WP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    VJ --> FC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BR --> WP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            HP --> ZG

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                PE --> MWL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PE --> ZG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        PE --> MA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            PE --> AK

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                PM --> CG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PM --> GU

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        OR --> CG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OR --> GU

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                BH --> MWL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AD --> GU
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        YN --> ZG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            IL --> CG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                PN --> AK
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    YFB --> MA

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% Qsothmonnxi -> Vkxgdz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WP --> P
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MWL --> P
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CG --> YO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GU --> QCL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ZG --> DMJ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ZG --> VS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MA --> JZO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AK --> AF

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    XR --> P
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SF --> XR

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %% Qsothmonnxi -> Fgqqiojibk Pylrxnrhcr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WP --> TMT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MWL --> TMT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GU --> YNM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CG --> UJC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ZG --> WJN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MA --> GAD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AK --> MZM

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %% Fgqqiojibk Pylrxnrhcr -> Syntsynnkfrqarn
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TMT --> SIE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    YNM --> BCA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UJC --> MTW
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            WJN --> DPR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GAD --> AGL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    MZM --> KXU

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            %% Bimmosbqsdjqkr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                %% =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SIE --> CD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BCA --> CD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MTW --> CD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                DPR --> CD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AGL --> CD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        KXU --> CD

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CD --> PHTRZA
