---
description: >-
  Stick half-arrowhead in the bottom half with the head reversed onto the
  source (`\\-`), solid line, from Alice to John.
---
sequenceDiagram
  Alice \\-John: Hello Alice, how are you?
  Alice \\-John: Hi Alice, I can hear you!
  Alice \\-John: Test
