---
description: >-
  Stick half-arrowhead pointing into the top half only (`--\\`), dotted
  line, from Alice to John.
---
sequenceDiagram
  Alice--\\John: Hello John, how are you?
  Alice--\\John: Hi Alice, I can hear you!
  Alice--\\John: Test
