%%{init: { 'logLevel': 'debug', 'theme': 'neutral' } }%%
timeline
  title History of Social Media Platform
  2002 : LinkedIn
  2004 : Facebook : Google
  2005 : YouTube
  2006 : Twitter
  2007 : Tumblr
  2008 : Instagram
  2010 : Pinterest
