---
config:
  elk:
    nodePlacementAlignment: BALANCED
---

flowchart TD
  Start([Start]) --> Split{Ready to Process?}
  Split -->|yes| T1[Task A]
  Split -->|yes| T2[Task B]
  T1 --> Merge((Join Results))
  T2 --> Merge
  Merge --> Done([Done])
