---
config:
  elk:
    nodePlacementAlignment: NONE
---
flowchart LR
    subgraph G1
        N00
        N11
        N12
        N13
    end
    subgraph G2
        N21
        N22
    end
    N00 --- N01 & N02 & N03 & N04 & N05
    N00 --- N11 & N12 & N13 & N22
    N11 --- N22
    N11 --- N22
    N11 --- N22
    N11 --- N22
    N11 --- N22
