stateDiagram-v2
    State1
    note left of State1 : a short note
    State2
    note right of State2
        A note can also
        be defined on
        several lines
    end note
    State1 --> State2
