---
config:
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
%%{init: {'theme':'base'}}%%
sequenceDiagram
  autonumber
  participant Alice
  participant Bob
  participant Charlie
  Alice->>()Bob: Solid arrow with circle at destination
  Alice-->>()Bob: Dotted arrow with circle at destination
  Alice->()Bob: Open arrow with circle at destination
  Alice--x()Bob: Cross arrow with circle at destination
  Alice--)()Bob: Close arrow with circle at destination
