---
config:
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
%%{init: {'theme':'base'}}%%
sequenceDiagram
  autonumber
  participant Alice
  participant Bob
  participant Charlie
  Alice()->>Bob: Circle at source with solid arrow
  Alice()-->>Bob: Circle at source with dotted arrow
  Alice()->Bob: Circle at source with open arrow
  Alice()--xBob: Circle at source with cross arrow
  Alice()--)Bob: Circle at source with close arrow
