---
config:
  look: classic
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
sequenceDiagram
  participant API@{ "type" : "boundary", "alias": "Internal Name" } as External Name
  participant DB@{ "type" : "database", "alias": "Internal DB" } AS External DB
  API ->> DB: Query
  DB -->> API: Result
