---
config:
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
%%{init: {'theme':'base'}}%%
sequenceDiagram
  autonumber
  participant Alice
  participant Bob
  participant Charlie
  Alice()->>()Bob: Circles at both ends with solid arrow
  Alice()-->>()Bob: Circles at both ends with dotted arrow
  Alice()->()Bob: Circles at both ends with open arrow
  Alice()--x()Bob: Circles at both ends with cross arrow
  Alice()--)()Bob: Circles at both ends with close arrow
