---
config:
  themeCSS: '.loopText { fill: #ffffff !important; } .labelBox { fill: red !important; }'
---
sequenceDiagram
  participant Alice
  participant Bob
  opt Outer
  alt Command A
    Alice->>Bob: Request A
  else Command B
    Alice->>Bob: Request B
  else Command C
    Alice->>Bob: Request C
  end
  end
