---
config:
  look: classic
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
sequenceDiagram
  participant Alice
  participant Bob
  Alice ()<<->>() Bob: Bidirectional solid
  Alice ()<<-->>() Bob: Bidirectional dotted
