sequenceDiagram
  participant Alice@{ "type" : "boundary" }
  actor Bob
  Alice->>Bob: Hola
  Note left of Alice: Extremely utterly long line of longness which had previously overflown the actor box as it is much longer than what it should be
  Bob->>Alice: I'm short though
