---
config:
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
%%{init: {'theme':'base'}}%%
sequenceDiagram
  autonumber
  participant Alice
  participant Bob
  participant Charlie
  Alice()->>Alice: Circle at source with solid arrow
  Bob()-->>Bob: Circle at source with dotted arrow
  Charlie()->Charlie: Circle at source with open arrow
  Alice()--xAlice: Circle at source with cross arrow
  Bob()--)Bob: Circle at source with close arrow
