---
config:
  look: classic
  sequence:
    diagramMarginX: 50
    diagramMarginY: 10
---
sequenceDiagram
  participant Alice
  participant Bob
  Alice ()->>() Bob: Solid open arrow
  Alice ()-->>() Bob: Dotted open arrow
  Alice ()-x() Bob: Solid cross
  Alice ()--x() Bob: Dotted cross
  Alice ()->() Bob: Solid arrow
