---
config:
  theme: redux-color
  look: neo
---
sequenceDiagram
  actor User
  participant API
  participant DB@{ "type" : "database" } as Database
  Note over User: A note on the actor
  rect
    User ->> API: request
    API ->> DB: query
  end
  Note over API,DB: A wider note
  rect rgb(200, 230, 255)
    DB -->> API: rows
  end
  API -->> User: response
