---
config:
  sequence:
    wrap: true
---
sequenceDiagram
  Alice->>Bob: Extremely utterly long line of longness which had previously overflown the actor box as it is much longer than what it should be
  loop Loopy
  Bob->>Alice: Pasten
  end
