%%{init: {'config': {'wrap': true }}}%%
sequenceDiagram
  participant A as Extremely utterly long line of longness which had previously overflown the actor box as it is much longer than what it should be
  A->>Bob: Hola
  Bob-->A: Pasten !
