sequenceDiagram
  Alice<<->>John: Hello John, how are you?
  Alice<<-->>John: Hi Alice, I can hear you!
  John<<->>Alice: This also works the other way
  John<<-->>Alice: Yes
  Alice->John: Test
  John->>Alice: Still works
