name: Applitools E2E (Develop Branch)

on:
  push:
    branches:
      - develop
      - applitools_workflow
    paths:
      - '.github/workflows/applitools-tests.yml'
  workflow_dispatch:
    # Manual triggering only - to limit Applitools usage
    inputs:
      parent_branch:
        required: true
        type: string
        default: master
        description: 'Parent branch to use for PRs'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

env:
  # on PRs from forks, this secret will always be empty, for security reasons
  USE_APPLI: ${{ secrets.APPLITOOLS_API_KEY && 'true' || '' }}

jobs:
  applitools-e2e:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        # uses version from "packageManager" field in package.json

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: pnpm
          node-version-file: '.node-version'

      - name: Install Packages
        run: |
          pnpm install --frozen-lockfile

      - name: Start server
        run: pnpm dev

      - name: Run Cypress with Applitools
        # If you use eyes-cypress runner, switch to `pnpm dlx eyes-cypress run`
        run: pnpm cypress run --spec "cypress/integration/rendering/appli.spec.js"
        env:
          # ensure these are visible to Cypress + Applitools
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          USE_APPLI: true
