name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        # uses version from "packageManager" field in package.json

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: pnpm
          node-version-file: '.node-version'

      - name: Install Packages
        run: |
          pnpm install --frozen-lockfile
        env:
          CYPRESS_CACHE_FOLDER: .cache/Cypress

      - name: Fix Linting
        shell: bash
        run: pnpm -w run lint:fix

      - name: Sync `./src/config.type.ts` with `./src/schemas/config.schema.yaml`
        shell: bash
        run: pnpm run --filter mermaid types:build-config

      - name: Build Docs
        working-directory: ./packages/mermaid
        run: pnpm run docs:build

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # main
