import { describe, expect, it } from 'vitest';
import themes from './index.js';

type Variables = Record<string, unknown>;

const isObjectValued = (value: unknown): value is Variables =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const variablesOf = (theme: keyof typeof themes, overrides: Variables = {}): Variables => {
  const variables: unknown = themes[theme].getThemeVariables(overrides);
  return isObjectValued(variables) ? variables : {};
};

const nested = (variables: Variables, variable: string): Variables => {
  const value = variables[variable];
  return isObjectValued(value) ? value : {};
};

const themeNames = Object.keys(themes).filter((name): name is keyof typeof themes =>
  Object.hasOwn(themes, name)
);

const cases = themeNames.flatMap((theme) => {
  const generated = variablesOf(theme);
  return Object.keys(generated)
    .filter((variable) => Object.keys(nested(generated, variable)).length > 1)
    .map((variable) => ({ theme, variable, generated: nested(generated, variable) }));
});

describe('object-valued theme variables', () => {
  it('are generated by the themes', () => {
    expect(cases.map(({ variable }) => variable)).toContain('xyChart');
  });

  it.each(cases)(
    '$theme keeps the generated $variable keys a partial override leaves out',
    ({ theme, variable, generated }) => {
      const [first, ...rest] = Object.keys(generated);
      const overridden = nested(
        variablesOf(theme, { [variable]: { [first]: '#123456' } }),
        variable
      );

      expect(overridden[first]).toBe('#123456');
      for (const key of rest) {
        expect(overridden[key], key).toEqual(generated[key]);
      }
    }
  );

  it('keeps the dark xyChart palette when only the title colour is overridden', () => {
    const generated = nested(variablesOf('dark'), 'xyChart');
    const overridden = nested(
      variablesOf('dark', { xyChart: { titleColor: '#ff0000' } }),
      'xyChart'
    );

    expect(overridden).toEqual({ ...generated, titleColor: '#ff0000' });
  });

  it('still replaces a variable that is not an object', () => {
    expect(variablesOf('dark', { primaryColor: '#abcdef' }).primaryColor).toBe('#abcdef');
  });
});
