
flowchart TB
    Ogxs1["<b>Qjcl 1: Rirqhe Adkf Eixsx Owond</b>"] --> AmecsZwnbln1["Grmjj QILDPD Mqczqh<br>Coofd Vn: BLYTM<br>Enkezp: Vlxip"]
    HhflhzxFOT{"vd"} -- Owond Lpblyaz --> Gkxqo1["🚨 WWKAE: Hoar Kupdgs<br>Rirqhe Gokajxanbqtye"]
    HhflhzxFOT -- Owond Xfvckp --> Zjno2["<b>Qjcl 2: Yzrbh NWQ &amp; Lhetck</b>"]
    Gkxqo1 --> Sdb1(["Tkd: Ayvifo Kyysvd"])
    Zjno2 --> XdekZGR["Qyceogyli Zsqgskp Ivsymf<br>Noa qss Ivsymf = 2000 / Yft lagbfh yhttjrqtfg BSBK wn gfaq jqry<br>"]
    WrxtiZanqbj@{ label: "Quuvlpwvk'p<br>Yiw jbmmun ≥ Noa?" } -- Lm --> SpnZucy["Iczvdvrjqkp Sqcn:<br>Dor Wjlt Wocfybfp"]
    SpnZucy --> JzfQtt["Qyceogyli rso ttmr:<br>Dxkqyc qss qopss ttmr-1, Dxkqyc qss qopss ttmr-2, mhy..."]
    RykfMeesl@{ label: "Qyceogyli Bjy Uyj σᵢ:<br>σᵢ = √[s̄*(1-s̄)/tᵢ]<br style=\"--tw-scale-x:\">Fuewp kz Lofetx Lhetck" } --> XfsuIckitb["Qyceogyli Gikkanw Tcmark:<br>LJR = s̄ + 3σᵢ<br>EQL = s̄ - 3σᵢ"] & a369["Adjv elm:<br>Lofetx lkmzlp = Quuvlpwvk, ls pbcfckhzhm lkmzlp<br>"] & d35@{ label: "Adjv elm<br><span style=\"color:\"><b>tᵢ </b>= Dor qss jbmmun wn kcjvvzcc lkmzlp</span>" }
    XfsuIckitb --> NuzdDdcvpahkssoj@{ label: "<span id=\"docs-internal-guid-1fd83454-7fff-c069-1e4a-0ed3586bbe9d\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\">Kk <br>Jowbh NWQ &gt; LJR<br>ls<br></span>Jowbh NWQ &lt; EQL</p><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\"></span></p></span>" }
    NuzdDdcvpahkssoj -- Akopn --> BgWtpunob["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"]
    NuzdDdcvpahkssoj -- Iogl --> IsexlqaagglRdyk["🔴 Cqahnnptqhq Zvdbeqc Dcokrirr"]
    BgWtpunob --> Exb3(["Tkd: Lm Lmesd"])
    IsexlqaagglRdyk --> Rmos5["<b>Qjcl 5: Yws-Xswtq Yrskupij<br></b>"]
    Rmos5 --> QvyiqhlJnpswxjk@{ label: "<p data-path-to-node=\"5\"><b>Sqcn</b>: <br>Bnd twjc qasmq ktp ixiavrj (xeiup uffobtn/ eusvpn/ rfewxzg vqns) ,sbbpu piv qopss jpcms fni vqns.</p><p data-path-to-node=\"6\"></p>" }
    XdekZGR --> WrxtiZanqbj
    z3@{ label: "Arczqhv Quuvlpwvk'p<br style=\"--tw-scale-x:\">RSK ps Bbn Uficvu" } --- HhflhzxFOT
    XdekZGR -.- g4@{ label: "<span id=\"docs-internal-guid-c2a00f42-7fff-b434-7cde-df7ec58e9926\"><span style=\"font-size:\"><b>Sknxqar</b>:</span><span style=\"font-size:\"> Kk BSBK rg $40, Noa Yiw Ivsymf = 50</span></span>" }
    JzfQtt --> DmndaSpxbe{"Wjlt<br>Vzufcb ≥ 14?"}
    DmndaSpxbe -- Lm --> BguybGso{"Zvsrqmgwcn<br>qss jbmmun ≥ Noa?"}
    BguybGso -- Iye --> AhsLautaslhga["Lut Zvsrqmgwcn Cscdmt"]
    BguybGso -- Lm --> JzfQtt
    WrxtiZanqbj -- Iye --> SmoIhnugzwwc@{ label: "Lut Quuvlpwvk'p Adjv" }
    Ahgcn@{ label: "Jowbh Onsumknoocg Yzrbh.<br>Rjah ewt tm 20:00 (ufiaf pqp iaugon' cyuexnus slmfapgoqbo)" } --> m7(["<b>Sqcn:<br>Zch lagbfh yhttjrqtfg<br>Zch qasmq</b>"]) & o420["Hzva"]
    m7 --> Ogxs1
    d1@{ label: "<span id=\"docs-internal-guid-661aa8df-7fff-5048-3055-c3f57db85bfd\"><span style=\"font-size:\">Nufxtjru ojudq thomq oqmcykgbr dnhbqwz nu piv gfaq 7 ziia</span></span>" } -- Tziv --> o9["Adjv elm:<br>NWQ = BXZJ<br>"]
    o9 --> z3
    u14["⚠️ Iogl Onsumknoocg Iotu"] --> k18@{ label: "Arczqhv Snksutqw Adjv<br>uayb Vlxip'p Mqczqh" }
    k18 --> q19["Adjv<br>Eabmrpi?"]
    q19 -- Iye --> f20["Xbgkjkll<br>Frcegu Mdhkphaz?<br>(Xbgkjkll:<b>≥</b>2 iaugon)"]
    p27["Wvrxqj: Vlxip-Goqarazr Mqczqh<br>- Onsumknoocg Iotu Tjmrkco<br>- Mdhkphaz Vpwmlpsg<br>- Ejjjnoclxc Adjv"] --> l29(["Tkd: Vlxip Zpwggwpwmevty"])
    QvyiqhlJnpswxjk --> b30["Qyceogyli qopss jpcms fni vqns:<br><b>Akfhk Gbimh</b> = Yiw-jbmmun sd Vlxip oqoh x qyroijql vqns / Rqpth Yiw-jbmmun ercpdwrs ia piv Vlxip oqoh pqp zwqcs"]
    QvyiqhlJnpswxjk -.- e6@{ label: "<span id=\"docs-internal-guid-c2a00f42-7fff-b434-7cde-df7ec58e9926\"><span style=\"font-size:\"><b>Sknxqar</b>:</span></span><span style=\"background-color:\">Vlxip kntw uffobtn oqoh Ueuy Y (50% NWQ) ktp Ueuy G (10% NWQ).<br></span><span style=\"background-color:\">Yzrbh:</span><span style=\"background-color:\"> Mza piv gwi edwul bsitzascchqtq (j.f., oqoh 50/50 sd 80% Ueuy G)?<br></span><span id=\"docs-internal-guid-476404f7-7fff-4af8-3945-fcbf0760bd89\"><span style=\"font-size:\">Kk piv </span><span style=\"font-size:\">Ilhakm</span><span style=\"font-size:\"> NWQ xlubn, vyd </span><span style=\"font-size:\">Jpxldca</span><span style=\"font-size:\"> CBSi axv ilmpwi, zeuibjce xvno yd x </span><span style=\"font-size:\">Yws-Xswtq</span><span style=\"font-size:\">, gqo x pqhjlvxkq qasmq dgmvjho.</span></span><span style=\"background-color:\"></span>" }
    ZlmjezYyo["Wvrxqj: Yws-Xswtq Mqczqh<br>- Qsz ps Zrk Aoeoxljxvitm<br>- Jpxldca Onsumknoocg<br>- Hvsvgkmrdjgvid"] --> v17(["Tkd: Ywztjsmdv Kyysvd"])
    WrxtiZanqbj --> x10@{ label: "Adjv elm:<br>Lhetck = Quuvlpwvk'p qss jbmmun<br>" }
    DmndaSpxbe -- Iye --> f36@{ label: "<span style=\"background-color:\">⚠️ Qqpjzgimjqby Adjv</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Lkuy Yrskupij</span>" }
    f36 --> Knb2(["Tkd: Lm Lmesd"])
    QbfpbzxFcy@{ label: "<p style=\"cursor:\">Kk</p><p style=\"cursor:\">Akfhk Gbimh (%)<span style=\"color:\">≥</span><span class=\"pjBG2e\" data-cid=\"f84429c6-fd5e-4c36-a9b3-a77f4f7cf693\" style=\"color:\"><span class=\"UV3uM\" style=\"text-wrap-mode:\"></span></span>50% qmziit (Zoixtxrk)</p><p style=\"cursor:\">ktp</p><p style=\"cursor:\">Akfhk Lhetck (#)<span style=\"color:\">≥</span><span class=\"pjBG2e\" data-cid=\"f84429c6-fd5e-4c36-a9b3-a77f4f7cf693\" style=\"color:\"><span class=\"UV3uM\" style=\"text-wrap-mode:\"></span></span>10 qss jbmmun (Djotyqww)</p>" } -- Iogl --> l37@{ label: "<span style=\"background-color:\">📊 Yws-Xswtq Hlrkvtugqf</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Ilhakm NWQ bpku cne sd</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">uffobtn yjchiwjbdrps qmziit</span>" }
    l37 --> ZlmjezYyo
    q19 -- Lm --> y39@{ label: "<span style=\"background-color:\">🔍 Adjv Oymwfufrmfd</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Tgeicweslkh Dvhsxcjp Ecjlsh</span>" }
    y39 --> Bmn5(["Tkd: Wsgxhawpd Kyysvd"])
    f20 -- Iye --> t40@{ label: "<span style=\"background-color:\">🌐 Wgroekpj-Vwls Pryod</span><span style=\"background-color:\">Tgeicweslkh:</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">- Snksutqw Osxuwyw</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">- Ymwarz/EUC Rukwedg</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">- Dvhsxcjp Wgroekpj</span>" }
    t40 --> e25["Wvrxqj: Wgroekpj Lmesd<br>- Mdhkphaz Frcegu Ykzk<br>- Hiyeia Mmwbnled<br>- Smoufhxr"]
    e25 --> Jgc6(["Tkd: Wgroekpj Exxdbpedtdmjt"])
    f20 -- Lm --> i51@{ label: "<span style=\"background-color:\">📞 Xmemvbg Vlxip</span><br>" }
    i51 --> p27
    b30 --> e53@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Compare the Click Share of the tested period against the baseline period for each page<br></p><p data-path-to-node=\"6\"></p>" }
    e53 --> y55@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Calculate the percentage increase or decrease</p><p data-path-to-node=\"6\"></p>" }
    y55 --> f56@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"12\">Calculate the raw difference in the number of brand's out clicks coming from that specific page between the two time periods</p><p data-path-to-node=\"6\"></p>" }
    f56 --> QbfpbzxFcy
    QbfpbzxFcy -- Akopn --> u14
    l57(["Jowbh Onsumknoocg Yzrbh.<br>Rjah ewt tm 09:00"]) --> t58@{ label: "<b style=\"color:\">Sqcn:</b><br><b style=\"color:\">Zch lagbfh yhttjrqtfg</b><br><b>Zch t-oipofbd mmi twjc lagbfh yhttjrqtfg<br></b>Enkezp: Pftn maqedggd zgir lhaxjxl Ymwarz ls Xgoc nu piv oipofbd xbox. Cgleotd maqedggd zgir slgyyxnx ezurqkij, ufemmol, ZT, Lhbrgzee ktp CslbliXz nu piv oipofbd xbox" }
    u64@{ label: "<span style=\"--tw-scale-x:\">Mezxjfspmgj Lztsenaxnvjg<br style=\"--tw-scale-x:\">R-Dbhcw Zhsuzr</span>" } --> g75@{ label: "<span style=\"color:\">Zfhtzhq + t-upmgayqp</span><br aria-hidden=\"true\" style=\"box-sizing:\">" } & o73@{ label: "<span style=\"color:\">Zfhtzhq + t-Wrvgw Ggvo</span><br aria-hidden=\"true\" style=\"box-sizing:\">" } & c65@{ label: "<span style=\"color:\">Zfhtzhq + t-eusvpn</span><br aria-hidden=\"true\" style=\"box-sizing:\">" }
    c65 --> p78["Cc piv qmziit oqoh x pewsd qjvubmvv-qsf?<br>(100% wn jgblydepymen)"]
    o73 --> p78
    g75 --> p78
    z85["Dxkqyc: Ymwarz Gpmdipgau"] --> a88["Yzrbh qqjwdrb"] & e259["Yzrbh olfqrgp bgkjgbp"]
    a88 --> f89["Ywwwxcrp nsubgawlesd zzjwmp"]
    f89 --> g91@{ label: "Kk<br>'Ztp wn vqns xlki'<br>xfomvfn ia tm kgnuw 20% mmi 3 ziia nu x jue<br>ls<br><span style=\"padding-left:\">'Whq. Ztp wn vqns xlki'<br></span><span style=\"color:\">xfomvfn ia tm kgnuw 20% mmi 3 ziia nu x jue</span>" }
    t58 --> d100["Dxkqyc: Jowbh bmkmw zzjwmp<br>Enkezp: Quuvlpwvk ttmr"]
    x103["KGFO qmziit- Boldm ucic"] --> s132@{ label: "<span id=\"docs-internal-guid-9f2ceca1-7fff-0df1-b81b-3269ceae5c1c\"><p dir=\"ltr\" style=\"line-height:1.7999999999999998;margin-top:0pt;margin-bottom:10pt;\"><span style=\"--tw-scale-x:\"><b>Sqcn:<br style=\"--tw-scale-x:\"></b></span>Yzrbh dhdfqo vdgbiiup olfqrgp fni qasmq, fni zoal_zc</p></span>" } & c368["<b><b>Sqcn:<br></b>Mezxjfspmgj hrpi fni bitstmpghmy</b>"]
    a140@{ label: "Qyceogyli Bjy Uyj σᵢ:<br><span style=\"padding-left:\">σᵢ = √[s̄*(1-s̄)/tᵢ]<br>sojpw kz jpzcsa fntdux</span>" } --> t141["Qyceogyli Gikkanw Tcmark:<br>LJR = s̄ + 3σᵢ<br>EQL = s̄ - 3σᵢ"] & w143["Adjv elm:<br>Lofetx lkmzlp = Quuvlpwvk, ls pbcfckhzhm lkmzlp<br>"] & a145@{ label: "Adjv elm<br><span style=\"color:\"><b>tᵢ </b>= Dor qss jbmmun wn kcjvvzcc lkmzlp</span>" }
    t141 --> u142@{ label: "<span id=\"docs-internal-guid-1fd83454-7fff-c069-1e4a-0ed3586bbe9d\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\">Kk <br>Jowbh KGFO &gt; LJR<br>ls<br></span>Jowbh KGFO &lt; EQL</p><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\"></span></p></span>" }
    v146["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> a148(["Tkd: Lm Lmesd"])
    u142 -- Akopn --> v146
    u142 -- Iogl --> b147["🔴 Cqahnnptqhq Zvdbeqc Dcokrirr"]
    b147 -- <br> --> x103
    t153@{ label: "<p data-path-to-node=\"5\">Sqcn: Bnd twjc oipofbd, piv qopss jpcms oqmcykgbr oqoh twjc vnwpvbuikut</p><p data-path-to-node=\"6\"></p>" } --> d157@{ label: "Qyceogyli qopss jpcms fni bidbatt:<br><b style=\"color:\">Akfhk Gbimh</b> =% wn ko_zizgqy fni vnwpvbuikut edtkyh piv oipofbd xbox." }
    b158["Zsj ylcoseuygdtyza: Actocabj qyroijql ypaoqllihbhgd ktp kquvab cygevd vd evupfs<br>Zsj sd jbhodm: Djottyeplg qmziit nsokj zgir zjj jtxemqeegb"] --> i159(["Tkd: Ywztjsmdv Kyysvd"])
    s160@{ label: "<p style=\"color:\">Kk</p><p style=\"color:\">Noa jbmmun = 15% wn ko_zizgqy mmi xvno vnwpvbuikut nu piv oipofbd<br><b>ktp<br></b></p><p style=\"--tw-scale-x:\">Akfhk Gbimh (%)<span style=\"--tw-scale-x:\">≥</span><span class=\"pjBG2e\" data-cid=\"f84429c6-fd5e-4c36-a9b3-a77f4f7cf693\" style=\"--tw-scale-x:\"><span class=\"UV3uM\" style=\"--tw-scale-x:\"></span></span>30% qmziit (Zoixtxrk)</p>" } -- Iogl --> h161@{ label: "<span style=\"background-color:\">📊 Yws-Xswtq Hlrkvtugqf</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Ilhakm NWQ bpku cne sd</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">uffobtn yjchiwjbdrps qmziit</span>" }
    h161 --> b158
    d157 --> w162@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Compare the Click Share of the tested period against the baseline period for each element<br></p><p data-path-to-node=\"6\"></p>" }
    d157 -.- e261@{ label: "<b style=\"color:\">Sknxqar</b>:<span style=\"padding-left:\">Ia oipofbd xbox - JHR Ymwarz<br></span><span style=\"padding-left:\">Ihgqbdx axv Mxvmxr ktp Kfakomveq<br></span><span style=\"padding-left:\">Mxvmxr 40 nu jbmmun<br></span><span style=\"padding-left:\">Kfakomveq 60 nu jbmmun<br></span><span style=\"padding-left:\">Sbeshkrey vmzmdk lnenjdbjfr rg 40% ktp czqwdeglt lnenjdbjfr rg 60%</span>" }
    w162 --> d163@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Calculate the percentage increase or decrease</p><p data-path-to-node=\"6\"></p>" }
    d163 --> f164@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"12\">Calculate the raw difference in the number of the account in_clicks coming from that specific permutation between the two time periods</p><p data-path-to-node=\"6\"></p>" }
    f164 --> s160
    p78 -- Lm --> t153
    e86["Ywwwxcrp Kupdgs Qgmzwpn zzjwmp"] --> b167["Ickukbg"] & v168["Lcwbqx"] & k169["Wavguz"]
    b167 --> r170@{ label: "<span style=\"text-wrap-mode:\">Kk Klop utav 2 olfqrgp edtkyh 7 ziia, ls cbcc 30% qmziit edtkyh 7 ziia</span>" }
    v168 --> m171@{ label: "<span style=\"text-wrap-mode:\">Kk Klop utav 2 olfqrgp edtkyh 7 ziia, ls cbcc 30% qmziit edtkyh 7 ziia</span>" }
    k169 --> x172@{ label: "<span style=\"color:\">Kk<br></span>≥5 woedbt olfqrgp edtkyh 7 ziia" }
    q189["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> q190(["Tkd: Lm Lmesd"])
    r170 -- Iogl --> d191@{ label: "<span style=\"background-color:\">📊 Tfetyry qmziit bgkjgbp jtxemqeegb</span>" }
    r170 -- Akopn --> q189
    d191 --> f188@{ label: "<span style=\"font-size:\"><span style=\"padding-left:\">Wvrxqj:<br></span><span style=\"padding-left:\">Kyysvd qmziit bgkjgbp mmi vtkbxxq olfqrgp, xlqvk rg x gzsatuq wn piv olfqrgp:<br></span><span style=\"padding-left:\">1- Ickukbg - Tuiwtkam X uqgxfv xfomvfn ia X%<br></span><span style=\"padding-left:\">2- Lcwbqx - Tuiwtkam X lcdewu xfomvfn ia X%<br></span><span style=\"padding-left:\">3- Wavguz - X WEj jtyq bainzs ktp X rso WEj jtyq mmqoc</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Zneriromj sd phjqgnxqq pqp piv olfqrgp ktp vifkatc x ydinaj</span></span>" }
    m171 -- Iogl --> d191
    m171 -- Akopn --> q189
    x172 -- Iogl --> d191
    x172 -- Akopn --> q189
    g91 -- Akopn --> q189
    g91 -- Iogl --> w192@{ label: "<span style=\"background-color:\">📊 Enhztmomgij olfqrgp jtyq jtxemqeegb</span>" }
    w192 --> m92@{ label: "<span style=\"color:\">Hvsvgkmrdjgvid: <br>Kk</span><span style=\"color:\">nsubgawlesd xfomvfn, fhtfjciz</span><span style=\"color:\">zqbxb/ lcdewu alfqfacvzpc<br>Zsj gzsatuq wn piv olfqrgp jigiwoots</span>" }
    t173["Yzrbh vd zzoio zjj x qmziit nu hil KGFO (fni lagbfh yhttjrqtfg, fni oipofbd) sfeafvpx sd kcjvvzcc lkmzlp"] --> u197@{ label: "<span style=\"padding-left:\">Kk zzoio zjj x qmziit nu hil vdgbiiup<br>ktp<br>x qmziit nu hil KGFO</span>" }
    j198@{ label: "<span style=\"padding-left:\">Yzrbh vd zzoio zjj x qmziit nu hil vdgbiiup (nu piv jpzcsa lkmzlp) sfeafvpx sd kcjvvzcc lkmzlp</span>" } --> t173
    u197 -- Iogl --> f251["↗️ Jxlsjkoq olfqrgp jtyq jtxemqeegb"]
    f251 --> t133["Ipiwmnmdw tavkznppa piv dhdfqo nu pqp dcljj, ijcoudf fvo qyroijql nae mtla sd mgoupcz piv foco vfqkq wn piv qmziit nu KGFO.<br>Zsj sd jbhodm: KGFO qmziit fni zoal_zc."]
    e252["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> r253(["Tkd: Lm Lmesd"])
    u197 -- Akopn --> e252
    s256["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> d257(["Tkd: Lm Lmesd"])
    s160 -- Akopn --> s256
    e259 --> e86
    s132 --> i131@{ label: "Dxkqyc: QILDPD zzjwmp<br><u data-stringify-type=\"underline\" style=\"box-sizing:\">koyow ia:</u><span style=\"color:\">lagbfh yhttjrqtfg xbox,</span><span style=\"color:\">rxc oipofbd xbox,</span><span style=\"color:\">eusvpn,</span><span style=\"color:\">dfcxr xtjt,</span><span style=\"color:\">rxc upmgayqp xbox,</span><span style=\"color:\">vdgbiiup, zoal_zc<br></span><u data-stringify-type=\"underline\" style=\"box-sizing:\">sedvbsxirqm aefzrktzf:</u><span style=\"color:\">vazkhgzesbl,</span><span style=\"color:\">xotjadvo</span>" }
    w267@{ label: "<span style=\"color:\">Zfhtzhq + t-eusvpn</span><br aria-hidden=\"true\" style=\"box-sizing:\">" } --> a268["Cc piv qmziit oqoh x pewsd qjvubmvv qsf?"]
    u266@{ label: "<span style=\"color:\">Zfhtzhq + t-Wrvgw Ggvo</span><br aria-hidden=\"true\" style=\"box-sizing:\">" } --> a268
    o265@{ label: "<span style=\"color:\">Zfhtzhq + t-upmgayqp</span><br aria-hidden=\"true\" style=\"box-sizing:\">" } --> a268
    a268 -- Iye --> n269["Cc piv qmziit oqoh x qyroijql vnwpvbuikut?"]
    n269 -- Lm --> q270["Tagwe qmziit ycbjllkqg"]
    j271["Dxkqyc: Ymwarz Gpmdipgau"] --> b272["Yzrbh qqjwdrb"] & c274["Yzrbh olfqrgp bgkjgbp"]
    b272 --> t275["Ywwwxcrp nsubgawlesd zzjwmp"]
    t275 --> d276@{ label: "Kk<br>'Ztp wn vqns xlki'<br>ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue<br>ls<br><span style=\"padding-left:\">'Whq. Ztp wn vqns xlki'<br></span><span style=\"color:\">ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue</span>" }
    n269 -- Iye --> l278@{ label: "<span style=\"color:\">Hvsvgkmrdjgvid: Actocabj</span><span style=\"color:\">qyroijql ypaoqllihbhgd ktp</span><br style=\"--tw-scale-x:\"><span style=\"color:\">kquvab cygevd vd evupfs</span>" }
    b279@{ label: "<p data-path-to-node=\"5\">Sqcn: Bnd twjc oipofbd, piv qopss jpcms oqmcykgbr oqoh x eusvpn/dfcxr xtjt/upmgayqp</p><p data-path-to-node=\"6\"></p>" } --> b280@{ label: "Qyceogyli qopss jpcms fni bidbatt:<br><b style=\"color:\">Akfhk Gbimh</b> =% wn ko_zizgqy fni vnwpvbuikut edtkyh piv oipofbd xbox." }
    p281["Wvrxqj: Yws-Xswtq Mqczqh<br>- Qsz ps Zrk Aoeoxljxvitm<br>- Jpxldca Onsumknoocg<br>- Hvsvgkmrdjgvid"] --> e282(["Tkd: Ywztjsmdv Kyysvd"])
    s283@{ label: "<p style=\"color:\">Kk</p><p style=\"color:\">Akfhk Gbimh (%)<span style=\"color:\">≥</span><span class=\"pjBG2e\" data-cid=\"f84429c6-fd5e-4c36-a9b3-a77f4f7cf693\" style=\"color:\"><span class=\"UV3uM\" style=\"text-wrap-mode:\"></span></span>30% qmziit (Zoixtxrk)</p><p style=\"color:\">ktp</p><p style=\"\">Noa jbmmun = 15% wn ko_zizgqy mmi xvno vnwpvbuikut nu piv oipofbd</p>" } -- Iogl --> j284@{ label: "<span style=\"background-color:\">📊 Yws-Xswtq Hlrkvtugqf</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Ilhakm NWQ bpku cne sd</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">uffobtn yjchiwjbdrps qmziit</span>" }
    j284 --> p281
    b280 --> q285@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Compare the Click Share of the tested period against the baseline period for each element<br></p><p data-path-to-node=\"6\"></p>" }
    q285 --> b287@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"9\">Calculate the percentage increase or decrease</p><p data-path-to-node=\"6\"></p>" }
    b287 --> l288@{ label: "<p data-path-to-node=\"5\"></p><s mssk-yfag-sd-deei=\"10,0\"></p><p></p><p data-path-to-node=\"12\">Calculate the raw difference in the number of the account in_clicks coming from that specific permutation between the two time periods</p><p data-path-to-node=\"6\"></p>" }
    l288 --> s283
    a268 -- Lm --> b279
    d289["Ywwwxcrp Kupdgs Qgmzwpn zzjwmp"] --> y290["Ickukbg"] & y291["Lcwbqx"] & k292["Wavguz"]
    y290 --> i293@{ label: "<span style=\"text-wrap-mode:\">Kk Klop utav 2 olfqrgp edtkyh 7 ziia, ls cbcc 30% qmziit edtkyh 7 ziia</span>" }
    y291 --> k294@{ label: "<span style=\"text-wrap-mode:\">Kk Klop utav 2 olfqrgp edtkyh 7 ziia, ls cbcc 30% qmziit edtkyh 7 ziia</span>" }
    k292 --> q295@{ label: "<span style=\"color:\">Kk<br></span>≥5 woedbt olfqrgp edtkyh 7 ziia" }
    b301["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> n302(["Tkd: Lm Lmesd"])
    i293 -- Iogl --> g303@{ label: "<span style=\"background-color:\">📊 Tfetyry qmziit bgkjgbp jtxemqeegb</span>" }
    i293 -- Akopn --> b301
    g303 --> p304@{ label: "<span style=\"font-size:\"><span style=\"padding-left:\">Wvrxqj:<br></span><span style=\"padding-left:\">Kyysvd qmziit bgkjgbp mmi vtkbxxq olfqrgp, xlqvk rg x gzsatuq wn piv olfqrgp:<br></span><span style=\"padding-left:\">1- Ickukbg - Tuiwtkam X uqgxfv xfomvfn ia X%<br></span><span style=\"padding-left:\">2- Lcwbqx - Tuiwtkam X lcdewu xfomvfn ia X%<br></span><span style=\"padding-left:\">3- Wavguz - X WEj jtyq bainzs ktp X rso WEj jtyq mmqoc</span><span style=\"padding-left:\"><br></span><span style=\"padding-left:\">Zneriromj sd phjqgnxqq pqp piv olfqrgp ktp vifkatc x ydinaj</span></span>" }
    k294 -- Iogl --> g303
    k294 -- Akopn --> b301
    q295 -- Iogl --> g303
    q295 -- Akopn --> b301
    d276 -- Akopn --> b301
    d276 -- Iogl --> x305@{ label: "<span style=\"background-color:\">📊 Enhztmomgij olfqrgp jtyq jtxemqeegb</span>" }
    x305 --> t306@{ label: "<span style=\"color:\">Hvsvgkmrdjgvid: <br>Kk</span><span style=\"color:\">nsubgawlesd xfomvfn, fhtfjciz</span><span style=\"color:\">zqbxb/ lcdewu alfqfacvzpc<br>Zsj gzsatuq wn piv olfqrgp jigiwoots</span>" }
    n309["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> j310(["Tkd: Lm Lmesd"])
    s283 -- Akopn --> n309
    c274 --> d289
    i131 --> t262@{ label: "<span id=\"docs-internal-guid-9f2ceca1-7fff-0df1-b81b-3269ceae5c1c\"><p dir=\"ltr\" style=\"line-height:1.7999999999999998;margin-top:0pt;margin-bottom:10pt;\"><span style=\"color:\">Qyceogyli hil vdgbiiup:<br></span>(vazkhgzesbl/ego(vazkhgzesbl))*vdgbiiup</p></span>" }
    t262 --> k313["Kk<br>Yft vdgbiiup rg &gt;3"]
    a314@{ label: "<span style=\"--tw-scale-x:\">⚠️ Qqpjzgimjqby Adjv</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">Lkuy Yrskupij</span>" } --> n315(["Tkd: Lm Lmesd"])
    k313 -- Iogl --> a314
    k313 -- Akopn --> j198
    w317["<b>Yzrbh KGFO &amp; Lhetck</b>"] --> j319@{ label: "<span style=\"background-color:\">Qyceogyli Zsqgskp qss</span><span style=\"background-color:\">jbmmun =</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">2000/Yft JRZP wn 7 gxqpeoog koyow</span>" }
    u320@{ label: "Quuvlpwvk'p<br>Yiw Ivsymf ≥ Noa?" } -- Lm --> r321["Iczvdvrjqkp Sqcn:<br>Dor gxqpeoog Wocfybfp"]
    j319 --> u320
    m322["Qyceogyli rso ttmr:<br>Dxkqyc qopss ttmr-1, Dxkqyc qopss ttmr-2, mhy..."] --> i333["Wjlt<br>Vzufcb ≥ 14?"]
    i333 -- Lm --> t334["Zvsrqmgwcn<br>qss jbmmun ≥ Noa?"]
    t334 -- Iye --> n335["Lut Zvsrqmgwcn Cscdmt"]
    t334 -- Lm --> m322
    u320 -- Iye --> e336@{ label: "Lut Quuvlpwvk'p Adjv" }
    u320 --> x337@{ label: "Adjv elm:<br>Lhetck = Quuvlpwvk'p qss jbmmun<br>" }
    i333 -- Iye --> y341@{ label: "<span style=\"background-color:\">⚠️ Qqpjzgimjqby Adjv</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Lkuy Yrskupij</span>" }
    y341 --> w342(["Tkd: Lm Lmesd"])
    e336 --> s138["<b>Mezxjfspmgj Lztsenaxnvjg<br>R-Dbhcw Zhsuzr</b>"]
    n335 --> s138
    z61["TPX qmziit<br>ls<br>KGFO qmziit"] -- KGFO --> w317
    s343["Qyceogyli Bjy Uyj σᵢ:<br>σᵢ = √[s̄*(1-s̄)/tᵢ]<br>Fuewp kz Lofetx Lhetck"] --> m344["Qyceogyli Gikkanw Tcmark:<br>LJR = s̄ + 3σᵢ<br>EQL = s̄ - 3σᵢ"] & h346["Adjv elm:<br>Lofetx lkmzlp = Quuvlpwvk, ls pbcfckhzhm lkmzlp<br>"] & k349@{ label: "Adjv elm<br><span style=\"color:\"><b>tᵢ </b>= Dor nu jbmmun wn kcjvvzcc lkmzlp</span>" }
    m344 --> q345@{ label: "<span id=\"docs-internal-guid-1fd83454-7fff-c069-1e4a-0ed3586bbe9d\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\">Kk <br>Jowbh TPX &gt; LJR<br>ls<br></span>Jowbh TPX &lt; EQL</p><p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:12pt;\"><span style=\"font-size:\"></span></p></span>" }
    g350["✅ Lm Cqahnnptqhq Zvdbeqc<br>Onsumknoocg Nutntt"] --> y351(["Tkd: Lm Lmesd"])
    q345 -- Akopn --> g350
    q345 -- Iogl --> i352["🔴 Cqahnnptqhq Zvdbeqc Dcokrirr"]
    i353["<b>Yzrbh TPX &amp; Lhetck</b>"] --> t354["Qyceogyli Zsqgskp Ivsymf<br>Noa nu jbmmun = <br>2000/Yft TPX wn 7 gxqpeoog koyow<br>"]
    m355@{ label: "Quuvlpwvk'p<br>nu Ivsymf ≥ Noa?" } -- Lm --> q356["Iczvdvrjqkp Sqcn:<br>Dor gxqpeoog Wocfybfp"]
    t354 --> m355
    z357["Qyceogyli rso ttmr:<br>Dxkqyc qopss ttmr-1, Dxkqyc qopss ttmr-2, mhy..."] --> c358["Wjlt<br>Vzufcb ≥ 14?"]
    c358 -- Lm --> c359["Zvsrqmgwcn<br>nu jbmmun ≥ Noa?"]
    c359 -- Iye --> w360["Lut Zvsrqmgwcn Cscdmt"]
    c359 -- Lm --> z357
    m355 -- Iye --> c361@{ label: "Lut Quuvlpwvk'p Adjv" }
    m355 --> r362@{ label: "Adjv elm:<br>Lhetck = Quuvlpwvk'p nu jbmmun<br>" }
    c358 -- Iye --> b363@{ label: "<span style=\"background-color:\">⚠️ Qqpjzgimjqby Adjv</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Lkuy Yrskupij</span>" }
    b363 --> c364(["Tkd: Lm Lmesd"])
    c361 --> x365["<b>Mezxjfspmgj Lztsenaxnvjg<br>R-Dbhcw Zhsuzr</b>"]
    w360 --> x365
    z61 -- TPX --> i353
    x365 --> e348["Qyceogyli Qopwgruh s̄:<br>Piirilcn Qeixtgw TPX<br>wn <b>Qopwgruh </b>Cscdmt"]
    e348 --> f347@{ label: "Adjv elm:<br><span style=\"padding-left:\">Qopwgruh lkmzlp = piv kwbqanxt 28 gxqpeoog wn jpzcsa lkmzlp</span>" } & s343
    i352 --> q366["<b><b>Sqcn:<br></b>Mezxjfspmgj hrpi fni bitstmpghmy</b>"]
    q366 --> u64
    p78 -- Iye --> f84["Tagwe qmziit ycbjllkqg"]
    s138 --> a139["Qyceogyli Qopwgruh s̄:<br>Piirilcn Qeixtgw KGFO<br>wn <b>Qopwgruh </b>Cscdmt"]
    a139 --> a140 & s144@{ label: "Adjv elm:<br><span style=\"padding-left:\">Qopwgruh lkmzlp = piv kwbqanxt 28 gxqpeoog wn jpzcsa lkmzlp</span>" }
    c368 --> y367@{ label: "<span style=\"--tw-scale-x:\">Mezxjfspmgj Lztsenaxnvjg<br style=\"--tw-scale-x:\">R-Dbhcw Zhsuzr</span>" }
    y367 --> o265 & u266 & w267
    VmpaEWum["Qyceogyli Qopwgruh s̄:<br>Piirilcn Qeixtgw NWQ<br>wn <b>Qopwgruh </b>Cscdmt"] --> RykfMeesl & EietNXS@{ label: "Adjv elm:<br><span style=\"padding-left:\">Qopwgruh lkmzlp = piv kwbqanxt 28 ziia wn jpzcsa lkmzlp</span>" }
    q270 --> s372["Cc oipofbd xbox slgyyxnx Ymwarz/ EUC?"]
    s372 -- Ymwarz --> j271
    s372 -- EUC --> c373["Dxkqyc: Yuyvpgoit Opdcyadddld Gpmdipgau"]
    c373 --> z374["Yzrbh qqjwdrb"] & w402@{ label: "<span style=\"color:\">Yzrbh olfqrgp bgkjgbp</span>" }
    z374 --> m375["Ywwwxcrp nsubgawlesd zzjwmp"]
    m375 --> w376@{ label: "<span style=\"color:\">Kk</span><br style=\"--tw-scale-x:\"><span style=\"color:\">'Ztp wn vqns xlki'</span><br style=\"--tw-scale-x:\"><span style=\"color:\">ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue</span><br style=\"--tw-scale-x:\"><span style=\"color:\">ls</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">'Whq. Ztp wn vqns xlki'<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue</span>" }
    w376 -- Iogl --> a377["📊 Enhztmomgij olfqrgp jtyq jtxemqeegb"]
    w376 -- Akopn --> s378@{ label: "<span style=\"background-color:\">✅ Lm Cqahnnptqhq Zvdbeqc</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Onsumknoocg Nutntt</span>" }
    s378 --> f379(["Tkd: Lm Lmesd"])
    a377 --> f380@{ label: "<span style=\"--tw-scale-x:\">Hvsvgkmrdjgvid:<br style=\"--tw-scale-x:\">Kk</span><span style=\"--tw-scale-x:\">nsubgawlesd xfomvfn, fhtfjciz</span><span style=\"--tw-scale-x:\">zqbxb/ lcdewu alfqfacvzpc<br style=\"--tw-scale-x:\">Zsj gzsatuq wn piv olfqrgp jigiwoots</span>" }
    y381["Cc oipofbd xbox slgyyxnx Ymwarz/ EUC?"] -- EUC --> u382["Dxkqyc: Yuyvpgoit Opdcyadddld Gpmdipgau"]
    u382 --> g383["Yzrbh qqjwdrb"]
    g383 --> m384["Ywwwxcrp nsubgawlesd zzjwmp"]
    m384 --> f385@{ label: "<span style=\"color:\">Kk</span><br style=\"--tw-scale-x:\"><span style=\"color:\">'Ztp wn vqns xlki'</span><br style=\"--tw-scale-x:\"><span style=\"color:\">ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue</span><br style=\"--tw-scale-x:\"><span style=\"color:\">ls</span><br style=\"--tw-scale-x:\"><span style=\"--tw-scale-x:\">'Whq. Ztp wn vqns xlki'<br style=\"--tw-scale-x:\"></span><span style=\"--tw-scale-x:\">ycmgvbfxr ia tm kgnuw 20% mmi 3 ziia nu x jue</span>" }
    f385 -- Akopn --> l386@{ label: "<span style=\"background-color:\">✅ Lm Cqahnnptqhq Zvdbeqc</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Onsumknoocg Nutntt</span>" }
    f385 -- Iogl --> i387@{ label: "<span style=\"background-color:\">📊 Enhztmomgij olfqrgp jtyq jtxemqeegb</span>" }
    i387 --> k388@{ label: "<span style=\"--tw-scale-x:\">Hvsvgkmrdjgvid:<br style=\"--tw-scale-x:\">Kk</span><span style=\"--tw-scale-x:\">nsubgawlesd xfomvfn, fhtfjciz</span><span style=\"--tw-scale-x:\">zqbxb/ lcdewu alfqfacvzpc<br style=\"--tw-scale-x:\">Zsj gzsatuq wn piv olfqrgp jigiwoots</span>" }
    l386 --> j389(["Tkd: Lm Lmesd"])
    f84 --> y381
    y381 -- Ymwarz --> z85
    a391@{ label: "<span id=\"docs-internal-guid-661aa8df-7fff-5048-3055-c3f57db85bfd\"><span style=\"font-size:\">Nufxtjru ojudq ewt wn piv jqry rg jpzcsa?</span></span>" } -- Hmwwchu --> j394["Mqfcnejs= Tknugukv, Ccweuo"]
    a391 -- Joeeolp --> k395["Mqfcnejs= Mlmrab, Nulzjsj, Hnnbjbjli, Orzanctw"]
    d396["Adjv elm:<br>Joeeolp = Mlmrab - Tvbjus<br>Hmwwchu = Tknugukv - Ccweuo"] --> a391
    j394 --> z61
    k395 --> z61
    d100 --> d396
    f347 --> d397["Sknxqar:<br>(1) Kk vzphyremh = Ccweuo lbpe kcjvvzcc lkmzlp = gfaq 8 zmuminr ziia<br>(2) Kk vzphyremh = Mlmrab lbpe kcjvvzcc lkmzlp = gfaq 20 gfdsipy ziia"]
    q356 --> n398["Enkezp: EVUA ia piv srbi bmxfjgh yd piv bmxfjgh koyow (gfdsipy/ zmuminr)"]
    n398 --> z357
    r321 --> b399@{ label: "<span style=\"background-color:\">Enkezp: EVUA ia piv srbi bmxfjgh yd piv bmxfjgh koyow (gfdsipy/ zmuminr)</span>" }
    b399 --> m322
    AhsLautaslhga --> z400["Sqcn: bbyytsazizi hrpi fni ixiavrj"]
    SmoIhnugzwwc --> z400
    z400 --> Zztk4Myvdy["Rqpth Wdibjoa"] & n418["Gktfni"] & v419["Uwxuxhv Ueuy"]
    Zztk4Myvdy --> VmpaEWum
    AmecsZwnbln1 --> t403["Cc zzoio dnhbqwz &gt;0 oqoh piv gfaq 7 ziia?"]
    t403 -- Iye --> d1
    t403 --> y404["Kk vnk_nhoyq &gt;10"]
    w407@{ label: "<span style=\"background-color:\">⚠️ Qqpjzgimjqby Adjv</span><br style=\"--tw-scale-x:\"><span style=\"background-color:\">Lkuy Yrskupij</span>" } --> m408(["Tkd: Lm Lmesd"])
    y404 -- Akopn --> w407
    o410["🚨 WWKAE: Wdibjoa uayb ri ijmymkdgdi"] --> z411(["Tkd: Ayvifo Kyysvd"])
    y404 -- Iogl --> o410
    v413["Adjv elm:<br>NWQ = NXZLI<br>"] --> h412@{ label: "Arczqhv Quuvlpwvk'p<br style=\"--tw-scale-x:\">HUMP ps Bbn Uficvu" }
    d1 -- Tnbttxw --> v413
    h412 --> HhflhzxFOT
    d1 -- Lxeo --> p414["Cc dnhbqwz mmi<b> vwlown mtla </b>&lt;0 ls =0?"]
    p414 -- &gs;0 --> p416["Adjv elm:<br>NWQ = GTRHY<br>"]
    p414 -- "=0" --> t415["Adjv elm:<br>NWQ = JRYC<br>"]
    t415 --> t2@{ label: "Arczqhv Quuvlpwvk'p<br style=\"--tw-scale-x:\">FGU ps Bbn Uficvu" }
    t2 --> HhflhzxFOT
    p416 --> t417@{ label: "Arczqhv Quuvlpwvk'p<br style=\"--tw-scale-x:\">JWJZ ps Bbn Uficvu" }
    t417 --> HhflhzxFOT
    n418 --> VmpaEWum
    v419 --> VmpaEWum
    x["x"] --> m["m"]
    s194[" "]
    m42["<br>"]
    k43["Xqwvx Nmhbgc"]
    x44["Lsqenrfa dbaf"]
    b45@{ label: "<span id=\"docs-internal-guid-661aa8df-7fff-5048-3055-c3f57db85bfd\"><span style=\"font-size:\">Kk</span></span>" }
    s46["Adjv elm<br>"]
    u47["Lmesd xtjt"]
    v48(["Viaj lse"])
    c49@{ label: "<span id=\"docs-internal-guid-c2a00f42-7fff-b434-7cde-df7ec58e9926\"><span style=\"font-size:\">Sknxqar</span></span>" }
    r50["Lm wqxay xtjt"]
    w52["Zsj sd jbhodm"]
    v59["Adjv lagbfh"]
    e195[" "]
    p196[" "]
    p263[" "]
    z311[" "]
    q312[" "]
    b370[" "]
    c371[" "]

    WrxtiZanqbj@{ shape: diamond}
    RykfMeesl@{ shape: rect}
    a369@{ shape: rect}
    d35@{ shape: rect}
    NuzdDdcvpahkssoj@{ shape: diamond}
    Rmos5@{ shape: rect}
    QvyiqhlJnpswxjk@{ shape: rect}
    z3@{ shape: rect}
    g4@{ shape: card}
    SmoIhnugzwwc@{ shape: rect}
    Ahgcn@{ shape: stadium}
    o420@{ shape: h-cyl}
    d1@{ shape: diam}
    o9@{ shape: rect}
    u14@{ shape: rect}
    k18@{ shape: rect}
    q19@{ shape: diam}
    f20@{ shape: diam}
    p27@{ shape: rect}
    b30@{ shape: rect}
    e6@{ shape: card}
    x10@{ shape: rect}
    f36@{ shape: rect}
    QbfpbzxFcy@{ shape: diamond}
    l37@{ shape: rect}
    y39@{ shape: rect}
    t40@{ shape: rect}
    e25@{ shape: rect}
    i51@{ shape: rect}
    e53@{ shape: rect}
    y55@{ shape: rect}
    f56@{ shape: rect}
    t58@{ shape: stadium}
    u64@{ shape: rect}
    g75@{ shape: rect}
    o73@{ shape: rect}
    c65@{ shape: rect}
    p78@{ shape: diam}
    z85@{ shape: rect}
    e259@{ shape: rect}
    f89@{ shape: rect}
    g91@{ shape: diam}
    d100@{ shape: rect}
    s132@{ shape: rect}
    c368@{ shape: rect}
    a140@{ shape: rect}
    t141@{ shape: rect}
    w143@{ shape: rect}
    a145@{ shape: rect}
    u142@{ shape: diam}
    v146@{ shape: rect}
    b147@{ shape: rect}
    t153@{ shape: rect}
    d157@{ shape: rect}
    b158@{ shape: rect}
    s160@{ shape: diam}
    h161@{ shape: rect}
    w162@{ shape: rect}
    e261@{ shape: card}
    d163@{ shape: rect}
    f164@{ shape: rect}
    e86@{ shape: rect}
    r170@{ shape: diam}
    m171@{ shape: diam}
    x172@{ shape: diam}
    q189@{ shape: rect}
    d191@{ shape: rect}
    f188@{ shape: rect}
    w192@{ shape: rect}
    m92@{ shape: rect}
    t173@{ shape: rect}
    u197@{ shape: diam}
    j198@{ shape: rect}
    f251@{ shape: rect}
    e252@{ shape: rect}
    s256@{ shape: rect}
    i131@{ shape: rect}
    w267@{ shape: rect}
    a268@{ shape: diam}
    u266@{ shape: rect}
    o265@{ shape: rect}
    n269@{ shape: diam}
    q270@{ shape: rect}
    j271@{ shape: rect}
    b272@{ shape: rect}
    c274@{ shape: rect}
    t275@{ shape: rect}
    d276@{ shape: diam}
    l278@{ shape: rect}
    b279@{ shape: rect}
    b280@{ shape: rect}
    p281@{ shape: rect}
    s283@{ shape: diam}
    j284@{ shape: rect}
    q285@{ shape: rect}
    b287@{ shape: rect}
    l288@{ shape: rect}
    d289@{ shape: rect}
    y290@{ shape: rect}
    y291@{ shape: rect}
    k292@{ shape: rect}
    i293@{ shape: diam}
    k294@{ shape: diam}
    q295@{ shape: diam}
    b301@{ shape: rect}
    g303@{ shape: rect}
    p304@{ shape: rect}
    x305@{ shape: rect}
    t306@{ shape: rect}
    n309@{ shape: rect}
    t262@{ shape: rect}
    k313@{ shape: diam}
    a314@{ shape: rect}
    w317@{ shape: rect}
    j319@{ shape: rect}
    u320@{ shape: diam}
    r321@{ shape: rect}
    m322@{ shape: rect}
    i333@{ shape: diam}
    t334@{ shape: diam}
    n335@{ shape: rect}
    e336@{ shape: rect}
    x337@{ shape: rect}
    y341@{ shape: rect}
    s138@{ shape: rect}
    z61@{ shape: diam}
    s343@{ shape: rect}
    m344@{ shape: rect}
    h346@{ shape: rect}
    k349@{ shape: rect}
    q345@{ shape: diam}
    g350@{ shape: rect}
    i352@{ shape: rect}
    i353@{ shape: rect}
    t354@{ shape: rect}
    m355@{ shape: diam}
    q356@{ shape: rect}
    z357@{ shape: rect}
    c358@{ shape: diam}
    c359@{ shape: diam}
    w360@{ shape: rect}
    c361@{ shape: rect}
    r362@{ shape: rect}
    b363@{ shape: rect}
    x365@{ shape: rect}
    e348@{ shape: rect}
    f347@{ shape: rect}
    q366@{ shape: rect}
    a139@{ shape: rect}
    s144@{ shape: rect}
    y367@{ shape: rect}
    EietNXS@{ shape: rect}
    s372@{ shape: diam}
    w402@{ shape: rect}
    w376@{ shape: diam}
    a377@{ shape: rect}
    s378@{ shape: rect}
    f380@{ shape: rect}
    y381@{ shape: diam}
    u382@{ shape: rect}
    g383@{ shape: rect}
    m384@{ shape: rect}
    f385@{ shape: diam}
    l386@{ shape: rect}
    i387@{ shape: rect}
    k388@{ shape: rect}
    a391@{ shape: diam}
    j394@{ shape: rect}
    k395@{ shape: rect}
    d396@{ shape: rect}
    d397@{ shape: rect}
    b399@{ shape: rect}
    v419@{ shape: rect}
    t403@{ shape: diam}
    y404@{ shape: diam}
    w407@{ shape: rect}
    o410@{ shape: rect}
    v413@{ shape: rect}
    h412@{ shape: rect}
    p414@{ shape: diam}
    p416@{ shape: rect}
    t415@{ shape: rect}
    t2@{ shape: rect}
    t417@{ shape: rect}
    s194@{ icon: "azure:update-management-center", pos: "b"}
    m42@{ shape: rect}
    k43@{ shape: text}
    x44@{ shape: rect}
    b45@{ shape: diam}
    s46@{ shape: rect}
    u47@{ shape: rect}
    c49@{ shape: card}
    r50@{ shape: rect}
    w52@{ shape: rect}
    v59@{ shape: rect}
    e195@{ icon: "azure:update-management-center", pos: "b"}
    p196@{ icon: "azure:update-management-center", pos: "b"}
    p263@{ icon: "azure:update-management-center", pos: "b"}
    z311@{ icon: "azure:update-management-center", pos: "b"}
    q312@{ icon: "azure:update-management-center", pos: "b"}
    b370@{ icon: "azure:update-management-center", pos: "b"}
    c371@{ icon: "azure:update-management-center", pos: "b"}
     Ogxs1:::Eijnb
     AmecsZwnbln1:::Eijnb
     HhflhzxFOT:::Eijnb
     Zjno2:::Eijnb
     Sdb1:::Tjlt
     XdekZGR:::Eijnb
     WrxtiZanqbj:::Eijnb
     SpnZucy:::Eijnb
     JzfQtt:::Eijnb
     RykfMeesl:::Eijnb
     XfsuIckitb:::Eijnb
     a369:::Eijnb
     d35:::Eijnb
     NuzdDdcvpahkssoj:::Eijnb
     Exb3:::Tjlt
     Rmos5:::Eijnb
     QvyiqhlJnpswxjk:::Eijnb
     z3:::Eijnb
     DmndaSpxbe:::Eijnb
     BguybGso:::Eijnb
     AhsLautaslhga:::Eijnb
     SmoIhnugzwwc:::Eijnb
     m7:::Brc
     d1:::Eijnb
     o9:::Eijnb
     u14:::Eijnb
     k18:::Eijnb
     q19:::Eijnb
     f20:::Eijnb
     p27:::Pmap
     l29:::Tjlt
     b30:::Eijnb
     ZlmjezYyo:::Pmap
     v17:::Tjlt
     x10:::Eijnb
     Knb2:::Tjlt
     QbfpbzxFcy:::Eijnb
     Bmn5:::Tjlt
     e25:::Pmap
     Jgc6:::Tjlt
     e53:::Eijnb
     y55:::Eijnb
     f56:::Eijnb
     t58:::Brc
     u64:::Eijnb
     g75:::Eijnb
     o73:::Eijnb
     c65:::Eijnb
     p78:::Eijnb
     a88:::Eijnb
     e259:::Eijnb
     f89:::Eijnb
     g91:::Eijnb
     d100:::Eijnb
     x103:::Eijnb
     s132:::Eijnb
     c368:::Eijnb
     a140:::Eijnb
     t141:::Eijnb
     w143:::Eijnb
     a145:::Eijnb
     u142:::Eijnb
     a148:::Tjlt
     t153:::Eijnb
     d157:::Eijnb
     b158:::Pmap
     i159:::Tjlt
     s160:::Eijnb
     w162:::Eijnb
     d163:::Eijnb
     f164:::Eijnb
     e86:::Eijnb
     b167:::Eijnb
     v168:::Eijnb
     k169:::Eijnb
     r170:::Eijnb
     m171:::Eijnb
     x172:::Eijnb
     q190:::Tjlt
     f188:::Pmap
     m92:::Pmap
     t173:::Eijnb
     u197:::Eijnb
     j198:::Eijnb
     t133:::Pmap
     r253:::Tjlt
     d257:::Tjlt
     w267:::Eijnb
     a268:::Eijnb
     u266:::Eijnb
     o265:::Eijnb
     n269:::Eijnb
     q270:::Eijnb
     b272:::Eijnb
     c274:::Eijnb
     t275:::Eijnb
     d276:::Eijnb
     l278:::Pmap
     b279:::Eijnb
     b280:::Eijnb
     p281:::Pmap
     e282:::Tjlt
     s283:::Eijnb
     q285:::Eijnb
     b287:::Eijnb
     l288:::Eijnb
     d289:::Eijnb
     y290:::Eijnb
     y291:::Eijnb
     k292:::Eijnb
     i293:::Eijnb
     k294:::Eijnb
     q295:::Eijnb
     n302:::Tjlt
     p304:::Pmap
     t306:::Pmap
     j310:::Tjlt
     t262:::Eijnb
     k313:::Eijnb
     n315:::Tjlt
     w317:::Eijnb
     j319:::Eijnb
     u320:::Eijnb
     r321:::Eijnb
     m322:::Eijnb
     i333:::Eijnb
     t334:::Eijnb
     n335:::Eijnb
     e336:::Eijnb
     x337:::Eijnb
     w342:::Tjlt
     s138:::Eijnb
     z61:::Eijnb
     s343:::Eijnb
     m344:::Eijnb
     h346:::Eijnb
     k349:::Eijnb
     q345:::Eijnb
     y351:::Tjlt
     i353:::Eijnb
     t354:::Eijnb
     m355:::Eijnb
     q356:::Eijnb
     z357:::Eijnb
     c358:::Eijnb
     c359:::Eijnb
     w360:::Eijnb
     c361:::Eijnb
     r362:::Eijnb
     c364:::Tjlt
     x365:::Eijnb
     e348:::Eijnb
     f347:::Eijnb
     q366:::Eijnb
     f84:::Eijnb
     a139:::Eijnb
     s144:::Eijnb
     y367:::Eijnb
     VmpaEWum:::Eijnb
     EietNXS:::Eijnb
     a391:::Eijnb
     j394:::Eijnb
     k395:::Eijnb
     d396:::Eijnb
     Zztk4Myvdy:::Eijnb
     v419:::Eijnb
     m408:::Tjlt
     z411:::Tjlt
     v413:::Eijnb
     h412:::Eijnb
     p416:::Eijnb
     t415:::Eijnb
     t2:::Eijnb
     t417:::Eijnb
     m42:::Brc
     x44:::Eijnb
     b45:::Eijnb
     s46:::Eijnb
     v48:::Tjlt
     w52:::Pmap
     v59:::Eijnb
    classDef Brc stroke-width:1px, stroke-dasharray:none, stroke:#999999, fill:#EEEEEE, color:#000000
    classDef Pmap stroke-width:1px, stroke-dasharray:none, stroke:#254336, fill:#27654A, color:#FFFFFF
    classDef Tjlt stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236
    classDef Eijnb stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    style Ogxs1 stroke:#FF6D00
    style AmecsZwnbln1 fill:#BBDEFB,stroke:#2962FF,color:#000000
    style Gkxqo1 fill:#ff6b6b
    style Zjno2 stroke:#FF6D00
    style RykfMeesl color:#000000
    style XfsuIckitb color:#000000
    style a369 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style d35 color:#000000,fill:#FFF9C4
    style BgWtpunob fill:#95e1d3
    style IsexlqaagglRdyk fill:#ff6b6b
    style Rmos5 stroke:#FF6D00
    style g4 fill:#E1BEE7,stroke:#AA00FF,stroke-width:2px,stroke-dasharray: 2
    style AhsLautaslhga fill:#FFE0B2
    style SmoIhnugzwwc fill:#FFE0B2
    style m7 stroke:#000000
    style d1 fill:#FFD600
    style o9 fill:#FFF9C4,stroke:#FFD600
    style e6 fill:#E1BEE7,stroke:#AA00FF,stroke-width:2px,stroke-dasharray: 2
    style x10 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style f36 fill:#95e1d3
    style QbfpbzxFcy color:none
    style l37 fill:#ff6b6b
    style y39 fill:#ff6b6b
    style t40 fill:#ff6b6b
    style i51 fill:#ff6b6b
    style t58 stroke:#000000
    style u64 color:none
    style p78 color:none
    style z85 fill:#BBDEFB,stroke:#2962FF
    style f89 fill:#BBDEFB,stroke:#2962FF,color:#000000
    style g91 color:none
    style d100 fill:#BBDEFB,color:#000000,stroke:#2962FF
    style s132 color:none,fill:#FFD600
    style c368 stroke:#FF6D00
    style a140 color:#000000
    style t141 color:#000000
    style w143 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style a145 color:#000000,fill:#FFF9C4
    style v146 fill:#95e1d3
    style b147 fill:#ff6b6b
    style d157 color:none
    style s160 color:none
    style h161 fill:#ff6b6b
    style e261 fill:#E1BEE7,stroke:#AA00FF,stroke-width:2px,stroke-dasharray: 2
    style e86 color:#000000,fill:#BBDEFB,stroke:#2962FF
    style q189 fill:#95e1d3
    style d191 fill:#ff6b6b
    style w192 fill:#ff6b6b
    style t173 color:none,fill:#FFD600
    style j198 color:#D50000,fill:#FFD600
    style f251 fill:#ff6b6b
    style t133 fill:#FFD600,color:#000000
    style e252 fill:#95e1d3
    style s256 fill:#95e1d3
    style i131 fill:#FFD600,stroke:#2962FF
    style a268 color:none
    style q270 stroke:#FF6D00
    style j271 fill:#BBDEFB,stroke:#2962FF
    style t275 fill:#BBDEFB,stroke:#2962FF,color:#000000
    style d276 color:none
    style b280 color:none
    style s283 color:none
    style j284 fill:#ff6b6b
    style d289 color:#000000,fill:#BBDEFB,stroke:#2962FF
    style b301 fill:#95e1d3
    style g303 fill:#ff6b6b
    style x305 fill:#ff6b6b
    style n309 fill:#95e1d3
    style t262 color:none
    style a314 fill:#95e1d3
    style w317 stroke:#FF6D00
    style j319 fill:#FFD600
    style r321 fill:#FFD600
    style n335 fill:#FFE0B2
    style e336 fill:#FFE0B2
    style x337 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style y341 fill:#95e1d3
    style s138 stroke:#FF6D00
    style z61 color:none
    style s343 color:#000000
    style m344 color:#000000
    style h346 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style k349 color:#000000,fill:#FFF9C4
    style g350 fill:#95e1d3
    style i352 fill:#ff6b6b
    style i353 stroke:#FF6D00
    style t354 fill:#FFD600
    style q356 fill:#FFD600
    style w360 fill:#FFE0B2
    style c361 fill:#FFE0B2
    style r362 fill:#FFF9C4,stroke:#FFD600,color:#000000
    style b363 fill:#95e1d3
    style x365 stroke:#FF6D00
    style e348 color:#000000
    style f347 fill:#FFD600,color:#000000
    style q366 stroke:#FF6D00
    style f84 stroke:#FF6D00
    style a139 color:#000000
    style s144 fill:#FFD600,color:#000000
    style y367 color:none
    style VmpaEWum color:#000000
    style EietNXS fill:#FFF9C4,color:#000000
    style s372 fill:#FFD600
    style c373 fill:#FFD600
    style z374 fill:#FFD600
    style w402 fill:#FFD600
    style m375 stroke:#000000,fill:#FFD600
    style w376 fill:#FFD600
    style a377 fill:#FFD600
    style s378 fill:#FFD600
    style f379 stroke:#000000,fill:#FFD600
    style f380 fill:#FFD600
    style y381 fill:#FFD600
    style u382 fill:#FFD600
    style g383 fill:#FFD600
    style m384 stroke:#000000,fill:#FFD600
    style f385 fill:#FFD600
    style l386 fill:#FFD600
    style i387 fill:#FFD600
    style k388 stroke:#000000,fill:#FFD600
    style j389 fill:#FFD600
    style a391 stroke:#FFD600,fill:#FFD600
    style j394 fill:#FFD600,stroke:#FFD600
    style k395 fill:#FFD600,stroke:#FFD600
    style d396 fill:#FFD600,stroke:#000000
    style d397 fill:#E1BEE7,stroke:#FFD600
    style n398 fill:#FFD600
    style b399 fill:#FFD600
    style z400 fill:#FFD600
    style Zztk4Myvdy stroke:#000000,fill:#FFD600
    style n418 fill:#FFD600
    style v419 stroke:#000000,fill:#FFD600
    style t403 fill:#FFD600
    style y404 fill:#FFD600
    style w407 fill:#95e1d3
    style o410 fill:#ff6b6b
    style v413 fill:#FFF9C4,stroke:#FFD600
    style p414 fill:#FFD600
    style p416 fill:#FFF9C4,stroke:#FFD600
    style t415 fill:#FFF9C4,stroke:#FFD600
    style s194 fill:transparent
    style s46 fill:#FFF9C4,stroke:#FFD600
    style u47 fill:#ff6b6b
    style c49 fill:#E1BEE7,stroke:#AA00FF,stroke-width:2px,stroke-dasharray: 2
    style r50 fill:#95e1d3
    style v59 fill:#BBDEFB,stroke:#2962FF,color:#000000
    style e195 fill:transparent
    style p196 fill:transparent
    style p263 fill:transparent
    style z311 fill:transparent
    style q312 fill:transparent
    style b370 fill:transparent
    style c371 fill:transparent
