---
config:
  sequence:
    useMaxWidth: false
---
sequenceDiagram
    participant A
    participant B
    Note over B: $$(sk_B, pk_B)\leftarrow KeyGen(1^\lambda)$$
    Note left of B: $$(sk_B, pk_B)\leftarrow KeyGen(1^\lambda)$$
    A->>B: Message
