---
config:
  logLevel: 1
  htmlLabels: true
  layout: dagre
---
classDiagram
  note "I love this diagram!
  Do you love it?"
  class Class10 {
    int id
  size()
  }
  note for Class10 "Cool class
  I said it's very cool class!"
