---
config:
  logLevel: 1
  htmlLabels: true
  layout: dagre
---
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#BB2528',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F83d29',
      'secondaryColor': '#006100',
      'tertiaryColor': '#fff'
    }
  }
  }%%
  classDiagram
  Class01 <|-- AveryLongClass : Cool
  &lt;&lt;interface&gt;&gt; Class01
  Class03 *-- Class04
  Class05 o-- Class06
  Class07 .. Class08
  Class09 --> C2 : Where am i?
  Class09 --* C3
  Class09 --|> Class07
  Class12 <|.. Class08
  Class11 ..>Class12
  Class07 : equals()
  Class07 : Object[] elementData
  Class01 : size()
  Class01 : int chimp
  Class01 : int gorilla
  Class01 : -int privateChimp
  Class01 : +int publicGorilla
  Class01 : #int protectedMarmoset
  Class08 <--> C2: Cool label
  class Class10 {
    &lt;&lt;service&gt;&gt;
    int id
    test()
  }
