---
config:
  logLevel: 1
  htmlLabels: false
  layout: dagre
---
classDiagram
  class Class10:::pink
  cssClass "Class10" bold
  classDef pink fill:#f9f
  classDef bold stroke:#333,stroke-width:6px,color:#fff
