---
config:
  logLevel: 1
  htmlLabels: true
  layout: dagre
---
classDiagram
  class Class10 {
  int[] id
  List~int~ ids
  test(List~int~ ids) List~bool~
  testArray() bool[]
  }

  cssClass "Class10" exClass2
