---
config:
  logLevel: 1
  htmlLabels: true
  layout: dagre
---
classDiagram
  namespace Company.Engineering.Backend {
  class Developer {
    +writeCode()
  }
  }
  namespace Company.Engineering.Frontend {
  class Designer {
    +createMockup()
  }
  }
  namespace Company.Engineering {
  class TechLead {
    +planSprint()
  }
  }
  TechLead --> Developer : leads
  TechLead --> Designer : leads
