---
config:
  logLevel: 1
  htmlLabels: false
  layout: dagre
---
classDiagram
  class Class10 {
  +attribute *italic**
  ~attribute **bold***
  _italicmethod_()
  __boldmethod__()
  _+_swim_()a_
  __+quack() test__
  }
